// Runtime/nodedefs/BuiltinNodeDefs_Conversion.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Conversion() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Conversion(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("IntToFloat", "Int To Float", "Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");
    

    reg("FloatToInt", "Float To Int", "Conversion",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Integer) },
        "80C3F8", "Simple");
    

    reg("IntToString", "Int To String", "Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::String) },
        "C880F8", "Simple");
    

    reg("FloatToString", "Float To String", "Conversion",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) },
        "C880F8", "Simple");
    

    reg("StringToInt", "String To Int", "Conversion",
        { MakePin("Value", PinDataType::String) },
        { MakePin("Result", PinDataType::Integer) },
        "F8A030", "Simple");
    

    reg("StringToFloat", "String To Float", "Conversion",
        { MakePin("Value", PinDataType::String) },
        { MakePin("Result", PinDataType::Float) },
        "F8A030", "Simple");
    

    reg("BoolToInt", "Bool To Int", "Conversion",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Integer) },
        "", "Simple");
    

    reg("IntToBool", "Int To Bool", "Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");
    

    reg("ToString", "To String", "Conversion",
        { MakePin("Value", PinDataType::Any) },
        { MakePin("Result", PinDataType::String) },
        "C880F8", "Simple");
    
}

// Event 节点

} // namespace Runtime
} // namespace NodeEditor