// Runtime/nodedefs/BuiltinNodeDefs_EventBus.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_EventBus() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_EventBus(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("Event.Fire", "Fire Event", "Event",
        { MakeFlowPin(""), MakePin("EventName", PinDataType::String), MakePin("Payload", PinDataType::Any) },
        { MakeFlowPin("") },
        "FF6040");

    reg("Event.Subscribe", "Bind Event", "Event",
        { MakeFlowPin(""), MakePin("EventName", PinDataType::String) },
        { MakeFlowPin(""), MakePin("SubscriptionId", PinDataType::Integer) },
        "FF6040");

    reg("Event.Unsubscribe", "Unbind Event", "Event",
        { MakeFlowPin(""), MakePin("SubscriptionId", PinDataType::Integer) },
        { MakeFlowPin("") },
        "FF6040");

    reg("Event.OnEvent", "On Event", "Event",
        {},
        { MakeFlowPin(""), MakePin("EventName", PinDataType::String), MakePin("Payload", PinDataType::Any) },
        "FF8060");
}

// ============================================================================
// File I/O 节点定义
// 颜色：4CAF50（绿色，区别于 Network 蓝 / AI 紫）
// ============================================================================
// ============================================================================
// Retry 节点定义
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor