// Runtime/nodedefs/BuiltinNodeDefs_Save.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Save() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Save(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    const char* SAVE_COLOR = "C47A2B"; // 琥珀色

    reg("Save.Write", "Save Write", "Game/Save",
        { MakeFlowPin(""),
          MakePin("Slot",  PinDataType::String),
          MakePin("Key",   PinDataType::String),
          MakePin("Value", PinDataType::Any) },
        { MakeFlowPin("exec"),
          MakePin("Success",      PinDataType::Boolean),
          MakePin("ErrorMessage", PinDataType::String) },
        SAVE_COLOR);

    reg("Save.Read", "Save Read", "Game/Save",
        { MakePin("Slot",    PinDataType::String),
          MakePin("Key",     PinDataType::String),
          MakePin("Default", PinDataType::Any) },
        { MakePin("Value", PinDataType::Any),
          MakePin("Found", PinDataType::Boolean) },
        SAVE_COLOR, "Simple");

    reg("Save.Exists", "Save Exists", "Game/Save",
        { MakePin("Slot", PinDataType::String) },
        { MakePin("Exists", PinDataType::Boolean) },
        SAVE_COLOR, "Simple");

    reg("Save.Delete", "Save Delete", "Game/Save",
        { MakeFlowPin(""), MakePin("Slot", PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("Success", PinDataType::Boolean) },
        SAVE_COLOR);

    reg("Save.ListSlots", "Save List Slots", "Game/Save",
        {},
        { MakePin("Slots", PinDataType::Array),
          MakePin("Count", PinDataType::Integer) },
        SAVE_COLOR, "Simple");

    reg("Save.ExportJSON", "Save Export JSON", "Game/Save",
        { MakePin("Slot", PinDataType::String) },
        { MakePin("JSON",  PinDataType::String),
          MakePin("Found", PinDataType::Boolean) },
        SAVE_COLOR, "Simple");

    reg("Save.ImportJSON", "Save Import JSON", "Game/Save",
        { MakeFlowPin(""),
          MakePin("Slot", PinDataType::String),
          MakePin("JSON", PinDataType::String) },
        { MakeFlowPin("exec"),
          MakePin("Success",      PinDataType::Boolean),
          MakePin("ErrorMessage", PinDataType::String) },
        SAVE_COLOR);

    reg("Save.Clear", "Save Clear", "Game/Save",
        { MakeFlowPin(""), MakePin("Slot", PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("Success", PinDataType::Boolean) },
        SAVE_COLOR);

    reg("Save.GetKeys", "Save Get Keys", "Game/Save",
        { MakePin("Slot", PinDataType::String) },
        { MakePin("Keys",  PinDataType::Array),
          MakePin("Count", PinDataType::Integer) },
        SAVE_COLOR, "Simple");

    reg("Save.WriteMultiple", "Save Write Multiple", "Game/Save",
        { MakeFlowPin(""),
          MakePin("Slot", PinDataType::String),
          MakePin("Data", PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("Success", PinDataType::Boolean) },
        SAVE_COLOR);
}

// ============================================================================
// GameMath — Vec2/Vec3、物理碰撞辅助、Stat 数值系统、Cooldown
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor