// Runtime/nodedefs/BuiltinNodeDefs_Socket.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Socket() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Socket(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    const char* TCP_COLOR = "1565C0"; // 深蓝
    const char* UDP_COLOR = "00838F"; // 青绿

    // ── TCP ──────────────────────────────────────────────────────────────────
    reg("TCP.Listen", "TCP Listen", "Network/TCP",
        {
            MakeFlowPin(""),
            MakePin("Host",       PinDataType::String),
            MakePin("Port",       PinDataType::Integer),
            MakePin("BufferSize", PinDataType::Integer),
        },
        {
            MakeFlowPin(""),
            MakeFlowPin("onAccept"),
            MakeFlowPin("onData"),
            MakeFlowPin("onDisconnect"),
            MakePin("Success",  PinDataType::Boolean),
            MakePin("ConnId",   PinDataType::String),
            MakePin("PeerAddr", PinDataType::String),
            MakePin("PeerPort", PinDataType::Integer),
            MakePin("Data",     PinDataType::String),
        },
        TCP_COLOR);

    reg("TCP.Connect", "TCP Connect", "Network/TCP",
        {
            MakeFlowPin(""),
            MakePin("Host",       PinDataType::String),
            MakePin("Port",       PinDataType::Integer),
            MakePin("BufferSize", PinDataType::Integer),
        },
        {
            MakeFlowPin(""),
            MakeFlowPin("onConnected"),
            MakeFlowPin("onData"),
            MakeFlowPin("onDisconnect"),
            MakeFlowPin("onError"),
            MakePin("ConnId",       PinDataType::String),
            MakePin("Data",         PinDataType::String),
        },
        TCP_COLOR);

    reg("TCP.Send", "TCP Send", "Network/TCP",
        {
            MakeFlowPin(""),
            MakePin("ConnId", PinDataType::String),
            MakePin("Data",   PinDataType::String),
        },
        {
            MakeFlowPin(""),
            MakePin("Success",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        TCP_COLOR);

    reg("TCP.Disconnect", "TCP Disconnect", "Network/TCP",
        {
            MakeFlowPin(""),
            MakePin("ConnId", PinDataType::String),
        },
        { MakeFlowPin("") },
        TCP_COLOR);

    reg("TCP.Stop", "TCP Stop", "Network/TCP",
        {
            MakeFlowPin(""),
            MakePin("ServerKey", PinDataType::String),
        },
        { MakeFlowPin("") },
        TCP_COLOR);

    // ── UDP ──────────────────────────────────────────────────────────────────
    reg("UDP.Bind", "UDP Bind", "Network/UDP",
        {
            MakeFlowPin(""),
            MakePin("Host",       PinDataType::String),
            MakePin("Port",       PinDataType::Integer),
            MakePin("BufferSize", PinDataType::Integer),
        },
        {
            MakeFlowPin(""),
            MakeFlowPin("onData"),
            MakePin("Success",  PinDataType::Boolean),
            MakePin("FromAddr", PinDataType::String),
            MakePin("FromPort", PinDataType::Integer),
            MakePin("Data",     PinDataType::String),
        },
        UDP_COLOR);

    reg("UDP.Send", "UDP Send", "Network/UDP",
        {
            MakeFlowPin(""),
            MakePin("Host", PinDataType::String),
            MakePin("Port", PinDataType::Integer),
            MakePin("Data", PinDataType::String),
        },
        {
            MakeFlowPin(""),
            MakePin("Success",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        UDP_COLOR);

    reg("UDP.Close", "UDP Close", "Network/UDP",
        {
            MakeFlowPin(""),
            MakePin("Port", PinDataType::Integer),
        },
        { MakeFlowPin("") },
        UDP_COLOR);
}

// ============================================================================
// GameExtra — Random / Easing / GameTimer / Entity / Inventory
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor