// Runtime/nodedefs/BuiltinNodeDefs_AI_JSON.cpp
// Generated by tools/split_nodedefs_ai.ps1 from BuiltinNodeDefs_AI.cpp
//
// Contains the RegisterNodeDefs_AI_JSON() function, registering AI/JSON
// node definitions. Called by RegisterNodeDefs_AI().
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

void RegisterNodeDefs_AI_JSON(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };
    // JSON.Build — 从 Keys/Values 数组构建 JSON 对象字符串
    reg("JSON.Build", "JSON Build", "AI/JSON",
        {
            MakePin("Keys",   PinDataType::Array),   // Array<String>
            MakePin("Values", PinDataType::Array),   // Array<Any>
        },
        {
            MakePin("JSON", PinDataType::String),
        },
        "6A0572", "Simple");

    // JSON.SetPath — 向 JSON 对象设置嵌套路径
    reg("JSON.SetPath", "JSON Set Path", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",  PinDataType::String),
            MakePin("Path",  PinDataType::String),   // e.g. "choices[0].message.content"
            MakePin("Value", PinDataType::Any),
        },
        {
            MakeFlowPin(""),
            MakePin("JSON",  PinDataType::String),
        },
        "6A0572");

    // JSON.ArrayPush — 向 JSON 数组追加元素
    reg("JSON.ArrayPush", "JSON Array Push", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",    PinDataType::String),
            MakePin("Element", PinDataType::Any),
        },
        {
            MakeFlowPin(""),
            MakePin("JSON",   PinDataType::String),
            MakePin("Length", PinDataType::Integer),
        },
        "6A0572");

    // JSON.MakeMessage — 构造 {"role":"...","content":"..."} 消息对象
    reg("JSON.MakeMessage", "Make Message", "AI/JSON",
        {
            MakePin("Role",       PinDataType::String),   // "user" | "assistant" | "system" | "tool"
            MakePin("Content",    PinDataType::String),
            MakePin("ToolCallId", PinDataType::String),   // optional; for role="tool" responses
        },
        {
            MakePin("Message", PinDataType::String),
        },
        "6A0572", "Simple");

    //        Index(Integer)        — 要取第几个（默认 0）
    //   out: Name(String)          — function name
    //        ArgumentsJSON(String) — arguments 对象 JSON 字符串
    //        ID(String)            — tool_call id（回传给 LLM 时需要）
    reg("JSON.ParseToolCall", "Parse Tool Call", "AI/JSON",
        {
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("Index",         PinDataType::Integer),
        },
        {
            MakePin("Name",          PinDataType::String),
            MakePin("ArgumentsJSON", PinDataType::String),
            MakePin("ID",            PinDataType::String),
        },
        "2E86AB");

    // ── JSON.MakeToolResult ─────────────────────────────────────────────────
    // 构造 tool role 消息，把工具结果反馈给 LLM
    //   in:  ToolCallID(String), Content(String)
    //   out: JSON(String) — {"role":"tool","tool_call_id":"...","content":"..."}
    reg("JSON.MakeToolResult", "Make Tool Result", "AI/JSON",
        {
            MakePin("ToolCallID", PinDataType::String),
            MakePin("Content",    PinDataType::String),
        },
        {
            MakePin("JSON", PinDataType::String),
        },
        "2E86AB");

    // ── JSON.ToolCallCount ──────────────────────────────────────────────────
    // 返回 tool_calls 数组长度（用于并行工具调用循环）
    reg("JSON.ToolCallCount", "Tool Call Count", "AI/JSON",
        { MakePin("ToolCallsJSON", PinDataType::String), },
        { MakePin("Count",         PinDataType::Integer), },
        "2E86AB");

    // ── JSON.Extract ────────────────────────────────────────────────────────
    reg("JSON.Extract", "JSON Extract", "AI/JSON",
        {
            MakePin("Text", PinDataType::String),
        },
        {
            MakePin("JSON",  PinDataType::String),
            MakePin("Found", PinDataType::Boolean),
        },
        "6A0572", "Simple");

    // ── JSON.Validate ───────────────────────────────────────────────────────
    reg("JSON.Validate", "JSON Validate", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",         PinDataType::String),
            MakePin("RequiredKeys", PinDataType::String),
        },
        {
            MakeFlowPin("onValid"),
            MakeFlowPin("onInvalid"),
            MakePin("IsValid",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // Schema.Validate — 验证 JSON 是否符合 Schema
    reg("Schema.Validate", "Schema Validate", "AI/JSON",
        {
            MakePin("JSON",   PinDataType::String),
            MakePin("Schema", PinDataType::String),
        },
        {
            MakeFlowPin("onPass"),
            MakeFlowPin("onFail"),
            MakePin("IsValid",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572", "Simple");

}

} // namespace Runtime
} // namespace NodeEditor