// Runtime/nodedefs/BuiltinNodeDefs_Map.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Map() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Map(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("MakeMap", "Make Map", "Misc/Map",
        { MakePin("Key 0", PinDataType::Any), MakePin("Value 0", PinDataType::Any) },
        { MakePin("Map", PinDataType::Map) },
        "", "Simple");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("MakeMap"));
        if (d) d->customProperties["dynamicInputs"] = "Any";
    }

    reg("MapGet", "Map Get", "Misc/Map",
        { MakePin("Map", PinDataType::Map), MakePin("Key", PinDataType::Any) },
        { MakePin("Value", PinDataType::Any), MakePin("Found", PinDataType::Boolean) },
        "20CCDD", "Simple");
    

    reg("MapSet", "Map Set", "Misc/Map",
        { MakeFlowPin(""), MakePin("Map", PinDataType::Map), MakePin("Key", PinDataType::Any), MakePin("Value", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Result", PinDataType::Map) },
        "20CCDD");
    

    reg("MapRemove", "Map Remove", "Misc/Map",
        { MakeFlowPin(""), MakePin("Map", PinDataType::Map), MakePin("Key", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Result", PinDataType::Map) },
        "20CCDD");
    

    reg("MapHasKey", "Map Has Key", "Misc/Map",
        { MakePin("Map", PinDataType::Map), MakePin("Key", PinDataType::Any) },
        { MakePin("Result", PinDataType::Boolean) },
        "20CCDD", "Simple");
    

    reg("MapLength", "Map Length", "Misc/Map",
        { MakePin("Map", PinDataType::Map) },
        { MakePin("Length", PinDataType::Integer) },
        "20CCDD", "Simple");
    

    // Keep legacy MapSize for backward compatibility
    reg("MapSize", "Map Size", "Misc/Map",
        { MakePin("Map", PinDataType::Map) },
        { MakePin("Size", PinDataType::Integer) },
        "20CCDD", "Simple");

    reg("MapKeys", "Map Keys", "Misc/Map",
        { MakePin("Map", PinDataType::Map) },
        { MakePin("Keys", PinDataType::Array) },
        "20CCDD", "Simple");
    

    reg("MapValues", "Map Values", "Misc/Map",
        { MakePin("Map", PinDataType::Map) },
        { MakePin("Values", PinDataType::Array) },
        "20CCDD", "Simple");
    

    reg("MapClear", "Map Clear", "Misc/Map",
        { MakeFlowPin(""), MakePin("Map", PinDataType::Map) },
        { MakeFlowPin(""), MakePin("Result", PinDataType::Map) },
        "20CCDD");
    

    reg("MapMerge", "Map Merge", "Misc/Map",
        { MakeFlowPin(""), MakePin("Map A", PinDataType::Map), MakePin("Map B", PinDataType::Map) },
        { MakeFlowPin(""), MakePin("Map", PinDataType::Map) },
        "20CCDD");

    reg("ForEachMapLoop", "For Each Map", "Misc/Map",
        { MakeFlowPin(""), MakePin("Map", PinDataType::Map) },
        { MakeFlowPin("Loop Body"), MakePin("Key", PinDataType::Any),
          MakePin("Value", PinDataType::Any), MakeFlowPin("Completed") });

    // ── Set 节点定义 ──────────────────────────────────────────────────────
    reg("MakeSet", "Make Set", "Misc/Set",
        { MakePin("Value 0", PinDataType::Any) },
        { MakePin("Set", PinDataType::Set) },
        "B464F0", "Simple");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("MakeSet"));
        if (d) d->customProperties["dynamicInputs"] = "Any";
    }

    reg("SetAdd", "Set Add", "Misc/Set",
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set), MakePin("Value", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set), MakePin("Added", PinDataType::Boolean) },
        "B464F0");

    reg("SetRemove", "Set Remove", "Misc/Set",
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set), MakePin("Value", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set), MakePin("Removed", PinDataType::Boolean) },
        "B464F0");

    reg("SetContains", "Set Contains", "Misc/Set",
        { MakePin("Set", PinDataType::Set), MakePin("Value", PinDataType::Any) },
        { MakePin("Result", PinDataType::Boolean) },
        "B464F0", "Simple");

    reg("SetSize", "Set Size", "Misc/Set",
        { MakePin("Set", PinDataType::Set) },
        { MakePin("Size", PinDataType::Integer) },
        "B464F0", "Simple");

    reg("SetLength", "Set Length", "Misc/Set",
        { MakePin("Set", PinDataType::Set) },
        { MakePin("Size", PinDataType::Integer) },
        "B464F0", "Simple");

    reg("SetClear", "Set Clear", "Misc/Set",
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set) },
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set) },
        "B464F0");

    reg("SetToArray", "Set To Array", "Misc/Set",
        { MakePin("Set", PinDataType::Set) },
        { MakePin("Array", PinDataType::Array) },
        "B464F0", "Simple");

    reg("SetFromArray", "Set From Array", "Misc/Set",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Set", PinDataType::Set) },
        "B464F0", "Simple");

    reg("ForEachSetLoop", "For Each Set", "Misc/Set",
        { MakeFlowPin(""), MakePin("Set", PinDataType::Set) },
        { MakeFlowPin("Loop Body"), MakePin("Value", PinDataType::Any),
          MakePin("Index", PinDataType::Integer), MakeFlowPin("Completed") },
        "B464F0");
}


} // namespace Runtime
} // namespace NodeEditor