// Runtime/nodedefs/BuiltinNodeDefs_Retry.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Retry() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Retry(INodeRegistry& registry)
{
    // MakePin / MakeFlowPin 使用文件顶部的自由函数
    auto MakePinDef = [](const char* n, PinDataType t, Variant dv) {
        PinDefinition p = MakePin(n, t);
        p.defaultValue = dv;
        return p;
    };

    // Retry.Backoff — 同步重试循环，支持指数退避（退避为元数据，实际 Delay 需配合 Delay 节点）
    {
        NodeDefinition d;
        d.id       = "Retry.Backoff";
        d.name     = "Retry Backoff";
        d.category = "Flow/Retry";
        d.color    = "E67E22";  // 橙色

        d.inputPins = {
            MakeFlowPin(""),
            MakePinDef("MaxRetries",        PinDataType::Integer, Variant((int64_t)3)),
            MakePinDef("InitialDelayMs",    PinDataType::Float,   Variant(500.0)),
            MakePinDef("BackoffMultiplier", PinDataType::Float,   Variant(2.0)),
            MakePinDef("MaxDelayMs",        PinDataType::Float,   Variant(10000.0)),
        };
        d.outputPins = {
            MakeFlowPin("onTry"),
            MakePin("AttemptIndex", PinDataType::Integer),
            MakePin("DelayMs",      PinDataType::Float),
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onExceeded"),
        };
        d.description =
            "Retry loop with exponential backoff. "
            "Each attempt activates onTry. Set blueprint variable "
            "'__retry_succeeded'=true inside the onTry body to exit early "
            "via onSuccess. All retries exhausted → onExceeded.";
        registry.registerNode(d);
    }
}


} // namespace Runtime
} // namespace NodeEditor