// Runtime/nodedefs/BuiltinNodeDefs_Misc.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Misc() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Misc(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("Message", "Message", "Misc",
        {},
        { MakePin("Message", PinDataType::String) },
        "80C3F8", "Simple");

    // Comment (special)
    {
        NodeDefinition d;
        d.id = "Comment";
        d.name = "Comment";
        d.category = "Misc";
        d.customProperties["editorType"] = "Comment";
        d.defaultSize = {300, 200};
        registry.registerNode(d);
    }

    reg("GetVariable", "Get Variable", "Variables",
        { MakePin("Name", PinDataType::String) },
        { MakePin("Value", PinDataType::String) },
        "50C878", "Simple");

    reg("SetVariable", "Set Variable", "Variables",
        { MakeFlowPin(""), MakePin("Name", PinDataType::String),
          MakePin("Value", PinDataType::String) },
        { MakeFlowPin("") },
        "50C878");

    reg("IsValid", "Is Valid", "Misc",
        { MakePin("Value", PinDataType::Any) },
        { MakePin("Is Valid", PinDataType::Boolean) },
        "", "Simple");

    reg("MakeLiteralBool", "Make Literal Bool", "Misc",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("MakeLiteralInt", "Make Literal Int", "Misc",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Integer) },
        "", "Simple");

    reg("MakeLiteralFloat", "Make Literal Float", "Misc",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "", "Simple");

    reg("MakeLiteralString", "Make Literal String", "Misc",
        { MakePin("Value", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // ── Object 引脚 Demo 节点（Object/Demo 分类）─────────────────────────
    // 演示 PinDataType::Object 类型引脚的使用场景
    // Object 值在运行时以字符串存储（对象引用 ID / 路径 / 名称）

    // MakeObject — 用字符串 ID 构造一个对象引用
    reg("Object.Make", "Make Object Ref", "Object",
        { MakePin("ObjectId", PinDataType::String) },
        { MakePin("Object", PinDataType::Object) },
        "C86428", "Simple");

    // GetObjectId — 从对象引用中提取 ID 字符串
    reg("Object.GetId", "Get Object Id", "Object",
        { MakePin("Object", PinDataType::Object) },
        { MakePin("ObjectId", PinDataType::String) },
        "C86428", "Simple");

    // IsObjectValid — 检查对象引用是否非空
    reg("Object.IsValid", "Is Object Valid", "Object",
        { MakePin("Object", PinDataType::Object) },
        { MakePin("Is Valid", PinDataType::Boolean) },
        "C86428", "Simple");

    // SetObjectProperty — 在全局属性表中为对象设置一个命名属性
    reg("Object.SetProperty", "Set Object Property", "Object",
        { MakeFlowPin(""),
          MakePin("Object",   PinDataType::Object),
          MakePin("Key",      PinDataType::String),
          MakePin("Value",    PinDataType::String) },
        { MakeFlowPin("") },
        "C86428");

    // GetObjectProperty — 读取对象命名属性
    reg("Object.GetProperty", "Get Object Property", "Object",
        { MakePin("Object",   PinDataType::Object),
          MakePin("Key",      PinDataType::String) },
        { MakePin("Value",    PinDataType::String),
          MakePin("Found",    PinDataType::Boolean) },
        "C86428", "Simple");

    // PrintObject — 打印对象 ID 及其所有属性
    reg("Object.Print", "Print Object", "Object",
        { MakeFlowPin(""),
          MakePin("Object",   PinDataType::Object),
          MakePin("Label",    PinDataType::String) },
        { MakeFlowPin("") },
        "C86428");

    // EqualObjects — 比较两个对象引用是否相同（按 ID）
    reg("Object.Equal", "Equal Objects", "Object",
        { MakePin("A", PinDataType::Object),
          MakePin("B", PinDataType::Object) },
        { MakePin("Result", PinDataType::Boolean) },
        "C86428", "Simple");

    // EventBus.Emit — 广播一个具名事件（携带可选 payload）
    reg("EventBusEmit", "EventBus: Emit", "Misc/EventBus",
        { MakeFlowPin(""), MakePin("Event", PinDataType::String),
          MakePin("Payload", PinDataType::Any) },
        { MakeFlowPin("") },
        "F5A623");

    // EventBus.Subscribe — 监听具名事件（每次触发时激活 On Event 输出）
    reg("EventBusSubscribe", "EventBus: Subscribe", "Misc/EventBus",
        { MakeFlowPin("Enable"), MakeFlowPin("Disable"),
          MakePin("Event", PinDataType::String) },
        { MakeFlowPin("On Event"), MakePin("Payload", PinDataType::Any) },
        "F5A623");

    // EventBus.Clear — 移除某个事件的全部监听者
    reg("EventBusClear", "EventBus: Clear", "Misc/EventBus",
        { MakeFlowPin(""), MakePin("Event", PinDataType::String) },
        { MakeFlowPin("") },
        "F5A623");
}

// ============================================================================
// 入口函数
// ============================================================================

// Conversion 类型转换节点

} // namespace Runtime
} // namespace NodeEditor