// Runtime/nodedefs/BuiltinNodeDefs_Function.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Function() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Function(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("Function.Entry", "Function Entry", "Function",
        {},
        { MakeFlowPin("") },
        "60C060");

    reg("Function.Return", "Function Return", "Function",
        { MakeFlowPin("") },
        {},
        "60C060");

    reg("Function.Call", "Call Function", "Function",
        { MakeFlowPin(""), MakePin("FunctionId", PinDataType::String) },
        { MakeFlowPin("") },
        "40A0FF");

    reg("Function.CallLibrary", "Call Library Function", "Function",
        { MakeFlowPin(""), MakePin("LibraryPath", PinDataType::String), MakePin("FunctionId", PinDataType::String) },
        { MakeFlowPin("") },
        "40A0FF");
}


} // namespace Runtime
} // namespace NodeEditor