// Runtime/nodedefs/BuiltinNodeDefs_GameExtra.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_GameExtra() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_GameExtra(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    const char* RND_COLOR = "4A7A3A"; // 草绿
    const char* EAS_COLOR = "7A4A8A"; // 紫
    const char* TMR_COLOR = "2A6A7A"; // 青
    const char* ENT_COLOR = "8A6A2A"; // 棕
    const char* INV_COLOR = "5A3A8A"; // 深紫

    // ── Random ──────────────────────────────────────────────────────────────
    reg("Random.SetSeed", "Random Set Seed", "Game/Random",
        { MakeFlowPin(""), MakePin("Seed", PinDataType::Integer) },
        { MakeFlowPin("exec") }, RND_COLOR);

    reg("Random.Float", "Random Float", "Game/Random",
        { MakePin("Min", PinDataType::Float), MakePin("Max", PinDataType::Float) },
        { MakePin("Value", PinDataType::Float) }, RND_COLOR, "Simple");

    reg("Random.Int", "Random Int", "Game/Random",
        { MakePin("Min", PinDataType::Integer), MakePin("Max", PinDataType::Integer) },
        { MakePin("Value", PinDataType::Integer) }, RND_COLOR, "Simple");

    reg("Random.Bool", "Random Bool", "Game/Random",
        { MakePin("Probability", PinDataType::Float) },
        { MakePin("Value", PinDataType::Boolean) }, RND_COLOR, "Simple");

    reg("Random.WeightedChoice", "Weighted Choice", "Game/Random",
        { MakePin("Items",   PinDataType::Array),
          MakePin("Weights", PinDataType::Array) },
        { MakePin("ChosenItem",  PinDataType::String),
          MakePin("ChosenIndex", PinDataType::Integer) }, RND_COLOR, "Simple");

    reg("Random.Shuffle", "Random Shuffle", "Game/Random",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Result", PinDataType::Array) }, RND_COLOR, "Simple");

    reg("Random.Vec2", "Random Vec2", "Game/Random",
        { MakePinEnum("Mode", "Rect,Circle,CircleSurface"),
          MakePin("MinX", PinDataType::Float), MakePin("MinY", PinDataType::Float),
          MakePin("MaxX", PinDataType::Float), MakePin("MaxY", PinDataType::Float) },
        { MakePin("Vec2", PinDataType::String),
          MakePin("X",    PinDataType::Float),
          MakePin("Y",    PinDataType::Float) }, RND_COLOR, "Simple");

    reg("Random.PickFromArray", "Pick From Array", "Game/Random",
        { MakePin("Array",           PinDataType::Array),
          MakePin("Count",           PinDataType::Integer),
          MakePin("WithReplacement", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Array) }, RND_COLOR, "Simple");

    // ── Easing ──────────────────────────────────────────────────────────────
    static const char* EASE_ENUM =
        "Linear,"
        "InQuad,OutQuad,InOutQuad,"
        "InCubic,OutCubic,InOutCubic,"
        "InQuart,OutQuart,InOutQuart,"
        "InQuint,OutQuint,InOutQuint,"
        "InSine,OutSine,InOutSine,"
        "InExpo,OutExpo,InOutExpo,"
        "InCirc,OutCirc,InOutCirc,"
        "InBack,OutBack,InOutBack,"
        "InElastic,OutElastic,InOutElastic,"
        "InBounce,OutBounce,InOutBounce";

    reg("Easing.Apply", "Easing Apply", "Game/Easing",
        { MakePinEnum("Curve", EASE_ENUM), MakePin("T", PinDataType::Float) },
        { MakePin("EasedT", PinDataType::Float) }, EAS_COLOR, "Simple");

    reg("Easing.Lerp", "Easing Lerp", "Game/Easing",
        { MakePinEnum("Curve", EASE_ENUM),
          MakePin("From", PinDataType::Float),
          MakePin("To",   PinDataType::Float),
          MakePin("T",    PinDataType::Float) },
        { MakePin("Result",  PinDataType::Float),
          MakePin("EasedT",  PinDataType::Float) }, EAS_COLOR, "Simple");

    // ── GameTimer ────────────────────────────────────────────────────────────
    reg("GameTimer.Tick", "Game Timer Tick", "Game/Timer",
        { MakeFlowPin(""),
          MakePin("Key",       PinDataType::String),
          MakePin("DeltaTime", PinDataType::Float),
          MakePin("MaxTime",   PinDataType::Float) },
        { MakeFlowPin("exec"),
          MakePin("ElapsedTime", PinDataType::Float),
          MakePin("FrameCount",  PinDataType::Integer),
          MakePin("Normalized",  PinDataType::Float) }, TMR_COLOR);

    reg("GameTimer.Reset", "Game Timer Reset", "Game/Timer",
        { MakeFlowPin(""), MakePin("Key", PinDataType::String) },
        { MakeFlowPin("exec") }, TMR_COLOR);

    reg("GameTimer.Get", "Game Timer Get", "Game/Timer",
        { MakePin("Key", PinDataType::String) },
        { MakePin("ElapsedTime", PinDataType::Float),
          MakePin("FrameCount",  PinDataType::Integer) }, TMR_COLOR, "Simple");

    // ── Entity & Tag ─────────────────────────────────────────────────────────
    reg("Entity.Create", "Entity Create", "Game/Entity",
        { MakeFlowPin(""), MakePin("Prefix", PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("EntityId", PinDataType::String) }, ENT_COLOR);

    reg("Entity.Destroy", "Entity Destroy", "Game/Entity",
        { MakeFlowPin(""), MakePin("EntityId", PinDataType::String) },
        { MakeFlowPin("exec") }, ENT_COLOR);

    reg("Entity.IsAlive", "Entity Is Alive", "Game/Entity",
        { MakePin("EntityId", PinDataType::String) },
        { MakePin("Alive", PinDataType::Boolean) }, ENT_COLOR, "Simple");

    reg("Tag.Add", "Tag Add", "Game/Entity",
        { MakeFlowPin(""),
          MakePin("EntityId", PinDataType::String),
          MakePin("Tag",      PinDataType::String) },
        { MakeFlowPin("exec") }, ENT_COLOR);

    reg("Tag.Remove", "Tag Remove", "Game/Entity",
        { MakeFlowPin(""),
          MakePin("EntityId", PinDataType::String),
          MakePin("Tag",      PinDataType::String) },
        { MakeFlowPin("exec") }, ENT_COLOR);

    reg("Tag.Has", "Tag Has", "Game/Entity",
        { MakePin("EntityId", PinDataType::String),
          MakePin("Tag",      PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) }, ENT_COLOR, "Simple");

    reg("Tag.GetAll", "Tag Get All", "Game/Entity",
        { MakePin("EntityId", PinDataType::String) },
        { MakePin("Tags",  PinDataType::Array),
          MakePin("Count", PinDataType::Integer) }, ENT_COLOR, "Simple");

    // ── Inventory ────────────────────────────────────────────────────────────
    reg("Inventory.Add", "Inventory Add", "Game/Inventory",
        { MakeFlowPin(""),
          MakePin("SlotId",   PinDataType::String),
          MakePin("ItemId",   PinDataType::String),
          MakePin("Quantity", PinDataType::Integer),
          MakePin("MaxStack", PinDataType::Integer) },
        { MakeFlowPin("exec"),
          MakePin("NewQuantity", PinDataType::Integer),
          MakePin("Overflow",    PinDataType::Integer) }, INV_COLOR);

    reg("Inventory.Remove", "Inventory Remove", "Game/Inventory",
        { MakeFlowPin(""),
          MakePin("SlotId",   PinDataType::String),
          MakePin("ItemId",   PinDataType::String),
          MakePin("Quantity", PinDataType::Integer) },
        { MakeFlowPin("exec"),
          MakePin("NewQuantity", PinDataType::Integer),
          MakePin("Removed",     PinDataType::Integer) }, INV_COLOR);

    reg("Inventory.GetQuantity", "Inventory Get Qty", "Game/Inventory",
        { MakePin("SlotId", PinDataType::String),
          MakePin("ItemId", PinDataType::String) },
        { MakePin("Quantity", PinDataType::Integer),
          MakePin("HasItem",  PinDataType::Boolean) }, INV_COLOR, "Simple");

    reg("Inventory.GetAll", "Inventory Get All", "Game/Inventory",
        { MakePin("SlotId", PinDataType::String) },
        { MakePin("Items",      PinDataType::Array),
          MakePin("Quantities", PinDataType::Array),
          MakePin("Count",      PinDataType::Integer) }, INV_COLOR, "Simple");

    reg("Inventory.Clear", "Inventory Clear", "Game/Inventory",
        { MakeFlowPin(""), MakePin("SlotId", PinDataType::String) },
        { MakeFlowPin("exec") }, INV_COLOR);
}


} // namespace Runtime
} // namespace NodeEditor