// Runtime/nodedefs/BuiltinNodeDefs_Houdini.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Houdini() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Houdini(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("HoudiniTransform", "Transform", "Houdini",
        { MakeFlowPin("") },
        { MakeFlowPin("") },
        "", "Houdini");

    reg("HoudiniGroup", "Group", "Houdini",
        { MakeFlowPin(""), MakeFlowPin("") },
        { MakeFlowPin("") },
        "", "Houdini");
}


} // namespace Runtime
} // namespace NodeEditor