// Runtime/nodedefs/BuiltinNodeDefs_Debug.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Debug() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Debug(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("PrintString", "Print String", "Debug",
        { MakeFlowPin(""), MakePin("In String", PinDataType::String) },
        { MakeFlowPin("") },
        "3D8B45");
    

    reg("Log", "Log", "Debug",
        { MakeFlowPin(""), MakePin("Message", PinDataType::String) },
        { MakeFlowPin("") },
        "3D8B45");
    

    // Assert — 断言条件为真，否则输出错误
    reg("Assert", "Assert", "Debug",
        { MakeFlowPin(""), MakePin("Condition", PinDataType::Boolean), MakePin("Message", PinDataType::String) },
        { MakeFlowPin("") },
        "FF4040");

    // InspectValue — 透传任意值，同时 Print 该值
    reg("InspectValue", "Inspect Value", "Debug",
        { MakePin("Value", PinDataType::Any) },
        { MakePin("Value", PinDataType::Any) },
        "", "Simple");

    // BreakOnCondition — Condition 为 true 时暂停 runner
    reg("BreakOnCondition", "Break On Condition", "Debug",
        { MakeFlowPin(""), MakePin("Condition", PinDataType::Boolean) },
        { MakeFlowPin("") },
        "FF8040");

    // FormatLog — 带格式化的日志输出
    reg("FormatLog", "Format Log", "Debug",
        { MakeFlowPin(""), MakePin("Format", PinDataType::String),
          MakePin("Arg 0", PinDataType::Any), MakePin("Arg 1", PinDataType::Any) },
        { MakeFlowPin("") });
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("FormatLog"));
        if (d) d->customProperties["dynamicInputs"] = "Any";
    }
}


} // namespace Runtime
} // namespace NodeEditor