// Runtime/nodedefs/BuiltinNodeDefs_Network.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Network() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Network(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    // HTTP.Request
    reg("HTTP.Request", "HTTP Request", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",            PinDataType::String),
            MakePinEnum("Method",     "GET,POST,PUT,DELETE,PATCH,HEAD", "GET"),
            MakePin("Body",           PinDataType::String),
            MakePin("Headers",        PinDataType::String),  // JSON 格式 {"Key":"Value"}
            MakePin("TimeoutSeconds", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ResponseBody", PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");  // 蓝色

    // JSON.GetPath — 支持 choices[0].message.content 路径
    reg("JSON.GetPath", "JSON Get Path", "Network",
        {
            MakePin("JSON", PinDataType::String),
            MakePin("Path", PinDataType::String),   // e.g. "choices[0].message.content"
        },
        {
            MakePin("Value", PinDataType::String),
            MakePin("Found", PinDataType::Boolean),
        },
        "2E86AB");

    // HTTP.Download — GET 请求下载内容，跨平台（native + WebGL）
    // 输入：URL, Headers(可选JSON), TimeoutSeconds
    // 输出：→ onSuccess, → onError
    //       Data(String 原始字节), Size(Integer), StatusCode(Integer), ErrorMessage(String)
    // 注意：WebGL 下 Data 为内存中字节串，如需持久化请配合 File.Write 节点使用
    reg("HTTP.Download", "HTTP Download", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",            PinDataType::String),
            MakePin("Headers",        PinDataType::String),  // JSON 格式 {"Key":"Value"}（可选）
            MakePin("TimeoutSeconds", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Data",         PinDataType::String),   // 原始响应字节（二进制安全）
            MakePin("Size",         PinDataType::Integer),  // 字节数
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");  // 蓝色，同 HTTP.Request

    // HTTP.Get — 快捷 GET 节点（HTTP.Request 的精简版）
    reg("HTTP.Get", "HTTP Get", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",            PinDataType::String),
            MakePin("Headers",        PinDataType::String),  // JSON 格式（可选）
            MakePin("TimeoutSeconds", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ResponseBody", PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");

    // HTTP.Post — 快捷 POST 节点
    reg("HTTP.Post", "HTTP Post", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",            PinDataType::String),
            MakePin("Body",           PinDataType::String),
            MakePin("Headers",        PinDataType::String),  // JSON 格式（可选）
            MakePin("TimeoutSeconds", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ResponseBody", PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");

    // Web.Search — DuckDuckGo Lite 网页搜索（无需 API Key，跨平台）
    // 输入：Query(String), MaxResults(Integer，默认5)
    // 输出：→ onSuccess, → onError
    //       Results(String，JSON数组 [{title,url,snippet},...])
    //       ResultText(String，纯文本拼接，适合直接喂给 LLM)
    reg("Web.Search", "Web Search", "Network",
        {
            MakeFlowPin(""),
            MakePin("Query",      PinDataType::String),
            MakePin("MaxResults", PinDataType::Integer),  // 默认 5
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Results",    PinDataType::String),   // JSON 数组
            MakePin("ResultText", PinDataType::String),   // 纯文本，适合喂 LLM
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");

    // Code.Run — 执行子进程命令（native only，WebGL 走 onError）
    // 输入：Command(String), WorkDir(String), TimeoutSeconds(Integer)
    // 输出：→ onSuccess, → onError
    //       Stdout(String), Stderr(String), ExitCode(Integer)
    reg("Code.Run", "Code Run", "Network",
        {
            MakeFlowPin(""),
            MakePin("Command",        PinDataType::String),
            MakePin("WorkDir",        PinDataType::String),   // 工作目录（可选）
            MakePin("TimeoutSeconds", PinDataType::Integer),  // 默认 30
        },
        {
            MakeFlowPin("onSuccess"),  // ExitCode == 0
            MakeFlowPin("onError"),    // 启动失败或超时
            MakePin("Stdout",    PinDataType::String),
            MakePin("Stderr",    PinDataType::String),
            MakePin("ExitCode",  PinDataType::Integer),
        },
        "2E86AB");
}

// ============================================================================
// AI / LLM 节点定义
// 颜色：6A0572（紫色，区别于网络蓝）
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor