// Runtime/nodedefs/BuiltinNodeDefs_AI_Tool.cpp
// Generated by tools/split_nodedefs_ai.ps1 from BuiltinNodeDefs_AI.cpp
//
// Contains the RegisterNodeDefs_AI_Tool() function, registering AI/Tool
// node definitions. Called by RegisterNodeDefs_AI().
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

void RegisterNodeDefs_AI_Tool(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };
    // ── Tool.CallByName ─────────────────────────────────────────────────────
    // 按工具名动态路由到同名 FuncLib 函数，无上限（不受 Tool.Match 8 个限制）
    reg("Tool.CallByName", "Tool Call By Name", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolName",   PinDataType::String),    // 工具名（与 FuncLib 函数名一致）
            MakePin("Arguments",  PinDataType::String),    // 参数 JSON 对象字符串
            MakePin("ToolCallId", PinDataType::String),    // tool_call id（透传）
        },
        {
            MakeFlowPin("onSuccess"),                      // 找到并调用成功
            MakeFlowPin("onNotFound"),                     // 找不到同名函数
            MakePin("Result",     PinDataType::String),    // 函数的 Result 变量返回值
            MakePin("ToolCallId", PinDataType::String),    // 透传的 tool_call id
        },
        "6A0572");

    // ── Tool.ForEach ────────────────────────────────────────────────────────
    reg("Tool.ForEach", "Tool For Each", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolCallsJSON", PinDataType::String),
        },
        {
            MakeFlowPin("onTool"),     // 每个 tool call 触发一次
            MakeFlowPin("onDone"),     // 全部遍历完毕
            MakePin("ToolName",   PinDataType::String),
            MakePin("Arguments",  PinDataType::String),
            MakePin("ToolCallId", PinDataType::String),
            MakePin("Index",      PinDataType::Integer),
        },
        "6A0572");

    // ── Tool.ForEachParallel ─────────────────────────────────────────────────
    // 并发发起所有 tool_calls 的 HTTP 请求，全部完成后激活 onDone
    // 适用于多个工具均为 HTTP 服务的场景（比串行快 N 倍）
    // 若工具是 FuncLib 函数，请使用 Tool.ForEach + Tool.CallByName（串行）
    reg("Tool.ForEachParallel", "Tool For Each (Parallel)", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("ToolServerURL", PinDataType::String),  // 工具 HTTP 服务地址（可选）
        },
        {
            MakeFlowPin("onDone"),                          // 全部并发完成
            MakeFlowPin("onError"),                         // HTTP client 未注册
            MakePin("ResultsJSON",   PinDataType::String),  // [{id,name,result},...]
        },
        "6A0572");

    // ── Tool.Match ──────────────────────────────────────────────────────────
    reg("Tool.Match", "Tool Match", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolName", PinDataType::String),
            MakePin("Case0",    PinDataType::String),
            MakePin("Case1",    PinDataType::String),
            MakePin("Case2",    PinDataType::String),
            MakePin("Case3",    PinDataType::String),
            MakePin("Case4",    PinDataType::String),
            MakePin("Case5",    PinDataType::String),
            MakePin("Case6",    PinDataType::String),
            MakePin("Case7",    PinDataType::String),
        },
        {
            MakeFlowPin("Match0"),
            MakeFlowPin("Match1"),
            MakeFlowPin("Match2"),
            MakeFlowPin("Match3"),
            MakeFlowPin("Match4"),
            MakeFlowPin("Match5"),
            MakeFlowPin("Match6"),
            MakeFlowPin("Match7"),
            MakeFlowPin("Default"),
            MakePin("MatchedIndex", PinDataType::Integer),
        },
        "6A0572");

    // Tool.Define — 可视化定义一个 LLM 工具
    reg("Tool.Define", "Define Tool", "AI/Tools",
        {
            MakePin("Name",        PinDataType::String),
            MakePin("Description", PinDataType::String),
            MakePin("ParamNames",  PinDataType::Array),
            MakePin("ParamDescs",  PinDataType::Array),
            MakePin("Required",    PinDataType::Array),
        },
        {
            MakePin("ToolJSON", PinDataType::String),
        },
        "5A7A6A");

    // MCP.Call — 调用 MCP Server 工具（支持标准 JSON-RPC 2.0 协议）
    // Protocol: "jsonrpc2"（默认，标准 MCP）或 "simple"（{tool_name, arguments}）
    // JSON-RPC 2.0 请求：{"jsonrpc":"2.0","id":N,"method":"tools/call","params":{"name":ToolName,"arguments":{...}}}
    // JSON-RPC 2.0 响应解析：result.content[0].text → Result
    reg("MCP.Call", "MCP Call", "AI/MCP",
        {
            MakeFlowPin(""),
            MakePin("ServerURL",  PinDataType::String),   // e.g. http://localhost:7788
            MakePin("ToolName",   PinDataType::String),
            MakePin("Arguments",  PinDataType::String),   // JSON object string
            MakePin("Protocol",   PinDataType::String),   // "jsonrpc2"(default) | "simple"
            MakePin("TimeoutSec", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Result",       PinDataType::String), // 解析后的文本结果
            MakePin("RawResult",    PinDataType::String), // 完整响应 JSON
            MakePin("ErrorMessage", PinDataType::String),
        },
        "5A6A7A");

    // ── HTTP.Retry ───────────────────────────────────────────────────────────
    // 带自动重试的 HTTP GET/POST，网络抖动时自动重试 MaxRetries 次
    // RetryOnStatus: 逗号分隔的 HTTP 状态码（如 "429,503"），匹配时重试
    reg("HTTP.Retry", "HTTP Retry", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",           PinDataType::String),
            MakePinEnum("Method",    "GET,POST,PUT,DELETE,PATCH,HEAD", "GET"),
            MakePin("Body",          PinDataType::String),
            MakePin("Headers",       PinDataType::String),
            MakePin("MaxRetries",    PinDataType::Integer),  // default 3
            MakePin("RetryDelaySec", PinDataType::Float),    // default 1.0
            MakePin("RetryOnStatus", PinDataType::String),   // "429,503" 等
            MakePin("TimeoutSeconds",PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ResponseBody", PinDataType::String),
            MakePin("RetryCount",   PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB"); // 蓝色，同 HTTP.Get

    // Tool.Register — 动态注册工具
    reg("Tool.Register", "Tool Register", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("Name",        PinDataType::String),
            MakePin("FilePath",    PinDataType::String),
            MakePin("Description", PinDataType::String),
        },
        {
            MakeFlowPin("exec"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "F5A623");

}

} // namespace Runtime
} // namespace NodeEditor