// Runtime/nodedefs/BuiltinNodeDefs_AI.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_AI() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_AI(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    // JSON.Build — 从 Keys/Values 数组构建 JSON 对象字符串
    reg("JSON.Build", "JSON Build", "AI/JSON",
        {
            MakePin("Keys",   PinDataType::Array),   // Array<String>
            MakePin("Values", PinDataType::Array),   // Array<Any>
        },
        {
            MakePin("JSON", PinDataType::String),
        },
        "6A0572", "Simple");

    // JSON.SetPath — 向 JSON 对象设置嵌套路径
    reg("JSON.SetPath", "JSON Set Path", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",  PinDataType::String),
            MakePin("Path",  PinDataType::String),   // e.g. "choices[0].message.content"
            MakePin("Value", PinDataType::Any),
        },
        {
            MakeFlowPin(""),
            MakePin("JSON",  PinDataType::String),
        },
        "6A0572");

    // JSON.ArrayPush — 向 JSON 数组追加元素
    reg("JSON.ArrayPush", "JSON Array Push", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",    PinDataType::String),
            MakePin("Element", PinDataType::Any),
        },
        {
            MakeFlowPin(""),
            MakePin("JSON",   PinDataType::String),
            MakePin("Length", PinDataType::Integer),
        },
        "6A0572");

    // JSON.MakeMessage — 构造 {"role":"...","content":"..."} 消息对象
    reg("JSON.MakeMessage", "Make Message", "AI/JSON",
        {
            MakePin("Role",       PinDataType::String),   // "user" | "assistant" | "system" | "tool"
            MakePin("Content",    PinDataType::String),
            MakePin("ToolCallId", PinDataType::String),   // optional; for role="tool" responses
        },
        {
            MakePin("Message", PinDataType::String),
        },
        "6A0572", "Simple");

    // String.Template — {{key}} 占位符替换
    reg("String.Template", "String Template", "AI/String",
        {
            MakePin("Template", PinDataType::String),
            MakePin("Keys",     PinDataType::Array),   // Array<String>
            MakePin("Values",   PinDataType::Array),   // Array<String>
        },
        {
            MakePin("Result", PinDataType::String),
        },
        "6A0572", "Simple");

    // LLM.Chat — OpenAI 兼容 Chat 调用（支持 tool_calls）
    reg("LLM.Chat", "LLM Chat", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",      PinDataType::String),   // 默认 https://api.openai.com/v1
            MakePin("ApiKey",       PinDataType::String),
            MakePin("Model",        PinDataType::String),   // 默认 gpt-4o
            MakePin("Messages",     PinDataType::String),   // JSON 数组字符串
            MakePin("SystemPrompt", PinDataType::String),   // 可选，自动插到首条
            MakePin("MaxTokens",    PinDataType::Integer),  // 默认 1024
            MakePin("Temperature",  PinDataType::Float),    // 默认 0.7
            MakePin("Tools",        PinDataType::String),   // function schema JSON 数组，可选
        },
        {
            MakeFlowPin("onReply"),                          // finish_reason=stop
            MakeFlowPin("onToolCall"),                       // finish_reason=tool_calls
            MakeFlowPin("onError"),
            MakePin("Reply",         PinDataType::String),   // 文本回复
            MakePin("ToolCallsJSON", PinDataType::String),   // tool_calls 数组 JSON
            MakePin("FinishReason",  PinDataType::String),   // "stop"|"tool_calls"|"length"|...
            MakePin("FullResponse",  PinDataType::String),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.Auto ────────────────────────────────────────────────────────────
    // 从配置文件读取多个 provider，按 priority 依次 fallback，第一个成功的返回结果
    // Provider 引脚：空/"auto" = 自动 fallback；填 provider name = 直接使用指定 provider
    reg("LLM.Auto", "LLM Auto", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("ConfigFile",   PinDataType::String),   // JSON 配置文件路径
            MakePin("Provider",     PinDataType::String),   // 空/"auto"=自动, 或指定 provider name
            MakePin("Messages",     PinDataType::String),   // JSON 数组字符串
            MakePin("SystemPrompt", PinDataType::String),   // 可选
            MakePin("MaxTokens",    PinDataType::Integer),  // 默认 1024
            MakePin("Temperature",  PinDataType::Float),    // 默认 0.7
            MakePin("Tools",        PinDataType::String),   // function schema，可选
        },
        {
            MakeFlowPin("onReply"),
            MakeFlowPin("onToolCall"),
            MakeFlowPin("onError"),
            MakePin("Reply",         PinDataType::String),
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("FinishReason",  PinDataType::String),
            MakePin("UsedProvider",  PinDataType::String),  // 实际使用的 provider 名
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.AutoStream ──────────────────────────────────────────────────────
    // 流式版 LLM.Auto：多 provider fallback + SSE 逐 token 推送
    // Provider 引脚：空/"auto"=自动 fallback；填 provider name=直接使用指定 provider
    reg("LLM.AutoStream", "LLM Auto Stream", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("ConfigFile",   PinDataType::String),
            MakePin("Provider",     PinDataType::String),   // 空/"auto"=自动, 或指定 provider name
            MakePin("Messages",     PinDataType::String),
            MakePin("SystemPrompt", PinDataType::String),
            MakePin("MaxTokens",    PinDataType::Integer),
            MakePin("Temperature",  PinDataType::Float),
            MakePin("Tools",        PinDataType::String),
        },
        {
            MakeFlowPin("onChunk"),                          // 每个 token 激活一次
            MakeFlowPin("onToolCall"),
            MakeFlowPin("onDone"),                           // 全部 chunk 完毕
            MakeFlowPin("onError"),
            MakePin("Token",         PinDataType::String),   // 当前 token（onChunk 时）
            MakePin("FullText",      PinDataType::String),   // 完整文本（onDone 时）
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("UsedProvider",  PinDataType::String),   // 实际使用的 provider 名
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.StreamChat ──────────────────────────────────────────────────────
    // 流式 OpenAI 兼容 Chat（SSE 批量聚合）
    reg("LLM.StreamChat", "LLM Stream Chat", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",      PinDataType::String),
            MakePin("ApiKey",       PinDataType::String),
            MakePin("Model",        PinDataType::String),
            MakePin("Messages",     PinDataType::String),
            MakePin("SystemPrompt", PinDataType::String),
            MakePin("MaxTokens",    PinDataType::Integer),
            MakePin("Temperature",  PinDataType::Float),
            MakePin("Tools",        PinDataType::String),
        },
        {
            MakeFlowPin("onChunk"),                          // 每个 token 激活一次（文本流）
            MakeFlowPin("onToolCall"),                       // finish_reason=tool_calls 时触发
            MakeFlowPin("onDone"),                           // 全部 chunk 完毕（文本流结束）
            MakeFlowPin("onError"),
            MakePin("Token",         PinDataType::String),   // 当前 token（onChunk 时）
            MakePin("FullText",      PinDataType::String),   // 完整文本（onDone 时）
            MakePin("ToolCallsJSON", PinDataType::String),   // tool_calls JSON（onToolCall 时）
            MakePin("FinishReason",  PinDataType::String),   // "stop"|"tool_calls"|"length"|...
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── JSON.ParseToolCall ──────────────────────────────────────────────────
    // 从 tool_calls[Index] 中提取 name 和 arguments
    //   in:  ToolCallsJSON(String) — LLM.Chat 输出的 ToolCallsJSON
    //        Index(Integer)        — 要取第几个（默认 0）
    //   out: Name(String)          — function name
    //        ArgumentsJSON(String) — arguments 对象 JSON 字符串
    //        ID(String)            — tool_call id（回传给 LLM 时需要）
    reg("JSON.ParseToolCall", "Parse Tool Call", "AI/JSON",
        {
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("Index",         PinDataType::Integer),
        },
        {
            MakePin("Name",          PinDataType::String),
            MakePin("ArgumentsJSON", PinDataType::String),
            MakePin("ID",            PinDataType::String),
        },
        "2E86AB");

    // ── JSON.MakeToolResult ─────────────────────────────────────────────────
    // 构造 tool role 消息，把工具结果反馈给 LLM
    //   in:  ToolCallID(String), Content(String)
    //   out: JSON(String) — {"role":"tool","tool_call_id":"...","content":"..."}
    reg("JSON.MakeToolResult", "Make Tool Result", "AI/JSON",
        {
            MakePin("ToolCallID", PinDataType::String),
            MakePin("Content",    PinDataType::String),
        },
        {
            MakePin("JSON", PinDataType::String),
        },
        "2E86AB");

    // ── JSON.ToolCallCount ──────────────────────────────────────────────────
    // 返回 tool_calls 数组长度（用于并行工具调用循环）
    reg("JSON.ToolCallCount", "Tool Call Count", "AI/JSON",
        { MakePin("ToolCallsJSON", PinDataType::String), },
        { MakePin("Count",         PinDataType::Integer), },
        "2E86AB");

    // 从文件加载对话历史 JSON 数组
    // WebGL：直接 onNew + 空数组
    reg("Memory.LoadHistory", "Memory Load History", "AI/Memory",
        {
            MakeFlowPin("In"),
            MakePin("Path",        PinDataType::String),   // 历史文件路径
            MakePin("MaxMessages", PinDataType::Integer),  // 0=不限，截断最旧的
        },
        {
            MakeFlowPin("onSuccess"),                      // 文件存在且解析成功
            MakeFlowPin("onNew"),                          // 文件不存在（首次启动）
            MakeFlowPin("onError"),
            MakePin("Messages",     PinDataType::String),  // JSON 数组字符串
            MakePin("Count",        PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // ── Memory.SaveHistory ──────────────────────────────────────────────────
    // 把 messages 数组写回文件（含可选截断）
    // WebGL：no-op，直接 onSuccess
    reg("Memory.SaveHistory", "Memory Save History", "AI/Memory",
        {
            MakeFlowPin("In"),
            MakePin("Path",        PinDataType::String),   // 历史文件路径
            MakePin("Messages",    PinDataType::String),   // JSON 数组字符串
            MakePin("MaxMessages", PinDataType::Integer),  // 0=不限，写入前截断
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // ── Tool.CallByName ─────────────────────────────────────────────────────
    // 按工具名动态路由到同名 FuncLib 函数，无上限（不受 Tool.Match 8 个限制）
    reg("Tool.CallByName", "Tool Call By Name", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolName",   PinDataType::String),    // 工具名（与 FuncLib 函数名一致）
            MakePin("Arguments",  PinDataType::String),    // 参数 JSON 对象字符串
            MakePin("ToolCallId", PinDataType::String),    // tool_call id（透传）
        },
        {
            MakeFlowPin("onSuccess"),                      // 找到并调用成功
            MakeFlowPin("onNotFound"),                     // 找不到同名函数
            MakePin("Result",     PinDataType::String),    // 函数的 Result 变量返回值
            MakePin("ToolCallId", PinDataType::String),    // 透传的 tool_call id
        },
        "6A0572");

    // ── Tool.ForEach ────────────────────────────────────────────────────────
    reg("Tool.ForEach", "Tool For Each", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolCallsJSON", PinDataType::String),
        },
        {
            MakeFlowPin("onTool"),     // 每个 tool call 触发一次
            MakeFlowPin("onDone"),     // 全部遍历完毕
            MakePin("ToolName",   PinDataType::String),
            MakePin("Arguments",  PinDataType::String),
            MakePin("ToolCallId", PinDataType::String),
            MakePin("Index",      PinDataType::Integer),
        },
        "6A0572");

    // ── Tool.ForEachParallel ─────────────────────────────────────────────────
    // 并发发起所有 tool_calls 的 HTTP 请求，全部完成后激活 onDone
    // 适用于多个工具均为 HTTP 服务的场景（比串行快 N 倍）
    // 若工具是 FuncLib 函数，请使用 Tool.ForEach + Tool.CallByName（串行）
    reg("Tool.ForEachParallel", "Tool For Each (Parallel)", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("ToolServerURL", PinDataType::String),  // 工具 HTTP 服务地址（可选）
        },
        {
            MakeFlowPin("onDone"),                          // 全部并发完成
            MakeFlowPin("onError"),                         // HTTP client 未注册
            MakePin("ResultsJSON",   PinDataType::String),  // [{id,name,result},...]
        },
        "6A0572");

    // ── Tool.Match ──────────────────────────────────────────────────────────
    reg("Tool.Match", "Tool Match", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("ToolName", PinDataType::String),
            MakePin("Case0",    PinDataType::String),
            MakePin("Case1",    PinDataType::String),
            MakePin("Case2",    PinDataType::String),
            MakePin("Case3",    PinDataType::String),
            MakePin("Case4",    PinDataType::String),
            MakePin("Case5",    PinDataType::String),
            MakePin("Case6",    PinDataType::String),
            MakePin("Case7",    PinDataType::String),
        },
        {
            MakeFlowPin("Match0"),
            MakeFlowPin("Match1"),
            MakeFlowPin("Match2"),
            MakeFlowPin("Match3"),
            MakeFlowPin("Match4"),
            MakeFlowPin("Match5"),
            MakeFlowPin("Match6"),
            MakeFlowPin("Match7"),
            MakeFlowPin("Default"),
            MakePin("MatchedIndex", PinDataType::Integer),
        },
        "6A0572");

    // ── JSON.Extract ────────────────────────────────────────────────────────
    reg("JSON.Extract", "JSON Extract", "AI/JSON",
        {
            MakePin("Text", PinDataType::String),
        },
        {
            MakePin("JSON",  PinDataType::String),
            MakePin("Found", PinDataType::Boolean),
        },
        "6A0572", "Simple");

    // ── JSON.Validate ───────────────────────────────────────────────────────
    reg("JSON.Validate", "JSON Validate", "AI/JSON",
        {
            MakeFlowPin(""),
            MakePin("JSON",         PinDataType::String),
            MakePin("RequiredKeys", PinDataType::String),
        },
        {
            MakeFlowPin("onValid"),
            MakeFlowPin("onInvalid"),
            MakePin("IsValid",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // UserInput.Wait — 等待用户在编辑器输入框输入文本
    reg("UserInput.Wait", "Wait For Input", "AI",
        {
            MakeFlowPin(""),
            MakePin("Prompt",       PinDataType::String),
            MakePin("DefaultValue", PinDataType::String),
        },
        {
            MakeFlowPin(""),
            MakePin("Input", PinDataType::String),
        },
        "6A5F9A");

    // Tool.Define — 可视化定义一个 LLM 工具
    reg("Tool.Define", "Define Tool", "AI/Tools",
        {
            MakePin("Name",        PinDataType::String),
            MakePin("Description", PinDataType::String),
            MakePin("ParamNames",  PinDataType::Array),
            MakePin("ParamDescs",  PinDataType::Array),
            MakePin("Required",    PinDataType::Array),
        },
        {
            MakePin("ToolJSON", PinDataType::String),
        },
        "5A7A6A");

    // MCP.Call — 调用 MCP Server 工具（支持标准 JSON-RPC 2.0 协议）
    // Protocol: "jsonrpc2"（默认，标准 MCP）或 "simple"（{tool_name, arguments}）
    // JSON-RPC 2.0 请求：{"jsonrpc":"2.0","id":N,"method":"tools/call","params":{"name":ToolName,"arguments":{...}}}
    // JSON-RPC 2.0 响应解析：result.content[0].text → Result
    reg("MCP.Call", "MCP Call", "AI/MCP",
        {
            MakeFlowPin(""),
            MakePin("ServerURL",  PinDataType::String),   // e.g. http://localhost:7788
            MakePin("ToolName",   PinDataType::String),
            MakePin("Arguments",  PinDataType::String),   // JSON object string
            MakePin("Protocol",   PinDataType::String),   // "jsonrpc2"(default) | "simple"
            MakePin("TimeoutSec", PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Result",       PinDataType::String), // 解析后的文本结果
            MakePin("RawResult",    PinDataType::String), // 完整响应 JSON
            MakePin("ErrorMessage", PinDataType::String),
        },
        "5A6A7A");

    // ── HTTP.Retry ───────────────────────────────────────────────────────────
    // 带自动重试的 HTTP GET/POST，网络抖动时自动重试 MaxRetries 次
    // RetryOnStatus: 逗号分隔的 HTTP 状态码（如 "429,503"），匹配时重试
    reg("HTTP.Retry", "HTTP Retry", "Network",
        {
            MakeFlowPin(""),
            MakePin("URL",           PinDataType::String),
            MakePinEnum("Method",    "GET,POST,PUT,DELETE,PATCH,HEAD", "GET"),
            MakePin("Body",          PinDataType::String),
            MakePin("Headers",       PinDataType::String),
            MakePin("MaxRetries",    PinDataType::Integer),  // default 3
            MakePin("RetryDelaySec", PinDataType::Float),    // default 1.0
            MakePin("RetryOnStatus", PinDataType::String),   // "429,503" 等
            MakePin("TimeoutSeconds",PinDataType::Integer),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("StatusCode",   PinDataType::Integer),
            MakePin("ResponseBody", PinDataType::String),
            MakePin("RetryCount",   PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB"); // 蓝色，同 HTTP.Get

    // ── Agent.Plan ───────────────────────────────────────────────────────────
    // 让 LLM 把复杂 Goal 分解为可执行步骤列表（JSON 数组），配合 Tool.CallByName
    reg("Agent.Plan", "Agent Plan", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",         PinDataType::String),
            MakePin("ApiKey",          PinDataType::String),
            MakePin("Model",           PinDataType::String),
            MakePin("Goal",            PinDataType::String),  // 目标描述
            MakePin("AvailableTools",  PinDataType::String),  // JSON 数组，每项含 name+description
            MakePin("MaxSteps",        PinDataType::Integer), // 最大步骤数，default 5
            MakePin("MaxTokens",       PinDataType::Integer),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("PlanJSON",      PinDataType::String),  // JSON 数组：[{"tool","arguments","reason"}]
            MakePin("StepCount",     PinDataType::Integer),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "5080C0"); // 蓝紫色

    // ── Agent.Reflect ────────────────────────────────────────────────────────
    // 让 LLM 评估上一步输出是否满足 Criteria，不满足时触发 onFail + Feedback
    reg("Agent.Reflect", "Agent Reflect", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",     PinDataType::String),
            MakePin("ApiKey",      PinDataType::String),
            MakePin("Model",       PinDataType::String),
            MakePin("Output",      PinDataType::String),  // 上一步的输出内容
            MakePin("Criteria",    PinDataType::String),  // 评判标准（自然语言）
            MakePin("MaxTokens",   PinDataType::Integer),
        },
        {
            MakeFlowPin("onPass"),
            MakeFlowPin("onFail"),
            MakeFlowPin("onError"),
            MakePin("Feedback",      PinDataType::String), // 不满足时的改进建议
            MakePin("Score",         PinDataType::String), // "pass" | "fail"
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "A05050"); // 红色

    // ── Context.Compress ─────────────────────────────────────────────────────
    // 压缩对话历史：保留最近 KeepRecent 轮，用 LLM 摘要更早的内容
    reg("Context.Compress", "Context Compress", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",    PinDataType::String),
            MakePin("ApiKey",     PinDataType::String),
            MakePin("Model",      PinDataType::String),
            MakePin("Messages",   PinDataType::String),
            MakePin("KeepRecent", PinDataType::Integer),
            MakePin("MaxTokens",  PinDataType::Integer),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("Compressed",   PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

    // LLM.StructuredOutput — 强制 JSON Schema 输出
    reg("LLM.StructuredOutput", "LLM Structured Output", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",     PinDataType::String),
            MakePin("ApiKey",      PinDataType::String),
            MakePin("Model",       PinDataType::String),
            MakePin("Messages",    PinDataType::String),
            MakePin("SystemPrompt",PinDataType::String),
            MakePin("SchemaName",  PinDataType::String),
            MakePin("Schema",      PinDataType::String),
            MakePin("MaxTokens",   PinDataType::Integer),
            MakePin("Temperature", PinDataType::Float),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Output",       PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // Schema.Validate — 验证 JSON 是否符合 Schema
    reg("Schema.Validate", "Schema Validate", "AI/JSON",
        {
            MakePin("JSON",   PinDataType::String),
            MakePin("Schema", PinDataType::String),
        },
        {
            MakeFlowPin("onPass"),
            MakeFlowPin("onFail"),
            MakePin("IsValid",      PinDataType::Boolean),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572", "Simple");

    // LLM.Route — LLM 驱动的路由分发
    reg("LLM.Route", "LLM Route", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL", PinDataType::String),
            MakePin("ApiKey",  PinDataType::String),
            MakePin("Model",   PinDataType::String),
            MakePin("Input",   PinDataType::String),
            MakePin("Routes",  PinDataType::String),   // JSON array of {label,description}
        },
        {
            MakeFlowPin("onRoute0"),
            MakeFlowPin("onRoute1"),
            MakeFlowPin("onRoute2"),
            MakeFlowPin("onRoute3"),
            MakeFlowPin("onRoute4"),
            MakeFlowPin("onRoute5"),
            MakeFlowPin("onRoute6"),
            MakeFlowPin("onRoute7"),
            MakeFlowPin("onError"),
            MakePin("SelectedRoute", PinDataType::Integer),
            MakePin("SelectedLabel", PinDataType::String),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // Intent.Classify — 意图识别
    reg("Intent.Classify", "Intent Classify", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL", PinDataType::String),
            MakePin("ApiKey",  PinDataType::String),
            MakePin("Model",   PinDataType::String),
            MakePin("Text",    PinDataType::String),
            MakePin("Intents", PinDataType::String),   // JSON array of string or {label,description}
        },
        {
            MakeFlowPin("onMatched"),
            MakeFlowPin("onUnknown"),
            MakeFlowPin("onError"),
            MakePin("Intent",       PinDataType::String),
            MakePin("Confidence",   PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

    // Agent.Spawn — 并行异步子蓝图
    reg("Agent.Spawn", "Agent Spawn", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("FilePath",  PinDataType::String),
            MakePin("Params",    PinDataType::String),  // JSON object
            MakePin("EventName", PinDataType::String),  // default: OnBeginPlay
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("SpawnId",      PinDataType::String),
            MakePin("Output",       PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

    // Agent.Join — 等待多个 Spawn 全部完成
    reg("Agent.Join", "Agent Join", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("Count",   PinDataType::Integer),
            MakePin("Timeout", PinDataType::Float),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onTimeout"),
            MakePin("CompletedCount", PinDataType::Integer),
        },
        "50A080");

    // Memory.Store — 进程级 KV 存储
    reg("Memory.Store", "Memory Store", "AI/Memory",
        {
            MakeFlowPin(""),
            MakePin("Key",   PinDataType::String),
            MakePin("Value", PinDataType::String),
            MakePin("TTL",   PinDataType::Float),   // 0=永久
        },
        { MakeFlowPin("exec") },
        "4A90D9");

    // Memory.Recall — 读取记忆
    reg("Memory.Recall", "Memory Recall", "AI/Memory",
        {
            MakePin("Key",    PinDataType::String),
            MakePin("Prefix", PinDataType::String),
        },
        {
            MakePin("Value",      PinDataType::String),
            MakePin("Found",      PinDataType::Boolean),
            MakePin("AllMatches", PinDataType::String),
        },
        "4A90D9", "Simple");

    // Memory.Clear — 清空记忆
    reg("Memory.Clear", "Memory Clear", "AI/Memory",
        {
            MakeFlowPin(""),
            MakePin("Prefix", PinDataType::String),
        },
        {
            MakeFlowPin("exec"),
            MakePin("RemovedCount", PinDataType::Integer),
        },
        "4A90D9");

    // Tool.Register — 动态注册工具
    reg("Tool.Register", "Tool Register", "AI/Tool",
        {
            MakeFlowPin(""),
            MakePin("Name",        PinDataType::String),
            MakePin("FilePath",    PinDataType::String),
            MakePin("Description", PinDataType::String),
        },
        {
            MakeFlowPin("exec"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "F5A623");

    // Trigger.Cron — 定时触发
    reg("Trigger.Cron", "Trigger Cron", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("IntervalSec", PinDataType::Float),
            MakePin("MaxCount",    PinDataType::Integer),
            MakePin("EventName",   PinDataType::String),
        },
        {
            MakeFlowPin("onTick"),
            MakeFlowPin("onDone"),
            MakePin("TickCount", PinDataType::Integer),
        },
        "E07B39");

    // Trigger.FileWatch — 文件变化触发
    reg("Trigger.FileWatch", "Trigger File Watch", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("FilePath",        PinDataType::String),
            MakePin("PollIntervalSec", PinDataType::Float),
        },
        {
            MakeFlowPin("onChanged"),
            MakeFlowPin("onError"),
            MakePin("FilePath", PinDataType::String),
        },
        "E07B39");

}

// ============================================================================
// Game — 行为树 BT.* 和状态机 FSM.*
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor