// Runtime/nodedefs/BuiltinNodeDefs_AI_LLM.cpp
// Generated by tools/split_nodedefs_ai.ps1 from BuiltinNodeDefs_AI.cpp
//
// Contains the RegisterNodeDefs_AI_LLM() function, registering AI/LLM
// node definitions. Called by RegisterNodeDefs_AI().
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

void RegisterNodeDefs_AI_LLM(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };
    // String.Template — {{key}} 占位符替换
    reg("String.Template", "String Template", "AI/String",
        {
            MakePin("Template", PinDataType::String),
            MakePin("Keys",     PinDataType::Array),   // Array<String>
            MakePin("Values",   PinDataType::Array),   // Array<String>
        },
        {
            MakePin("Result", PinDataType::String),
        },
        "6A0572", "Simple");

    // LLM.Chat — OpenAI 兼容 Chat 调用（支持 tool_calls）
    reg("LLM.Chat", "LLM Chat", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",      PinDataType::String),   // 默认 https://api.openai.com/v1
            MakePin("ApiKey",       PinDataType::String),
            MakePin("Model",        PinDataType::String),   // 默认 gpt-4o
            MakePin("Messages",     PinDataType::String),   // JSON 数组字符串
            MakePin("SystemPrompt", PinDataType::String),   // 可选，自动插到首条
            MakePin("MaxTokens",    PinDataType::Integer),  // 默认 1024
            MakePin("Temperature",  PinDataType::Float),    // 默认 0.7
            MakePin("Tools",        PinDataType::String),   // function schema JSON 数组，可选
        },
        {
            MakeFlowPin("onReply"),                          // finish_reason=stop
            MakeFlowPin("onToolCall"),                       // finish_reason=tool_calls
            MakeFlowPin("onError"),
            MakePin("Reply",         PinDataType::String),   // 文本回复
            MakePin("ToolCallsJSON", PinDataType::String),   // tool_calls 数组 JSON
            MakePin("FinishReason",  PinDataType::String),   // "stop"|"tool_calls"|"length"|...
            MakePin("FullResponse",  PinDataType::String),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.Auto ────────────────────────────────────────────────────────────
    // 从配置文件读取多个 provider，按 priority 依次 fallback，第一个成功的返回结果
    // Provider 引脚：空/"auto" = 自动 fallback；填 provider name = 直接使用指定 provider
    reg("LLM.Auto", "LLM Auto", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("ConfigFile",   PinDataType::String),   // JSON 配置文件路径
            MakePin("Provider",     PinDataType::String),   // 空/"auto"=自动, 或指定 provider name
            MakePin("Messages",     PinDataType::String),   // JSON 数组字符串
            MakePin("SystemPrompt", PinDataType::String),   // 可选
            MakePin("MaxTokens",    PinDataType::Integer),  // 默认 1024
            MakePin("Temperature",  PinDataType::Float),    // 默认 0.7
            MakePin("Tools",        PinDataType::String),   // function schema，可选
        },
        {
            MakeFlowPin("onReply"),
            MakeFlowPin("onToolCall"),
            MakeFlowPin("onError"),
            MakePin("Reply",         PinDataType::String),
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("FinishReason",  PinDataType::String),
            MakePin("UsedProvider",  PinDataType::String),  // 实际使用的 provider 名
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.AutoStream ──────────────────────────────────────────────────────
    // 流式版 LLM.Auto：多 provider fallback + SSE 逐 token 推送
    // Provider 引脚：空/"auto"=自动 fallback；填 provider name=直接使用指定 provider
    reg("LLM.AutoStream", "LLM Auto Stream", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("ConfigFile",   PinDataType::String),
            MakePin("Provider",     PinDataType::String),   // 空/"auto"=自动, 或指定 provider name
            MakePin("Messages",     PinDataType::String),
            MakePin("SystemPrompt", PinDataType::String),
            MakePin("MaxTokens",    PinDataType::Integer),
            MakePin("Temperature",  PinDataType::Float),
            MakePin("Tools",        PinDataType::String),
        },
        {
            MakeFlowPin("onChunk"),                          // 每个 token 激活一次
            MakeFlowPin("onToolCall"),
            MakeFlowPin("onDone"),                           // 全部 chunk 完毕
            MakeFlowPin("onError"),
            MakePin("Token",         PinDataType::String),   // 当前 token（onChunk 时）
            MakePin("FullText",      PinDataType::String),   // 完整文本（onDone 时）
            MakePin("ToolCallsJSON", PinDataType::String),
            MakePin("UsedProvider",  PinDataType::String),   // 实际使用的 provider 名
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── LLM.StreamChat ──────────────────────────────────────────────────────
    // 流式 OpenAI 兼容 Chat（SSE 批量聚合）
    reg("LLM.StreamChat", "LLM Stream Chat", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",      PinDataType::String),
            MakePin("ApiKey",       PinDataType::String),
            MakePin("Model",        PinDataType::String),
            MakePin("Messages",     PinDataType::String),
            MakePin("SystemPrompt", PinDataType::String),
            MakePin("MaxTokens",    PinDataType::Integer),
            MakePin("Temperature",  PinDataType::Float),
            MakePin("Tools",        PinDataType::String),
        },
        {
            MakeFlowPin("onChunk"),                          // 每个 token 激活一次（文本流）
            MakeFlowPin("onToolCall"),                       // finish_reason=tool_calls 时触发
            MakeFlowPin("onDone"),                           // 全部 chunk 完毕（文本流结束）
            MakeFlowPin("onError"),
            MakePin("Token",         PinDataType::String),   // 当前 token（onChunk 时）
            MakePin("FullText",      PinDataType::String),   // 完整文本（onDone 时）
            MakePin("ToolCallsJSON", PinDataType::String),   // tool_calls JSON（onToolCall 时）
            MakePin("FinishReason",  PinDataType::String),   // "stop"|"tool_calls"|"length"|...
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // ── Context.Compress ─────────────────────────────────────────────────────
    // 压缩对话历史：保留最近 KeepRecent 轮，用 LLM 摘要更早的内容
    reg("Context.Compress", "Context Compress", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",    PinDataType::String),
            MakePin("ApiKey",     PinDataType::String),
            MakePin("Model",      PinDataType::String),
            MakePin("Messages",   PinDataType::String),
            MakePin("KeepRecent", PinDataType::Integer),
            MakePin("MaxTokens",  PinDataType::Integer),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("Compressed",   PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

    // LLM.StructuredOutput — 强制 JSON Schema 输出
    reg("LLM.StructuredOutput", "LLM Structured Output", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",     PinDataType::String),
            MakePin("ApiKey",      PinDataType::String),
            MakePin("Model",       PinDataType::String),
            MakePin("Messages",    PinDataType::String),
            MakePin("SystemPrompt",PinDataType::String),
            MakePin("SchemaName",  PinDataType::String),
            MakePin("Schema",      PinDataType::String),
            MakePin("MaxTokens",   PinDataType::Integer),
            MakePin("Temperature", PinDataType::Float),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Output",       PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // LLM.Route — LLM 驱动的路由分发
    reg("LLM.Route", "LLM Route", "AI/LLM",
        {
            MakeFlowPin(""),
            MakePin("BaseURL", PinDataType::String),
            MakePin("ApiKey",  PinDataType::String),
            MakePin("Model",   PinDataType::String),
            MakePin("Input",   PinDataType::String),
            MakePin("Routes",  PinDataType::String),   // JSON array of {label,description}
        },
        {
            MakeFlowPin("onRoute0"),
            MakeFlowPin("onRoute1"),
            MakeFlowPin("onRoute2"),
            MakeFlowPin("onRoute3"),
            MakeFlowPin("onRoute4"),
            MakeFlowPin("onRoute5"),
            MakeFlowPin("onRoute6"),
            MakeFlowPin("onRoute7"),
            MakeFlowPin("onError"),
            MakePin("SelectedRoute", PinDataType::Integer),
            MakePin("SelectedLabel", PinDataType::String),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "6A0572");

    // Intent.Classify — 意图识别
    reg("Intent.Classify", "Intent Classify", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL", PinDataType::String),
            MakePin("ApiKey",  PinDataType::String),
            MakePin("Model",   PinDataType::String),
            MakePin("Text",    PinDataType::String),
            MakePin("Intents", PinDataType::String),   // JSON array of string or {label,description}
        },
        {
            MakeFlowPin("onMatched"),
            MakeFlowPin("onUnknown"),
            MakeFlowPin("onError"),
            MakePin("Intent",       PinDataType::String),
            MakePin("Confidence",   PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

}

} // namespace Runtime
} // namespace NodeEditor