// Runtime/nodedefs/BuiltinNodeDefs_AI_Agent.cpp
// Generated by tools/split_nodedefs_ai.ps1 from BuiltinNodeDefs_AI.cpp
//
// Contains the RegisterNodeDefs_AI_Agent() function, registering AI/Agent
// node definitions. Called by RegisterNodeDefs_AI().
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

void RegisterNodeDefs_AI_Agent(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };
    // 从文件加载对话历史 JSON 数组
    // WebGL：直接 onNew + 空数组
    reg("Memory.LoadHistory", "Memory Load History", "AI/Memory",
        {
            MakeFlowPin("In"),
            MakePin("Path",        PinDataType::String),   // 历史文件路径
            MakePin("MaxMessages", PinDataType::Integer),  // 0=不限，截断最旧的
        },
        {
            MakeFlowPin("onSuccess"),                      // 文件存在且解析成功
            MakeFlowPin("onNew"),                          // 文件不存在（首次启动）
            MakeFlowPin("onError"),
            MakePin("Messages",     PinDataType::String),  // JSON 数组字符串
            MakePin("Count",        PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // ── Memory.SaveHistory ──────────────────────────────────────────────────
    // 把 messages 数组写回文件（含可选截断）
    // WebGL：no-op，直接 onSuccess
    reg("Memory.SaveHistory", "Memory Save History", "AI/Memory",
        {
            MakeFlowPin("In"),
            MakePin("Path",        PinDataType::String),   // 历史文件路径
            MakePin("Messages",    PinDataType::String),   // JSON 数组字符串
            MakePin("MaxMessages", PinDataType::Integer),  // 0=不限，写入前截断
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "6A0572");

    // UserInput.Wait — 等待用户在编辑器输入框输入文本
    reg("UserInput.Wait", "Wait For Input", "AI",
        {
            MakeFlowPin(""),
            MakePin("Prompt",       PinDataType::String),
            MakePin("DefaultValue", PinDataType::String),
        },
        {
            MakeFlowPin(""),
            MakePin("Input", PinDataType::String),
        },
        "6A5F9A");

    // ── Agent.Plan ───────────────────────────────────────────────────────────
    // 让 LLM 把复杂 Goal 分解为可执行步骤列表（JSON 数组），配合 Tool.CallByName
    reg("Agent.Plan", "Agent Plan", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",         PinDataType::String),
            MakePin("ApiKey",          PinDataType::String),
            MakePin("Model",           PinDataType::String),
            MakePin("Goal",            PinDataType::String),  // 目标描述
            MakePin("AvailableTools",  PinDataType::String),  // JSON 数组，每项含 name+description
            MakePin("MaxSteps",        PinDataType::Integer), // 最大步骤数，default 5
            MakePin("MaxTokens",       PinDataType::Integer),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("PlanJSON",      PinDataType::String),  // JSON 数组：[{"tool","arguments","reason"}]
            MakePin("StepCount",     PinDataType::Integer),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "5080C0"); // 蓝紫色

    // ── Agent.Reflect ────────────────────────────────────────────────────────
    // 让 LLM 评估上一步输出是否满足 Criteria，不满足时触发 onFail + Feedback
    reg("Agent.Reflect", "Agent Reflect", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("BaseURL",     PinDataType::String),
            MakePin("ApiKey",      PinDataType::String),
            MakePin("Model",       PinDataType::String),
            MakePin("Output",      PinDataType::String),  // 上一步的输出内容
            MakePin("Criteria",    PinDataType::String),  // 评判标准（自然语言）
            MakePin("MaxTokens",   PinDataType::Integer),
        },
        {
            MakeFlowPin("onPass"),
            MakeFlowPin("onFail"),
            MakeFlowPin("onError"),
            MakePin("Feedback",      PinDataType::String), // 不满足时的改进建议
            MakePin("Score",         PinDataType::String), // "pass" | "fail"
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "A05050"); // 红色

    // Agent.Spawn — 并行异步子蓝图
    reg("Agent.Spawn", "Agent Spawn", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("FilePath",  PinDataType::String),
            MakePin("Params",    PinDataType::String),  // JSON object
            MakePin("EventName", PinDataType::String),  // default: OnBeginPlay
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onError"),
            MakePin("SpawnId",      PinDataType::String),
            MakePin("Output",       PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "50A080");

    // Agent.Join — 等待多个 Spawn 全部完成
    reg("Agent.Join", "Agent Join", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("Count",   PinDataType::Integer),
            MakePin("Timeout", PinDataType::Float),
        },
        {
            MakeFlowPin("onDone"),
            MakeFlowPin("onTimeout"),
            MakePin("CompletedCount", PinDataType::Integer),
        },
        "50A080");

    // Memory.Store — 进程级 KV 存储
    reg("Memory.Store", "Memory Store", "AI/Memory",
        {
            MakeFlowPin(""),
            MakePin("Key",   PinDataType::String),
            MakePin("Value", PinDataType::String),
            MakePin("TTL",   PinDataType::Float),   // 0=永久
        },
        { MakeFlowPin("exec") },
        "4A90D9");

    // Memory.Recall — 读取记忆
    reg("Memory.Recall", "Memory Recall", "AI/Memory",
        {
            MakePin("Key",    PinDataType::String),
            MakePin("Prefix", PinDataType::String),
        },
        {
            MakePin("Value",      PinDataType::String),
            MakePin("Found",      PinDataType::Boolean),
            MakePin("AllMatches", PinDataType::String),
        },
        "4A90D9", "Simple");

    // Memory.Clear — 清空记忆
    reg("Memory.Clear", "Memory Clear", "AI/Memory",
        {
            MakeFlowPin(""),
            MakePin("Prefix", PinDataType::String),
        },
        {
            MakeFlowPin("exec"),
            MakePin("RemovedCount", PinDataType::Integer),
        },
        "4A90D9");

    // Trigger.Cron — 定时触发
    reg("Trigger.Cron", "Trigger Cron", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("IntervalSec", PinDataType::Float),
            MakePin("MaxCount",    PinDataType::Integer),
            MakePin("EventName",   PinDataType::String),
        },
        {
            MakeFlowPin("onTick"),
            MakeFlowPin("onDone"),
            MakePin("TickCount", PinDataType::Integer),
        },
        "E07B39");

    // Trigger.FileWatch — 文件变化触发
    reg("Trigger.FileWatch", "Trigger File Watch", "AI/Agent",
        {
            MakeFlowPin(""),
            MakePin("FilePath",        PinDataType::String),
            MakePin("PollIntervalSec", PinDataType::Float),
        },
        {
            MakeFlowPin("onChanged"),
            MakeFlowPin("onError"),
            MakePin("FilePath", PinDataType::String),
        },
        "E07B39");

}

} // namespace Runtime
} // namespace NodeEditor