// Runtime/nodedefs/BuiltinNodeDefs_GameMath.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_GameMath() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_GameMath(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    const char* VEC_COLOR  = "1A7A8A"; // 青色
    const char* PHY_COLOR  = "7A3A8A"; // 紫
    const char* STAT_COLOR = "8A3A1A"; // 深橙
    const char* CD_COLOR   = "3A6A8A"; // 钢蓝

    // ── Vec2 ────────────────────────────────────────────────────────────────
    reg("Vec2.Make", "Vec2 Make", "Game/Math",
        { MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float) },
        { MakePin("Vec2", PinDataType::String),
          MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Get", "Vec2 Get", "Game/Math",
        { MakePin("Vec2", PinDataType::String) },
        { MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Add", "Vec2 Add", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        VEC_COLOR, "Simple");

    reg("Vec2.Sub", "Vec2 Sub", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        VEC_COLOR, "Simple");

    reg("Vec2.Scale", "Vec2 Scale", "Game/Math",
        { MakePin("Vec2", PinDataType::String), MakePin("Scale", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) },
        VEC_COLOR, "Simple");

    reg("Vec2.Length", "Vec2 Length", "Game/Math",
        { MakePin("Vec2", PinDataType::String) },
        { MakePin("Length", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Normalize", "Vec2 Normalize", "Game/Math",
        { MakePin("Vec2", PinDataType::String) },
        { MakePin("Result", PinDataType::String), MakePin("Length", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Dot", "Vec2 Dot", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Distance", "Vec2 Distance", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Distance", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Lerp", "Vec2 Lerp", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String),
          MakePin("T", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) },
        VEC_COLOR, "Simple");

    reg("Vec2.Angle", "Vec2 Angle", "Game/Math",
        { MakePin("Vec2", PinDataType::String) },
        { MakePin("Degrees", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec2.Rotate", "Vec2 Rotate", "Game/Math",
        { MakePin("Vec2", PinDataType::String), MakePin("Degrees", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) },
        VEC_COLOR, "Simple");

    reg("Vec2.Zero", "Vec2 Zero", "Game/Math", {},
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec2.One", "Vec2 One", "Game/Math", {},
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    // ── Vec3 ────────────────────────────────────────────────────────────────
    reg("Vec3.Make", "Vec3 Make", "Game/Math",
        { MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float),
          MakePin("Z", PinDataType::Float) },
        { MakePin("Vec3", PinDataType::String),
          MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float),
          MakePin("Z", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec3.Get", "Vec3 Get", "Game/Math",
        { MakePin("Vec3", PinDataType::String) },
        { MakePin("X", PinDataType::Float), MakePin("Y", PinDataType::Float),
          MakePin("Z", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec3.Add", "Vec3 Add", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Sub", "Vec3 Sub", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Scale", "Vec3 Scale", "Game/Math",
        { MakePin("Vec3", PinDataType::String), MakePin("Scale", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Length", "Vec3 Length", "Game/Math",
        { MakePin("Vec3", PinDataType::String) },
        { MakePin("Length", PinDataType::Float) }, VEC_COLOR, "Simple");

    reg("Vec3.Normalize", "Vec3 Normalize", "Game/Math",
        { MakePin("Vec3", PinDataType::String) },
        { MakePin("Result", PinDataType::String), MakePin("Length", PinDataType::Float) },
        VEC_COLOR, "Simple");

    reg("Vec3.Dot", "Vec3 Dot", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::Float) }, VEC_COLOR, "Simple");

    reg("Vec3.Cross", "Vec3 Cross", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Distance", "Vec3 Distance", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Distance", PinDataType::Float) }, VEC_COLOR, "Simple");

    reg("Vec3.Lerp", "Vec3 Lerp", "Game/Math",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String),
          MakePin("T", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Reflect", "Vec3 Reflect", "Game/Math",
        { MakePin("Vec3", PinDataType::String), MakePin("Normal", PinDataType::String) },
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.Zero", "Vec3 Zero", "Game/Math", {},
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    reg("Vec3.One", "Vec3 One", "Game/Math", {},
        { MakePin("Result", PinDataType::String) }, VEC_COLOR, "Simple");

    // ── 物理碰撞辅助 ─────────────────────────────────────────────────────────
    reg("Physics.PointInRect", "Point In Rect", "Game/Physics",
        { MakePin("PointX", PinDataType::Float), MakePin("PointY", PinDataType::Float),
          MakePin("RectX",  PinDataType::Float), MakePin("RectY",  PinDataType::Float),
          MakePin("RectW",  PinDataType::Float), MakePin("RectH",  PinDataType::Float) },
        { MakePin("Inside", PinDataType::Boolean) },
        PHY_COLOR, "Simple");

    reg("Physics.RectOverlap", "Rect Overlap", "Game/Physics",
        { MakePin("AX", PinDataType::Float), MakePin("AY", PinDataType::Float),
          MakePin("AW", PinDataType::Float), MakePin("AH", PinDataType::Float),
          MakePin("BX", PinDataType::Float), MakePin("BY", PinDataType::Float),
          MakePin("BW", PinDataType::Float), MakePin("BH", PinDataType::Float) },
        { MakePin("Overlap",  PinDataType::Boolean),
          MakePin("OverlapX", PinDataType::Float), MakePin("OverlapY", PinDataType::Float),
          MakePin("OverlapW", PinDataType::Float), MakePin("OverlapH", PinDataType::Float) },
        PHY_COLOR, "Simple");

    reg("Physics.CircleOverlap", "Circle Overlap", "Game/Physics",
        { MakePin("C1X", PinDataType::Float), MakePin("C1Y", PinDataType::Float),
          MakePin("R1",  PinDataType::Float),
          MakePin("C2X", PinDataType::Float), MakePin("C2Y", PinDataType::Float),
          MakePin("R2",  PinDataType::Float) },
        { MakePin("Overlap",          PinDataType::Boolean),
          MakePin("Distance",         PinDataType::Float),
          MakePin("PenetrationDepth", PinDataType::Float) },
        PHY_COLOR, "Simple");

    reg("Physics.PointInCircle", "Point In Circle", "Game/Physics",
        { MakePin("PointX", PinDataType::Float), MakePin("PointY", PinDataType::Float),
          MakePin("CX",     PinDataType::Float), MakePin("CY",     PinDataType::Float),
          MakePin("Radius", PinDataType::Float) },
        { MakePin("Inside",   PinDataType::Boolean),
          MakePin("Distance", PinDataType::Float) },
        PHY_COLOR, "Simple");

    reg("Physics.Raycast2D", "Raycast 2D", "Game/Physics",
        { MakePin("OriginX", PinDataType::Float), MakePin("OriginY", PinDataType::Float),
          MakePin("DirX",    PinDataType::Float), MakePin("DirY",    PinDataType::Float),
          MakePin("MaxDist", PinDataType::Float),
          MakePin("RectX",   PinDataType::Float), MakePin("RectY",   PinDataType::Float),
          MakePin("RectW",   PinDataType::Float), MakePin("RectH",   PinDataType::Float) },
        { MakePin("Hit",     PinDataType::Boolean),
          MakePin("HitX",    PinDataType::Float), MakePin("HitY",    PinDataType::Float),
          MakePin("HitDist", PinDataType::Float),
          MakePin("NormalX", PinDataType::Float), MakePin("NormalY", PinDataType::Float) },
        PHY_COLOR, "Simple");

    // ── Stat 数值系统 ────────────────────────────────────────────────────────
    reg("Stat.Set", "Stat Set", "Game/Stat",
        { MakeFlowPin(""),
          MakePin("Name",   PinDataType::String),
          MakePin("Base",   PinDataType::Float),
          MakePin("Min",    PinDataType::Float),
          MakePin("Max",    PinDataType::Float),
          MakePin("Entity", PinDataType::String) },
        { MakeFlowPin("exec") },
        STAT_COLOR);

    reg("Stat.Get", "Stat Get", "Game/Stat",
        { MakePin("Name",   PinDataType::String),
          MakePin("Entity", PinDataType::String) },
        { MakePin("Value",         PinDataType::Float),
          MakePin("Base",          PinDataType::Float),
          MakePin("ModifierCount", PinDataType::Integer) },
        STAT_COLOR, "Simple");

    reg("Stat.AddModifier", "Stat Add Modifier", "Game/Stat",
        { MakeFlowPin(""),
          MakePin("Name",   PinDataType::String),
          MakePin("Entity", PinDataType::String),
          MakePin("ModId",  PinDataType::String),
          MakePinEnum("Type", "add,mul,override"),
          MakePin("Value",  PinDataType::Float) },
        { MakeFlowPin("exec"), MakePin("NewValue", PinDataType::Float) },
        STAT_COLOR);

    reg("Stat.RemoveModifier", "Stat Remove Modifier", "Game/Stat",
        { MakeFlowPin(""),
          MakePin("Name",   PinDataType::String),
          MakePin("Entity", PinDataType::String),
          MakePin("ModId",  PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("NewValue", PinDataType::Float) },
        STAT_COLOR);

    reg("Stat.Reset", "Stat Reset", "Game/Stat",
        { MakeFlowPin(""),
          MakePin("Name",   PinDataType::String),
          MakePin("Entity", PinDataType::String) },
        { MakeFlowPin("exec") },
        STAT_COLOR);

    // ── Cooldown 冷却系统 ────────────────────────────────────────────────────
    reg("Cooldown.Start", "Cooldown Start", "Game/Cooldown",
        { MakeFlowPin(""),
          MakePin("Key",      PinDataType::String),
          MakePin("Duration", PinDataType::Float) },
        { MakeFlowPin("exec") },
        CD_COLOR);

    reg("Cooldown.IsReady", "Cooldown Is Ready", "Game/Cooldown",
        { MakePin("Key", PinDataType::String) },
        { MakePin("Ready",     PinDataType::Boolean),
          MakePin("Remaining", PinDataType::Float) },
        CD_COLOR, "Simple");

    reg("Cooldown.GetRemaining", "Cooldown Get Remaining", "Game/Cooldown",
        { MakePin("Key",      PinDataType::String),
          MakePin("Duration", PinDataType::Float) },
        { MakePin("Remaining", PinDataType::Float),
          MakePin("Progress",  PinDataType::Float) },
        CD_COLOR, "Simple");

    reg("Cooldown.Reset", "Cooldown Reset", "Game/Cooldown",
        { MakeFlowPin(""), MakePin("Key", PinDataType::String) },
        { MakeFlowPin("exec") },
        CD_COLOR);
}

// ============================================================================
// Socket — TCP/UDP 节点定义
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor