// Runtime/nodedefs/BuiltinNodeDefs_Array.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Array() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Array(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("ArrayLength", "Array Length", "Misc/Array",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Length", PinDataType::Integer) },
        "", "Simple");

    reg("ArrayGet", "Array Get", "Misc/Array",
        { MakePin("Array", PinDataType::Array), MakePin("Index", PinDataType::Integer) },
        { MakePin("Element", PinDataType::Any), MakePin("Valid", PinDataType::Boolean) },
        "", "Simple");

    reg("ArraySet", "Array Set", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Index", PinDataType::Integer), MakePin("Element", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) });

    reg("ArrayRemoveAt", "Array Remove At", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Index", PinDataType::Integer) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Valid", PinDataType::Boolean) });

    reg("ArrayClear", "Array Clear", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) });

    reg("ForEachLoop", "For Each Loop", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) },
        { MakeFlowPin("Loop Body"), MakePin("Array Element", PinDataType::Any),
          MakePin("Array Index", PinDataType::Integer), MakeFlowPin("Completed") });

    reg("ArrayAdd", "Array Add", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Element", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("New Length", PinDataType::Integer) });

    reg("ArrayInsert", "Array Insert", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Index", PinDataType::Integer), MakePin("Element", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) });

    reg("ArrayContains", "Array Contains", "Misc/Array",
        { MakePin("Array", PinDataType::Array), MakePin("Element", PinDataType::Any) },
        { MakePin("Found", PinDataType::Boolean), MakePin("Index", PinDataType::Integer) },
        "", "Simple");

    reg("ArrayReverse", "Array Reverse", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) });

    reg("MakeArray", "Make Array", "Misc/Array",
        { MakePin("Element 0", PinDataType::Any) },
        { MakePin("Array", PinDataType::Array) },
        "", "Simple");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("MakeArray"));
        if (d) d->customProperties["dynamicInputs"] = "Any";
    }

    // Array Find — 查找第一个匹配元素的索引（纯查询，不修改数组）
    reg("ArrayFind", "Array Find", "Misc/Array",
        { MakePin("Array", PinDataType::Array), MakePin("Element", PinDataType::Any) },
        { MakePin("Index", PinDataType::Integer), MakePin("Found", PinDataType::Boolean) },
        "", "Simple");

    // Array Slice — 返回子数组 [Start, End)（不含 End）
    reg("ArraySlice", "Array Slice", "Misc/Array",
        { MakePin("Array", PinDataType::Array),
          MakePin("Start", PinDataType::Integer), MakePin("End", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Array) },
        "", "Simple");

    // Array Concat — 拼接两个数组
    reg("ArrayConcat", "Array Concat", "Misc/Array",
        { MakePin("Array A", PinDataType::Array), MakePin("Array B", PinDataType::Array) },
        { MakePin("Result", PinDataType::Array) },
        "", "Simple");

    // Array Unique — 去重（保留第一次出现顺序）
    reg("ArrayUnique", "Array Unique", "Misc/Array",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Result", PinDataType::Array) },
        "", "Simple");

    // Array Sort — 排序（仅支持同质数组：全 Int / 全 Float / 全 String）
    reg("ArraySort", "Array Sort", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array),
          MakePin("Descending", PinDataType::Boolean) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array) });

    // Array Last — 获取最后一个元素
    reg("ArrayLast", "Array Last", "Misc/Array",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Element", PinDataType::Any), MakePin("Valid", PinDataType::Boolean) },
        "", "Simple");

    // Array First — 获取第一个元素
    reg("ArrayFirst", "Array First", "Misc/Array",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("Element", PinDataType::Any), MakePin("Valid", PinDataType::Boolean) },
        "", "Simple");

    // Array Remove — 删除第一个匹配的元素（按值查找）
    reg("ArrayRemove", "Array Remove", "Misc/Array",
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Element", PinDataType::Any) },
        { MakeFlowPin(""), MakePin("Array", PinDataType::Array), MakePin("Removed", PinDataType::Boolean) });
}


} // namespace Runtime
} // namespace NodeEditor