// Runtime/nodedefs/BuiltinNodeDefs_Action.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Action() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Action(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("InputActionFire", "InputAction Fire", "Action",
        {},
        { MakePin("", PinDataType::Custom, false), MakeFlowPin("Pressed"), MakeFlowPin("Released") },
        "FF8080");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("InputActionFire"));
        if (d && !d->outputPins.empty())
            d->outputPins[0].customProperties["pinType"] = "Delegate";
    }

    reg("OutputAction", "OutputAction", "Action",
        { MakePin("Sample", PinDataType::Float), MakePin("Event", PinDataType::Custom, false) },
        { MakePin("Condition", PinDataType::Boolean) });
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("OutputAction"));
        if (d && d->inputPins.size() >= 2)
            d->inputPins[1].customProperties["pinType"] = "Delegate";
    }

    reg("SetTimer", "Set Timer", "Action",
        { MakeFlowPin(""), MakePin("Object", PinDataType::Object),
          MakePin("Function Name", PinDataType::Custom, false),
          MakePin("Time", PinDataType::Float), MakePin("Looping", PinDataType::Boolean) },
        { MakeFlowPin("Exec"), MakePin("TimerHandle", PinDataType::Integer) },
        "80C3F8");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("SetTimer"));
        if (d && d->inputPins.size() >= 3)
            d->inputPins[2].customProperties["pinType"] = "Function";
    }

    reg("RemoveTimer", "Remove Timer", "Action",
        { MakeFlowPin(""), MakePin("TimerHandle", PinDataType::Integer) },
        { MakeFlowPin("Exec"), MakePin("Success", PinDataType::Boolean) },
        "FF6060");

    reg("PauseTimer", "Pause Timer", "Action",
        { MakeFlowPin(""), MakePin("TimerHandle", PinDataType::Integer) },
        { MakeFlowPin("Exec"), MakePin("Success", PinDataType::Boolean) },
        "FFA040");

    reg("ResumeTimer", "Resume Timer", "Action",
        { MakeFlowPin(""), MakePin("TimerHandle", PinDataType::Integer) },
        { MakeFlowPin("Exec"), MakePin("Success", PinDataType::Boolean) },
        "40C080");

    reg("CustomEvent", "Custom Event", "Action",
        {},
        { MakePin("Event", PinDataType::Custom, false), MakeFlowPin("Exec") },
        "A080F8");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("CustomEvent"));
        if (d && !d->outputPins.empty())
            d->outputPins[0].customProperties["pinType"] = "Function";
    }

    reg("TraceByChannel", "Single Line Trace by Channel", "Action",
        { MakeFlowPin(""), MakeFlowPin("Start"), MakePin("End", PinDataType::Integer),
          MakePin("Trace Channel", PinDataType::Float), MakePin("Trace Complex", PinDataType::Boolean),
          MakePin("Actors to Ignore", PinDataType::Integer), MakePin("Draw Debug Type", PinDataType::Boolean),
          MakePin("Ignore Self", PinDataType::Boolean) },
        { MakeFlowPin(""), MakePin("Out Hit", PinDataType::Float), MakePin("Return Value", PinDataType::Boolean) },
        "FF8040");
}


} // namespace Runtime
} // namespace NodeEditor