// Runtime/nodedefs/BuiltinNodeDefs_Event.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Event() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Event(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("OnBeginPlay", "On Begin Play", "Event",
        {},
        { MakeFlowPin("") },
        "FF6060");

    // ── Proto 节点 ─────────────────────────────────────────────────────────────
    // Protobuf 编解码（需链接 protobuf_s）
    // 内置 schema：pbbp2.Frame（飞书长连接帧，无需 LoadSchema）
    reg("Proto.LoadSchema", "Proto Load Schema", "Protobuf",
        {
            MakeFlowPin(""),
            MakePin("SchemaName", PinDataType::String),  // 唯一标识，如 "my.proto"
            MakePin("ProtoText",  PinDataType::String),  // proto 源文本
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "8E6BBF");

    reg("Proto.Decode", "Proto Decode", "Protobuf",
        {
            MakeFlowPin(""),
            MakePin("Data",        PinDataType::String),  // 二进制数据（bytes）
            MakePin("MessageType", PinDataType::String),  // 如 "pbbp2.Frame"，默认即 pbbp2.Frame
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("JSON",         PinDataType::String),  // 解码后的 JSON 字符串
            MakePin("ErrorMessage", PinDataType::String),
        },
        "8E6BBF");

    reg("Proto.Encode", "Proto Encode", "Protobuf",
        {
            MakeFlowPin(""),
            MakePin("JSON",        PinDataType::String),  // JSON 对象字符串
            MakePin("MessageType", PinDataType::String),  // 如 "pbbp2.Frame"
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("Data",         PinDataType::String),  // 序列化后的二进制
            MakePin("ErrorMessage", PinDataType::String),
        },
        "8E6BBF");

    reg("Proto.GetField", "Proto Get Field", "Protobuf",
        {
            MakePin("JSON",    PinDataType::String),  // Proto.Decode 输出的 JSON
            MakePin("Path",    PinDataType::String),  // dot-path，如 "headers.0.value"
            MakePin("Default", PinDataType::Unknown),
        },
        {
            MakePin("Value",   PinDataType::Unknown),
            MakePin("Found",   PinDataType::Boolean),
        },
        "8E6BBF");

    // ── Crypto 节点 ────────────────────────────────────────────────────────────
    reg("Crypto.SHA256", "SHA256", "Crypto",
        { MakePin("Data", PinDataType::String) },
        { MakePin("Hash", PinDataType::String) },
        "27AE60");

    reg("Crypto.HMAC", "HMAC", "Crypto",
        {
            MakePin("Key",       PinDataType::String),
            MakePin("Data",      PinDataType::String),
            MakePin("Algorithm", PinDataType::String),  // "sha256"（默认）
        },
        {
            MakePin("Hash",       PinDataType::String),  // hex
            MakePin("HashBase64", PinDataType::String),  // base64
        },
        "27AE60");

    reg("Crypto.MD5", "MD5", "Crypto",
        { MakePin("Data", PinDataType::String) },
        { MakePin("Hash", PinDataType::String) },
        "27AE60");

    reg("Crypto.Base64Enc", "Base64 Encode", "Crypto",
        { MakePin("Data",   PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "27AE60");

    reg("Crypto.Base64Dec", "Base64 Decode", "Crypto",
        { MakePin("Data",   PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "27AE60");

    reg("Crypto.HexEncode", "Hex Encode", "Crypto",
        { MakePin("Data",   PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "27AE60");

    reg("Crypto.HexDecode", "Hex Decode", "Crypto",
        { MakePin("Data",   PinDataType::String) },
        {
            MakePin("Result", PinDataType::String),
            MakePin("Valid",  PinDataType::Boolean),
        },
        "27AE60");

    // ── HTTP Server 节点 ───────────────────────────────────────────────────────
    reg("HTTP.Listen", "HTTP Listen", "Network/Server",
        {
            MakeFlowPin(""),
            MakePin("Port",     PinDataType::Integer),  // 默认 7788
            MakePin("Host",     PinDataType::String),   // 默认 0.0.0.0
            MakePin("BasePath", PinDataType::String),   // 默认 /
        },
        {
            MakeFlowPin("onRequest"),
            MakeFlowPin("onError"),
            MakePin("Method",    PinDataType::String),
            MakePin("Path",      PinDataType::String),
            MakePin("Body",      PinDataType::String),
            MakePin("Headers",   PinDataType::String),  // JSON
            MakePin("RequestId", PinDataType::String),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "2E86AB");

    reg("HTTP.Respond", "HTTP Respond", "Network/Server",
        {
            MakeFlowPin(""),
            MakePin("RequestId",   PinDataType::String),  // 空则读变量 __http_request_id
            MakePin("StatusCode",  PinDataType::Integer), // 默认 200
            MakePin("Body",        PinDataType::String),
            MakePinEnum("ContentType",
                "application/json,text/plain,text/html,application/x-www-form-urlencoded,multipart/form-data",
                "application/json"),
        },
        { MakeFlowPin("") },
        "2E86AB");

    reg("HTTP.Stop", "HTTP Stop", "Network/Server",
        {
            MakeFlowPin(""),
            MakePin("ListenKey", PinDataType::String),  // "host:port"，空则停止全部
        },
        { MakeFlowPin("") },
        "2E86AB");

    // ── WebSocket 节点 ────────────────────────────────────────────────────────
    reg("WS.Connect", "WS Connect", "Network/WebSocket",
        {
            MakeFlowPin(""),
            MakePin("URL",     PinDataType::String),  // ws://host:port/path
            MakePin("Headers", PinDataType::String),  // JSON，可选
        },
        {
            MakeFlowPin("onOpen"),
            MakeFlowPin("onMessage"),
            MakeFlowPin("onClose"),
            MakeFlowPin("onError"),
            MakePin("ConnectionId",  PinDataType::String),
            MakePin("Message",       PinDataType::String),
            MakePin("CloseCode",     PinDataType::Integer),
            MakePin("CloseReason",   PinDataType::String),
            MakePin("ErrorMessage",  PinDataType::String),
        },
        "E8A838");

    reg("WS.Send", "WS Send", "Network/WebSocket",
        {
            MakeFlowPin(""),
            MakePin("ConnectionId", PinDataType::String),  // 空则读 __ws_conn_id
            MakePin("Message",      PinDataType::String),
        },
        {
            MakeFlowPin("onSuccess"),
            MakeFlowPin("onError"),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "E8A838");

    reg("WS.Close", "WS Close", "Network/WebSocket",
        {
            MakeFlowPin(""),
            MakePin("ConnectionId", PinDataType::String),
            MakePin("Code",         PinDataType::Integer),
            MakePin("Reason",       PinDataType::String),
        },
        { MakeFlowPin("") },
        "E8A838");

    reg("WS.Server", "WS Server", "Network/WebSocket",
        {
            MakeFlowPin(""),
            MakePin("Port", PinDataType::Integer),  // 默认 7790
            MakePin("Host", PinDataType::String),   // 默认 0.0.0.0
            MakePin("Path", PinDataType::String),   // 默认 /ws
        },
        {
            MakeFlowPin("onConnect"),
            MakeFlowPin("onMessage"),
            MakeFlowPin("onClose"),
            MakeFlowPin("onError"),
            MakePin("ConnectionId", PinDataType::String),
            MakePin("Message",      PinDataType::String),
            MakePin("CloseCode",    PinDataType::Integer),
            MakePin("ErrorMessage", PinDataType::String),
        },
        "E8A838");

    // ── Platform 判断节点 ──────────────────────────────────────────────────────
    // 纯数据节点，编译期常量，无 exec flow
    reg("Platform.IsWindows", "Is Windows", "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    reg("Platform.IsLinux",   "Is Linux",   "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    reg("Platform.IsMacOS",   "Is macOS",   "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    reg("Platform.IsAndroid", "Is Android", "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    reg("Platform.IsIOS",     "Is iOS",     "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    reg("Platform.IsWebGL",   "Is WebGL",   "Platform",
        {}, { MakePin("Result", PinDataType::Boolean) }, "4A90D9");
    

    reg("OnTick", "On Tick", "Event",
        {},
        { MakeFlowPin(""), MakePin("DeltaTime", PinDataType::Float) },
        "FF6060");
    

    reg("CustomEventNode", "Custom Event", "Event",
        {},
        { MakeFlowPin(""), MakePin("EventName", PinDataType::String) },
        "FF8040");

    // FireEvent：在运行时通过名字触发一个 Custom Event（相当于 DispatchEvent）
    // 用于在异步回调里触发下一轮事件，避免在 exec 图里形成 cycle。
    reg("FireEvent", "Fire Event", "Event",
        {
            MakeFlowPin(""),
            MakePin("EventName", PinDataType::String),
        },
        {
            MakeFlowPin(""),
        },
        "FF8040");
    
}


} // namespace Runtime
} // namespace NodeEditor