// Runtime/nodedefs/BuiltinNodeDefs_Math.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Math() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Math(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    // --- Arithmetic (Math/Arithmetic) ---
    reg("Add", "+", "Math/Arithmetic",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Subtract", "-", "Math/Arithmetic",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Multiply", "*", "Math/Arithmetic",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Divide", "/", "Math/Arithmetic",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Comparison (Math/Comparison) ---
    reg("Less", "<", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Greater", ">", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Equal", "==", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    // --- Logic (Math/Logic) ---
    reg("And", "AND", "Math/Logic",
        { MakePin("A", PinDataType::Boolean), MakePin("B", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Or", "OR", "Math/Logic",
        { MakePin("A", PinDataType::Boolean), MakePin("B", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Not", "NOT", "Math/Logic",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    // --- Conversion (Math/Conversion) ---
    reg("IntToFloat", "Int to Float", "Math/Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("FloatToInt", "Float to Int", "Math/Conversion",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Integer) },
        "80C3F8", "Simple");

    reg("FloatToBool", "Float to Bool", "Math/Conversion",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("IntToString", "Int to String", "Math/Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::String) },
        "80C3F8", "Simple");

    reg("FloatToString", "Float to String", "Math/Conversion",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::String) },
        "80C3F8", "Simple");

    reg("BoolToInt", "Bool to Int", "Math/Conversion",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Integer) },
        "80C3F8", "Simple");

    reg("IntToBool", "Int to Bool", "Math/Conversion",
        { MakePin("Value", PinDataType::Integer) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("BoolToFloat", "Bool to Float", "Math/Conversion",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Functions (Math/Functions) ---
    reg("Abs", "Abs", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Clamp", "Clamp", "Math/Functions",
        { MakePin("Value", PinDataType::Float), MakePin("Min", PinDataType::Float),
          MakePin("Max", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Min", "Min", "Math/Functions",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Max", "Max", "Math/Functions",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Random (Math/Random) ---
    reg("Random", "Random Float", "Math/Random",
        {},
        { MakePin("Value", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("RandomInRange", "Random In Range", "Math/Random",
        { MakePin("Min", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Value", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- More Arithmetic ---
    reg("Modulo", "%", "Math/Arithmetic",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Power", "Power", "Math/Arithmetic",
        { MakePin("Base", PinDataType::Float), MakePin("Exponent", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Negate", "Negate", "Math/Arithmetic",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- More Comparison ---
    reg("NotEqual", "!=", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("LessEqual", "<=", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("GreaterEqual", ">=", "Math/Comparison",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    // --- More Logic ---
    reg("Nand", "NAND", "Math/Logic",
        { MakePin("A", PinDataType::Boolean), MakePin("B", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Nor", "NOR", "Math/Logic",
        { MakePin("A", PinDataType::Boolean), MakePin("B", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("Xor", "XOR", "Math/Logic",
        { MakePin("A", PinDataType::Boolean), MakePin("B", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::Boolean) },
        "80C3F8", "Simple");

    // --- More Conversion ---
    reg("StringToInt", "String to Int", "Math/Conversion",
        { MakePin("Value", PinDataType::String) },
        { MakePin("Result", PinDataType::Integer), MakePin("Valid", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("StringToFloat", "String to Float", "Math/Conversion",
        { MakePin("Value", PinDataType::String) },
        { MakePin("Result", PinDataType::Float), MakePin("Valid", PinDataType::Boolean) },
        "80C3F8", "Simple");

    reg("BoolToString", "Bool to String", "Math/Conversion",
        { MakePin("Value", PinDataType::Boolean) },
        { MakePin("Result", PinDataType::String) },
        "80C3F8", "Simple");

    // --- More Functions ---
    reg("Sqrt", "Sqrt", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Sin", "Sin", "Math/Functions",
        { MakePin("Value (Rad)", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Cos", "Cos", "Math/Functions",
        { MakePin("Value (Rad)", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Tan", "Tan", "Math/Functions",
        { MakePin("Value (Rad)", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Atan2", "Atan2", "Math/Functions",
        { MakePin("Y", PinDataType::Float), MakePin("X", PinDataType::Float) },
        { MakePin("Result (Rad)", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Asin", "Asin", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result (Rad)", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Acos", "Acos", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result (Rad)", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Atan", "Atan", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result (Rad)", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Hypot", "Hypot", "Math/Functions",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("DegreesToRadians", "Degrees to Radians", "Math/Functions",
        { MakePin("Degrees", PinDataType::Float) },
        { MakePin("Radians", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("RadiansToDegrees", "Radians to Degrees", "Math/Functions",
        { MakePin("Radians", PinDataType::Float) },
        { MakePin("Degrees", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Lerp", "Lerp", "Math/Functions",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float), MakePin("Alpha", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("MapRange", "Map Range", "Math/Functions",
        { MakePin("Value", PinDataType::Float), MakePin("InMin", PinDataType::Float), MakePin("InMax", PinDataType::Float),
          MakePin("OutMin", PinDataType::Float), MakePin("OutMax", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Ceil", "Ceil", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Floor", "Floor", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Round", "Round", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Sign", "Sign", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Constants (Math/Constants) ---
    reg("PI", "PI", "Math/Constants",
        {},
        { MakePin("Value", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("E", "E", "Math/Constants",
        {},
        { MakePin("Value", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Advanced Functions (Math/Functions) ---
    reg("InverseLerp", "Inverse Lerp", "Math/Functions",
        { MakePin("A", PinDataType::Float), MakePin("B", PinDataType::Float), MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Remap01", "Remap 0-1", "Math/Functions",
        { MakePin("Value", PinDataType::Float), MakePin("InMin", PinDataType::Float), MakePin("InMax", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("DegreesToRadians", "Degrees to Radians", "Math/Conversion",
        { MakePin("Degrees", PinDataType::Float) },
        { MakePin("Radians", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("RadiansToDegrees", "Radians to Degrees", "Math/Conversion",
        { MakePin("Radians", PinDataType::Float) },
        { MakePin("Degrees", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Wrap", "Wrap", "Math/Functions",
        { MakePin("Value", PinDataType::Float), MakePin("Min", PinDataType::Float), MakePin("Max", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Snap", "Snap to Grid", "Math/Functions",
        { MakePin("Value", PinDataType::Float), MakePin("GridSize", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Log2", "Log2", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Log10", "Log10", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    reg("Exp", "Exp", "Math/Functions",
        { MakePin("Value", PinDataType::Float) },
        { MakePin("Result", PinDataType::Float) },
        "80C3F8", "Simple");

    // --- Misc (直接在 Math 顶级) ---
    reg("Weird", "o.O", "Math",
        { MakePin("", PinDataType::Float) },
        { MakePin("", PinDataType::Float), MakePin("", PinDataType::Float) },
        "80C3F8", "Simple");
}


} // namespace Runtime
} // namespace NodeEditor