// Runtime/nodedefs/BuiltinNodeDefs_Flow.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Flow() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Flow(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("Branch", "Branch", "Flow",
        { MakeFlowPin(""), MakePin("Condition", PinDataType::Boolean) },
        { MakeFlowPin("True"), MakeFlowPin("False") },
        "8B3DB8");
    

    reg("DoN", "Do N", "Flow",
        { MakeFlowPin("Enter"), MakePin("N", PinDataType::Integer), MakeFlowPin("Reset") },
        { MakeFlowPin("Exit"), MakePin("Counter", PinDataType::Integer) });
    

    // ExecuteBlueprint: 完全异步模式（无 Sync 选项）
    {
        NodeDefinition d;
        d.id = "ExecuteBlueprint";
        d.name = "Execute Blueprint";
        d.category = "Flow";
        d.inputPins = {
            MakeFlowPin(""),
            MakePin("File",   PinDataType::String),
            MakePin("Params", PinDataType::String),   // optional JSON object: {"key":"value",...}
        };
        d.outputPins = {
            MakeFlowPin("Done"),
            MakeFlowPin("Completed"),
            MakePin("Success", PinDataType::Boolean),
            MakePin("Output",  PinDataType::String),
        };
        d.color = "FFA040";
        registry.registerNode(d);
    }

    reg("ForLoop", "For Loop", "Flow",
        { MakeFlowPin(""), MakePin("First Index", PinDataType::Integer),
          MakePin("Last Index", PinDataType::Integer) },
        { MakeFlowPin("Loop Body"), MakePin("Index", PinDataType::Integer),
          MakeFlowPin("Completed") },
        "2A7FAA");
    

    reg("WhileLoop", "While Loop", "Flow",
        { MakeFlowPin(""), MakePin("Condition", PinDataType::Boolean) },
        { MakeFlowPin("Loop Body"), MakeFlowPin("Completed") },
        "2A7FAA");
    

    reg("Delay", "Delay", "Flow",
        { MakeFlowPin(""), MakePin("Duration", PinDataType::Float) },
        { MakeFlowPin("Exec"), MakeFlowPin("Completed"), MakePin("TimerHandle", PinDataType::Integer) },
        "6A4AAA");
    

    reg("FlipFlop", "Flip Flop", "Flow",
        { MakeFlowPin("") },
        { MakeFlowPin("A"), MakeFlowPin("B"), MakePin("Is A", PinDataType::Boolean) },
        "2A7FAA");

    reg("Gate", "Gate", "Flow",
        { MakeFlowPin("Enter"), MakeFlowPin("Open"), MakeFlowPin("Close"),
          MakeFlowPin("Toggle") },
        { MakeFlowPin("Exit") },
        "2A7FAA");
    

    reg("DoOnce", "Do Once", "Flow",
        { MakeFlowPin(""), MakeFlowPin("Reset") },
        { MakeFlowPin("Completed") },
        "2A7FAA");
    

    // Sequence (Flow) — 按顺序执行多个 exec 输出
    {
        NodeDefinition d;
        d.id = "FlowSequence";
        d.name = "Sequence";
        d.category = "Flow";
        d.inputPins = { MakeFlowPin("") };
        d.outputPins = { MakeFlowPin("Then 0"), MakeFlowPin("Then 1"), MakeFlowPin("Then 2"), MakeFlowPin("Then 3") };
        registry.registerNode(d);
    }

    // Select — 三元选择节点
    reg("Select", "Select", "Flow",
        { MakePin("Condition", PinDataType::Boolean), MakePin("A", PinDataType::Any), MakePin("B", PinDataType::Any) },
        { MakePin("Result", PinDataType::Any) },
        "80C3F8", "Simple");

    // Switch on Int — 多分支选择
    {
        NodeDefinition d;
        d.id = "SwitchOnInt";
        d.name = "Switch on Int";
        d.category = "Flow";
        d.inputPins = { MakeFlowPin(""), MakePin("Selection", PinDataType::Integer) };
        d.outputPins = { MakeFlowPin("Default"), MakeFlowPin("0"), MakeFlowPin("1"), MakeFlowPin("2"), MakeFlowPin("3") };
        registry.registerNode(d);
    }

    // MultiGate — 依次激活多个输出（或随机）
    {
        NodeDefinition d;
        d.id = "MultiGate";
        d.name = "Multi Gate";
        d.category = "Flow";
        d.inputPins = { MakeFlowPin(""), MakeFlowPin("Reset"), MakePin("Loop", PinDataType::Boolean), MakePin("Random", PinDataType::Boolean) };
        d.outputPins = { MakeFlowPin("Out 0"), MakeFlowPin("Out 1"), MakeFlowPin("Out 2"), MakeFlowPin("Out 3") };
        registry.registerNode(d);
    }

    // ForLoopWithBreak — 可中断的 For Loop
    reg("ForLoopWithBreak", "For Loop with Break", "Flow",
        { MakeFlowPin(""), MakePin("First Index", PinDataType::Integer),
          MakePin("Last Index", PinDataType::Integer), MakeFlowPin("Break") },
        { MakeFlowPin("Loop Body"), MakePin("Index", PinDataType::Integer),
          MakeFlowPin("Completed") },
        "2A7FAA");
    

    // Switch on Bool — 根据 Bool 值二选一
    reg("SwitchOnBool", "Switch on Bool", "Flow",
        { MakeFlowPin(""), MakePin("Condition", PinDataType::Boolean) },
        { MakeFlowPin("True"), MakeFlowPin("False") },
        "8B3DB8");

    // Switch on String — 字符串多分支
    reg("SwitchOnString", "Switch on String", "Flow",
        { MakeFlowPin(""), MakePin("Selection", PinDataType::String),
          MakePin("Case 0", PinDataType::String), MakePin("Case 1", PinDataType::String),
          MakePin("Case 2", PinDataType::String), MakePin("Case 3", PinDataType::String),
          MakePin("Case 4", PinDataType::String), MakePin("Case 5", PinDataType::String) },
        { MakeFlowPin("Case 0"), MakeFlowPin("Case 1"),
          MakeFlowPin("Case 2"), MakeFlowPin("Case 3"),
          MakeFlowPin("Case 4"), MakeFlowPin("Case 5"), MakeFlowPin("Default") });

    // Switch on Int — 整数多分支（与 SwitchOnBool / SwitchOnString 对称）
    // Handler 在 BuiltinHandlers_Flow.cpp::handlers["SwitchOnInt"] 早已存在，
    // 但此前漏注册 NodeDef 导致用户在 Library 面板看不到、无法添加节点。
    // Handler 行为：按 Selection 整数找 name == std::to_string(sel) 的 exec 输出，
    // 找不到则走 "Default"。这里输出引脚命名 "0".."5" 与 handler 完全对应。
    reg("SwitchOnInt", "Switch on Int", "Flow",
        { MakeFlowPin(""), MakePin("Selection", PinDataType::Integer) },
        { MakeFlowPin("0"), MakeFlowPin("1"),
          MakeFlowPin("2"), MakeFlowPin("3"),
          MakeFlowPin("4"), MakeFlowPin("5"), MakeFlowPin("Default") });
}


} // namespace Runtime
} // namespace NodeEditor