// Runtime/nodedefs/BuiltinNodeDefs_String.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_String() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_String(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    reg("MakeString", "Make String", "Misc/String",
        { MakePin("Value", PinDataType::String) },
        { MakePin("String", PinDataType::String) },
        "", "Simple");

    reg("AppendString", "Append String", "Misc/String",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("AppendString"));
        if (d) d->customProperties["dynamicInputs"] = "String";
    }

    reg("StringLength", "String Length", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Length", PinDataType::Integer) },
        "", "Simple");

    reg("StringEquals", "String Equals", "Misc/String",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringEqualsIgnoreCase", "String Equals (Ignore Case)", "Misc/String",
        { MakePin("A", PinDataType::String), MakePin("B", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringContains", "String Contains", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Substring", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringStartsWith", "String Starts With", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Prefix", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringEndsWith", "String Ends With", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Suffix", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringReplace", "String Replace", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("From", PinDataType::String),
          MakePin("To", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    reg("StringToUpper", "String To Upper", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    reg("StringToLower", "String To Lower", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    reg("StringSubstring", "String Substring", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Start", PinDataType::Integer),
          MakePin("Count", PinDataType::Integer) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    reg("StringFind", "String Find", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Substring", PinDataType::String) },
        { MakePin("Index", PinDataType::Integer), MakePin("Found", PinDataType::Boolean) },
        "", "Simple");

    reg("StringSplit", "String Split", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Delimiter", PinDataType::String) },
        { MakePin("Array", PinDataType::Array), MakePin("Count", PinDataType::Integer) },
        "", "Simple");

    reg("StringTrimmed", "String Trimmed", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // FormatString — 格式化字符串 ({0}, {1}, ... 占位符)
    reg("FormatString", "Format String", "Misc/String",
        { MakePin("Format", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");
    {
        auto* d = const_cast<NodeDefinition*>(registry.getNodeDefinition("FormatString"));
        if (d) d->customProperties["dynamicInputs"] = "Any";
    }

    // StringJoin — 用分隔符连接数组中的字符串
    reg("StringJoin", "String Join", "Misc/String",
        { MakePin("Array", PinDataType::Array), MakePin("Separator", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // StringRepeat — 重复字符串 N 次
    reg("StringRepeat", "String Repeat", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Count", PinDataType::Integer) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // StringPadLeft — 左侧填充
    reg("StringPadLeft", "String Pad Left", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("TotalWidth", PinDataType::Integer), MakePin("PadChar", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // StringPadRight — 右侧填充
    reg("StringPadRight", "String Pad Right", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("TotalWidth", PinDataType::Integer), MakePin("PadChar", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // CharAt — 获取指定位置字符
    reg("CharAt", "Char At", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Index", PinDataType::Integer) },
        { MakePin("Char", PinDataType::String), MakePin("Valid", PinDataType::Boolean) },
        "", "Simple");

    // StringReverse — 反转字符串
    reg("StringReverse", "String Reverse", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // ── 新增字符串节点 ──────────────────────────────────────────────────────
    reg("StringCount", "String Count", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Substring", PinDataType::String) },
        { MakePin("Count", PinDataType::Integer) },
        "", "Simple");

    reg("StringIsEmpty", "String Is Empty", "Misc/String",
        { MakePin("String", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "", "Simple");

    reg("StringInsert", "String Insert", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Position", PinDataType::Integer), MakePin("Insert", PinDataType::String) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    reg("StringRemove", "String Remove", "Misc/String",
        { MakePin("String", PinDataType::String), MakePin("Position", PinDataType::Integer), MakePin("Length", PinDataType::Integer) },
        { MakePin("Result", PinDataType::String) },
        "", "Simple");

    // String.Regex — 正则表达式匹配与提取
    // Match:   在 String 中匹配 Pattern，Found=true 时 Match0..Match7 存各捕获组
    // FindAll: 找到所有匹配（无捕获组），结果存入 Matches(Array)
    // Replace: 将 Pattern 匹配替换为 Replacement（支持 $1 反向引用）
    reg("String.Regex", "String Regex", "Misc/String",
        {
            MakePin("String",      PinDataType::String),
            MakePin("Pattern",     PinDataType::String),
            MakePin("Replacement", PinDataType::String),  // Replace 模式用
            MakePinEnum("Mode",    "match,findall,replace", "match"),
        },
        {
            MakePin("Found",   PinDataType::Boolean),
            MakePin("Match0",  PinDataType::String),  // 整体匹配 / 第1组
            MakePin("Match1",  PinDataType::String),  // 第2捕获组
            MakePin("Match2",  PinDataType::String),
            MakePin("Match3",  PinDataType::String),
            MakePin("Matches", PinDataType::Array),   // findall 全部结果
            MakePin("Result",  PinDataType::String),  // replace 结果
        },
        "C08040", "Simple"); // 橙色，区别于普通字符串节点
}


} // namespace Runtime
} // namespace NodeEditor