// Runtime/nodedefs/BuiltinNodeDefs_Game.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Game() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Game(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    const char* BT_COLOR  = "3A7F4B"; // 森林绿
    const char* FSM_COLOR = "2E6DA4"; // 钢蓝

    // ── 行为树 ──────────────────────────────────────────────────────────────
    reg("BT.Sequence", "BT Sequence", "Game/BehaviorTree",
        { MakeFlowPin(""),
          MakePin("onChild0",PinDataType::Unknown,false), // 仅作占位，实际引脚动态
        },
        { MakeFlowPin("onChild0"), MakeFlowPin("onChild1"), MakeFlowPin("onChild2"),
          MakeFlowPin("onChild3"), MakeFlowPin("onChild4"),
          MakeFlowPin("onSuccess"), MakeFlowPin("onFailure"),
          MakePin("FailedIndex", PinDataType::Integer) },
        BT_COLOR);

    reg("BT.Selector", "BT Selector", "Game/BehaviorTree",
        { MakeFlowPin("") },
        { MakeFlowPin("onChild0"), MakeFlowPin("onChild1"), MakeFlowPin("onChild2"),
          MakeFlowPin("onChild3"), MakeFlowPin("onChild4"),
          MakeFlowPin("onSuccess"), MakeFlowPin("onFailure"),
          MakePin("SucceededIndex", PinDataType::Integer) },
        BT_COLOR);

    reg("BT.Parallel", "BT Parallel", "Game/BehaviorTree",
        { MakeFlowPin(""),
          MakePinEnum("Policy", "All,Any") },
        { MakeFlowPin("onChild0"), MakeFlowPin("onChild1"), MakeFlowPin("onChild2"),
          MakeFlowPin("onChild3"), MakeFlowPin("onChild4"),
          MakeFlowPin("onSuccess"), MakeFlowPin("onFailure"),
          MakePin("SuccessCount", PinDataType::Integer),
          MakePin("FailureCount", PinDataType::Integer) },
        BT_COLOR);

    reg("BT.Inverter", "BT Inverter", "Game/BehaviorTree",
        { MakeFlowPin("") },
        { MakeFlowPin("onChild"), MakeFlowPin("onSuccess"), MakeFlowPin("onFailure") },
        BT_COLOR);

    reg("BT.Repeat", "BT Repeat", "Game/BehaviorTree",
        { MakeFlowPin(""),
          MakePin("Count",        PinDataType::Integer),
          MakePin("StopOnFailure",PinDataType::Boolean) },
        { MakeFlowPin("onChild"), MakeFlowPin("onDone"), MakeFlowPin("onFailure"),
          MakePin("Iterations", PinDataType::Integer) },
        BT_COLOR);

    reg("BT.Cooldown", "BT Cooldown", "Game/BehaviorTree",
        { MakeFlowPin(""),
          MakePin("Duration", PinDataType::Float),
          MakePin("Key",      PinDataType::String) },
        { MakeFlowPin("onChild"), MakeFlowPin("onSuccess"),
          MakeFlowPin("onFailure"), MakeFlowPin("onCooldown") },
        BT_COLOR);

    reg("BT.Wait", "BT Wait", "Game/BehaviorTree",
        { MakeFlowPin(""), MakePin("Duration", PinDataType::Float) },
        { MakeFlowPin("onDone") },
        BT_COLOR);

    reg("BT.Condition", "BT Condition", "Game/BehaviorTree",
        { MakePin("Condition", PinDataType::Boolean),
          MakePin("Key",       PinDataType::String) },
        { MakeFlowPin("onSuccess"), MakeFlowPin("onFailure"),
          MakePin("Result", PinDataType::Boolean) },
        BT_COLOR, "Simple");

    reg("BT.SetBlackboard", "BT Set Blackboard", "Game/BehaviorTree",
        { MakeFlowPin(""), MakePin("Key", PinDataType::String), MakePin("Value", PinDataType::Any) },
        { MakeFlowPin("exec") },
        BT_COLOR);

    reg("BT.GetBlackboard", "BT Get Blackboard", "Game/BehaviorTree",
        { MakePin("Key", PinDataType::String) },
        { MakePin("Value", PinDataType::Any), MakePin("Found", PinDataType::Boolean) },
        BT_COLOR, "Simple");

    reg("BT.Log", "BT Log", "Game/BehaviorTree",
        { MakeFlowPin(""),
          MakePin("Message", PinDataType::String),
          MakePinEnum("Level", "info,warn,error") },
        { MakeFlowPin("exec") },
        BT_COLOR);

    reg("BT.AlwaysSuccess", "BT Always Success", "Game/BehaviorTree",
        { MakeFlowPin("") },
        { MakeFlowPin("onChild"), MakeFlowPin("onDone") },
        BT_COLOR);

    reg("BT.AlwaysFailure", "BT Always Failure", "Game/BehaviorTree",
        { MakeFlowPin("") },
        { MakeFlowPin("onChild"), MakeFlowPin("onDone") },
        BT_COLOR);

    // ── 状态机 ──────────────────────────────────────────────────────────────
    reg("FSM.State", "FSM State", "Game/StateMachine",
        { MakeFlowPin(""),
          MakePin("StateName",  PinDataType::String),
          MakePin("MachineId",  PinDataType::String) },
        { MakeFlowPin("onEnter"), MakeFlowPin("onUpdate"), MakeFlowPin("onExit"),
          MakePin("IsActive", PinDataType::Boolean) },
        FSM_COLOR);

    reg("FSM.Transition", "FSM Transition", "Game/StateMachine",
        { MakeFlowPin(""),
          MakePin("Condition", PinDataType::Boolean),
          MakePin("From",      PinDataType::String),
          MakePin("To",        PinDataType::String),
          MakePin("MachineId", PinDataType::String) },
        { MakeFlowPin("onTransitioned"), MakeFlowPin("onSkipped"),
          MakePin("Changed", PinDataType::Boolean) },
        FSM_COLOR);

    reg("FSM.GetState", "FSM Get State", "Game/StateMachine",
        { MakePin("MachineId", PinDataType::String) },
        { MakePin("State", PinDataType::String) },
        FSM_COLOR, "Simple");

    reg("FSM.SetState", "FSM Set State", "Game/StateMachine",
        { MakeFlowPin(""),
          MakePin("State",     PinDataType::String),
          MakePin("MachineId", PinDataType::String) },
        { MakeFlowPin("exec"), MakePin("PrevState", PinDataType::String) },
        FSM_COLOR);

    reg("FSM.IsInState", "FSM Is In State", "Game/StateMachine",
        { MakePin("State",     PinDataType::String),
          MakePin("MachineId", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        FSM_COLOR, "Simple");
}

// ============================================================================
// Save — 存档系统 Save.*
// ============================================================================

} // namespace Runtime
} // namespace NodeEditor