// Runtime/nodedefs/BuiltinNodeDefs_Time.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Time() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Time(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    // GetTime — 获取当前时间（秒，自 epoch）
    reg("GetTime", "Get Time", "Time",
        {},
        { MakePin("Seconds", PinDataType::Float) },
        "40C0C0", "Simple");

    // DeltaTime — 获取帧间隔时间
    reg("DeltaTime", "Delta Time", "Time",
        {},
        { MakePin("Seconds", PinDataType::Float) },
        "40C0C0", "Simple");

    // TimeSince — 计算距某时间戳过去了多少秒
    reg("TimeSince", "Time Since", "Time",
        { MakePin("Timestamp", PinDataType::Float) },
        { MakePin("Elapsed", PinDataType::Float) },
        "40C0C0", "Simple");

	// BreakTime — 将秒数分解为时分秒
	reg("BreakTime", "Break Time", "Time",
		{ MakePin("Seconds", PinDataType::Float) },
		{ MakePin("Year", PinDataType::Integer),
          MakePin("Mon", PinDataType::Integer),
          MakePin("Day", PinDataType::Integer),
          MakePin("WDay", PinDataType::Integer),
          MakePin("Hour", PinDataType::Integer),
          MakePin("Min", PinDataType::Integer),
          MakePin("Sec", PinDataType::Integer),
          MakePin("MSec", PinDataType::Integer)
        },
		"40C0C0", "Simple");

    // FormatTime — 格式化时间为可读字符串
    reg("FormatTime", "Format Time", "Time",
        { MakePin("Seconds", PinDataType::Float), MakePin("Format", PinDataType::String) },
        { MakePin("Formatted", PinDataType::String) },
        "40C0C0", "Simple");

    // TimerInfo — 查询计时器状态
    reg("TimerInfo", "Timer Info", "Time",
        { MakePin("TimerHandle", PinDataType::Integer) },
        { MakePin("IsActive", PinDataType::Boolean), MakePin("IsPaused", PinDataType::Boolean),
          MakePin("Elapsed", PinDataType::Float), MakePin("Remaining", PinDataType::Float) },
        "40C0C0", "Simple");
}


} // namespace Runtime
} // namespace NodeEditor