// Runtime/nodedefs/BuiltinNodeDefs_Data.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_Data() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;
void RegisterNodeDefs_Data(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

    // ToJSON — 将值序列化为 JSON 字符串
    reg("ToJSON", "To JSON", "Data",
        { MakePin("Value", PinDataType::Any) },
        { MakePin("JSON", PinDataType::String) },
        "C080F8", "Simple");

    // FromJSON — 从 JSON 字符串解析值
    reg("FromJSON", "From JSON", "Data",
        { MakePin("JSON", PinDataType::String) },
        { MakePin("Value", PinDataType::Any), MakePin("Valid", PinDataType::Boolean) },
        "C080F8", "Simple");

    // HasKey — 检查 JSON 对象中是否含有指定键
    reg("HasKey", "Has Key", "Data",
        { MakePin("JSON", PinDataType::String), MakePin("Key", PinDataType::String) },
        { MakePin("Result", PinDataType::Boolean) },
        "C080F8", "Simple");

    // GetField — 从 JSON 字符串中获取指定字段
    reg("GetField", "Get Field", "Data",
        { MakePin("JSON", PinDataType::String), MakePin("Key", PinDataType::String) },
        { MakePin("Value", PinDataType::String), MakePin("Found", PinDataType::Boolean) },
        "C080F8", "Simple");

    // ArrayToString — 将数组转为字符串表示
    reg("ArrayToString", "Array to String", "Data",
        { MakePin("Array", PinDataType::Array) },
        { MakePin("String", PinDataType::String) },
        "C080F8", "Simple");
}


} // namespace Runtime
} // namespace NodeEditor