// Runtime/exporter/BlueprintExporter_EditorExport.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the EditorExport section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;
std::string JsonBlueprintExporter::exportEditorToString(const BlueprintData& data, const ExportOptions& options) const
{
    std::ostringstream oss;
    int indentLevel = 0;
    bool pretty = options.prettyPrint;
    
    auto writeIndent = [&]() {
        if (pretty) oss << indentJson(indentLevel, options.indent);
    };
    
    auto writeNewline = [&]() {
        if (pretty) oss << "\n";
    };
    
    // 开始根对象
    oss << "{";
    writeNewline();
    indentLevel++;
    
    // 文件类型标识
    writeIndent();
    oss << "\"fileType\": \"editor\",";
    writeNewline();
    
    // ================================================================
    // 元数据附加（author、时间戳）
    // ================================================================
    writeIndent();
    oss << "\"metadata\": {";
    writeNewline();
    indentLevel++;
    
    writeIndent();
    oss << "\"author\": \"" << escapeJson(data.metadata.author) << "\",";
    writeNewline();
    
    writeIndent();
    oss << "\"createdAt\": \"" << escapeJson(data.metadata.createdAt) << "\",";
    writeNewline();
    
    writeIndent();
    oss << "\"updatedAt\": \"" << escapeJson(data.metadata.updatedAt) << "\"";
    
    writeNewline();
    indentLevel--;
    writeIndent();
    oss << "},";
    writeNewline();
    
    // ================================================================
    // 节点编辑器数据（position/size/isCollapsed），通过 nodeId 关联
    // ================================================================
    writeIndent();
    oss << "\"nodes\": [";
    writeNewline();
    indentLevel++;
    
    bool firstNode = true;
    for (size_t i = 0; i < data.nodes.size(); ++i)
    {
        const auto& node = data.nodes[i];
        
        if (options.nodeFilter && !options.nodeFilter(node))
            continue;
        
        if (!firstNode) { oss << ","; writeNewline(); }
        firstNode = false;
        
        writeIndent();
        oss << "{";
        writeNewline();
        indentLevel++;
        
        // 节点 ID（用于与 Runtime 文件中的节点关联）
        writeIndent();
        oss << "\"id\": " << node.id << ",";
        writeNewline();
        
        // 位置
        writeIndent();
        oss << "\"position\": {";
        writeNewline();
        indentLevel++;
        writeIndent(); oss << "\"x\": " << node.position.x << ","; writeNewline();
        writeIndent(); oss << "\"y\": " << node.position.y; writeNewline();
        indentLevel--;
        writeIndent();
        oss << "},";
        writeNewline();
        
        // 尺寸
        writeIndent();
        oss << "\"size\": {";
        writeNewline();
        indentLevel++;
        writeIndent(); oss << "\"width\": " << node.size.width << ","; writeNewline();
        writeIndent(); oss << "\"height\": " << node.size.height; writeNewline();
        indentLevel--;
        writeIndent();
        oss << "},";
        writeNewline();
        
        // 折叠状态
        writeIndent();
        oss << "\"isCollapsed\": " << (node.isCollapsed ? "true" : "false");
        
        writeNewline();
        indentLevel--;
        writeIndent();
        oss << "}";
    }
    
    writeNewline();
    indentLevel--;
    writeIndent();
    oss << "]";
    
    // ================================================================
    // 变量附加信息（category/tooltip），通过 name 关联
    // ================================================================
    if (!data.variables.empty())
    {
        // 检查是否有非空的 category 或 tooltip
        bool hasEditorVarData = false;
        for (const auto& var : data.variables)
        {
            if (!var.category.empty() || !var.tooltip.empty())
            {
                hasEditorVarData = true;
                break;
            }
        }
        
        if (hasEditorVarData)
        {
            oss << ","; writeNewline();
            
            writeIndent();
            oss << "\"variables\": [";
            writeNewline();
            indentLevel++;
            
            bool firstVar = true;
            for (size_t i = 0; i < data.variables.size(); ++i)
            {
                const auto& var = data.variables[i];
                if (var.category.empty() && var.tooltip.empty())
                    continue;
                
                if (!firstVar) { oss << ","; writeNewline(); }
                firstVar = false;
                
                writeIndent();
                oss << "{";
                writeNewline();
                indentLevel++;
                
                writeIndent(); oss << "\"name\": \"" << escapeJson(var.name) << "\","; writeNewline();
                writeIndent(); oss << "\"category\": \"" << escapeJson(var.category) << "\","; writeNewline();
                writeIndent(); oss << "\"tooltip\": \"" << escapeJson(var.tooltip) << "\""; writeNewline();
                
                indentLevel--;
                writeIndent();
                oss << "}";
            }
            
            writeNewline();
            indentLevel--;
            writeIndent();
            oss << "]";
        }
    }
    
    // ================================================================
    // 注释
    // ================================================================
    if (!data.comments.empty())
    {
        oss << ","; writeNewline();
        
        writeIndent();
        oss << "\"comments\": [";
        writeNewline();
        indentLevel++;
        
        for (size_t i = 0; i < data.comments.size(); ++i)
        {
            const auto& comment = data.comments[i];
            
            writeIndent();
            oss << "{";
            writeNewline();
            indentLevel++;
            
            writeIndent(); oss << "\"id\": \"" << escapeJson(comment.id) << "\","; writeNewline();
            writeIndent(); oss << "\"text\": \"" << escapeJson(comment.text) << "\","; writeNewline();
            writeIndent(); oss << "\"position\": { \"x\": " << comment.position.x << ", \"y\": " << comment.position.y << " },"; writeNewline();
            writeIndent(); oss << "\"size\": { \"width\": " << comment.size.width << ", \"height\": " << comment.size.height << " },"; writeNewline();
            writeIndent(); oss << "\"color\": \"" << escapeJson(comment.color) << "\","; writeNewline();
            writeIndent(); oss << "\"alpha\": " << comment.alpha; writeNewline();
            
            indentLevel--;
            writeIndent();
            oss << "}";
            if (i < data.comments.size() - 1) oss << ",";
            writeNewline();
        }
        
        indentLevel--;
        writeIndent();
        oss << "]";
    }
    
    // ================================================================
    // 视图信息
    // ================================================================
    {
        oss << ","; writeNewline();
        
        writeIndent();
        oss << "\"viewInfo\": {";
        writeNewline();
        indentLevel++;
        
        writeIndent(); oss << "\"viewPosition\": { \"x\": " << data.viewInfo.viewPosition.x << ", \"y\": " << data.viewInfo.viewPosition.y << " },"; writeNewline();
        writeIndent(); oss << "\"viewScale\": " << data.viewInfo.viewScale; writeNewline();
        
        indentLevel--;
        writeIndent();
        oss << "}";
    }
    
    // 结束根对象
    writeNewline();
    indentLevel--;
    writeIndent();
    oss << "}";
    
    return oss.str();
}


// ============================================================================
// JsonBlueprintExporter — 编辑器单文件导出
// ============================================================================

EditorExportResult JsonBlueprintExporter::exportEditorFiles(const BlueprintData& data,
    const std::string& runtimeFilePath,
    const ExportOptions& options) const
{
    EditorExportResult result;

#ifndef __EMSCRIPTEN__
    try
    {
#endif
        std::string runtimeJson = exportRuntimeToString(data, options);
        std::string editorJson  = exportEditorToString(data, options);

        // 单文件格式：{ "runtime": {...}, "editor": {...} }
        std::ostringstream merged;
        bool pretty = options.prettyPrint;
        const std::string nl  = pretty ? "\n" : "";
        const std::string ind = pretty ? "    " : "";

        merged << "{" << nl;
        merged << ind << "\"runtime\": " << runtimeJson << "," << nl;
        merged << ind << "\"editor\": "  << editorJson  << nl;
        merged << "}" << nl;

        std::string mergedStr = merged.str();

        std::string errorMsg;
        if (!m_fileSystem->WriteFile(runtimeFilePath, mergedStr, errorMsg))
        {
            result.errorMessage = "Write failed: " + errorMsg;
            return result;
        }

        result.success      = true;
        result.filePath     = runtimeFilePath;
        result.bytesWritten = mergedStr.size();

#ifndef __EMSCRIPTEN__
    }
    catch (const std::exception& e)
    {
        result.errorMessage = std::string("Exception: ") + e.what();
    }
#endif

    return result;
}

} // namespace Runtime
} // namespace NodeEditor