// Runtime/exporter/BlueprintExporter_RuntimeImport.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the RuntimeImport section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;
ImportResult JsonBlueprintExporter::importRuntimeFromString(const std::string& content, const ImportOptions& options) const
{
    ImportResult result;
    result.bytesRead = content.size();

    // 使用 crude_json 解析
    crude_json::value root = crude_json::value::parse(content);
    if (root.is_discarded())
    {
        result.errorMessage = "JSON parse error";
        return result;
    }

    if (root.type() != crude_json::type_t::object)
    {
        result.errorMessage = "Root JSON element must be an object";
        return result;
    }

    auto& rootObj = root;

    // 自动检测单文件新格式：顶层包含 "runtime" 子对象
    if (rootObj.contains("runtime") && rootObj["runtime"].type() == crude_json::type_t::object)
    {
        std::string runtimeJson = rootObj["runtime"].dump();
        // 先加载 runtime 数据
        result = importRuntimeFromString(runtimeJson, options);
        result.bytesRead = content.size();
        if (!result.success)
            return result;

        // 若顶层还有 "editor" 字段，合并编辑器附加数据（节点位置等）
        if (rootObj.contains("editor") && rootObj["editor"].type() == crude_json::type_t::object)
        {
            std::string editorJson = rootObj["editor"].dump();
            ImportResult merged = importEditorFromStrings(runtimeJson, editorJson, options);
            if (merged.success)
            {
                merged.bytesRead = content.size();
                return merged;
            }
            // 合并失败时仍返回 runtime 数据（editor 数据丢失但不致命）
            result.warnings.push_back("Editor data merge failed: " + merged.errorMessage);
        }
        return result;
    }

    // ---- 辅助别名（使用文件级辅助函数，通过 lambda 保留默认参数）----
    auto getNumber = [](const crude_json::value& obj, const char* key, double defaultVal = 0.0) { return getJsonNumber(obj, key, defaultVal); };
    auto getString = [](const crude_json::value& obj, const char* key) { return getJsonString(obj, key); };
    auto getBool   = [](const crude_json::value& obj, const char* key, bool defaultVal = false) { return getJsonBool(obj, key, defaultVal); };

    // ---- 解析元数据 ----
    if (rootObj.contains("metadata") && rootObj["metadata"].type() == crude_json::type_t::object)
    {
        auto& meta = rootObj["metadata"];
        result.data.metadata.schemaVersion = static_cast<int>(getNumber(meta, "schemaVersion", 0));
        result.data.metadata.blueprintClass = static_cast<BlueprintClass>(
            static_cast<int>(getNumber(meta, "blueprintClass", 0)));
        result.data.metadata.name        = getString(meta, "name");
        result.data.metadata.description  = getString(meta, "description");
        result.data.metadata.version      = getString(meta, "version");
        result.data.metadata.author       = getString(meta, "author");
        result.data.metadata.createdAt    = getString(meta, "createdAt");
        result.data.metadata.updatedAt    = getString(meta, "updatedAt");

        if (meta.contains("tags") && meta["tags"].type() == crude_json::type_t::array)
        {
            for (auto& tag : meta["tags"].get<crude_json::array>())
            {
                if (tag.type() == crude_json::type_t::string)
                    result.data.metadata.tags.push_back(tag.get<std::string>());
            }
        }

        // dependencies：加载时按序读取（Runtime 用来决定 Library 加载顺序）
        if (meta.contains("dependencies") && meta["dependencies"].type() == crude_json::type_t::array)
        {
            for (auto& dep : meta["dependencies"].get<crude_json::array>())
            {
                if (dep.type() == crude_json::type_t::string)
                    result.data.metadata.dependencies.push_back(dep.get<std::string>());
            }
        }
    }

    // ---- Schema 版本检查 ----
    {
        int fileSchema = result.data.metadata.schemaVersion;
        if (fileSchema > BLUEPRINT_CURRENT_SCHEMA_VERSION)
        {
            result.errorMessage = "Blueprint file requires schema version "
                + std::to_string(fileSchema)
                + ", but this runtime only supports up to version "
                + std::to_string(BLUEPRINT_CURRENT_SCHEMA_VERSION)
                + ". Please update the application.";
            return result;
        }
        if (fileSchema > 0 && fileSchema < BLUEPRINT_CURRENT_SCHEMA_VERSION)
        {
            result.warnings.push_back(
                "Blueprint file uses older schema version "
                + std::to_string(fileSchema)
                + " (current: " + std::to_string(BLUEPRINT_CURRENT_SCHEMA_VERSION)
                + "). Data will be migrated automatically.");
        }
        // fileSchema == 0 表示老文件没有 schemaVersion 字段，视为版本 1
        if (fileSchema == 0)
        {
            result.data.metadata.schemaVersion = 1;
        }
    }

    // ---- 解析节点 ----
    if (rootObj.contains("nodes") && rootObj["nodes"].type() == crude_json::type_t::array)
    {
        for (auto& nodeJson : rootObj["nodes"].get<crude_json::array>())
        {
            if (nodeJson.type() != crude_json::type_t::object) continue;

            NodeInstance node;
            node.id                = static_cast<NodeId>(getNumber(nodeJson, "id"));
            node.definitionId      = getString(nodeJson, "definitionId");
            node.definitionVersion = static_cast<int>(getNumber(nodeJson, "definitionVersion", 1));
            node.name              = getString(nodeJson, "name");
            node.isEnabled         = getBool(nodeJson, "isEnabled", true);
            node.isCollapsed       = getBool(nodeJson, "isCollapsed", false);

            // 位置（编辑器数据，单文件格式从 editor 段读取；此处兼容直接在 runtime 段写入的场景）
            if (nodeJson.contains("position") && nodeJson["position"].type() == crude_json::type_t::object)
            {
                auto& pos = nodeJson["position"];
                node.position.x = static_cast<float>(getNumber(pos, "x"));
                node.position.y = static_cast<float>(getNumber(pos, "y"));
            }

            // 尺寸
            if (nodeJson.contains("size") && nodeJson["size"].type() == crude_json::type_t::object)
            {
                auto& sz = nodeJson["size"];
                node.size.width  = static_cast<float>(getNumber(sz, "width"));
                node.size.height = static_cast<float>(getNumber(sz, "height"));
            }

            // 引脚
            if (nodeJson.contains("pins") && nodeJson["pins"].type() == crude_json::type_t::array)
            {
                for (auto& pinJson : nodeJson["pins"].get<crude_json::array>())
                {
                    if (pinJson.type() != crude_json::type_t::object) continue;

                    PinInfo pin;
                    pin.id       = static_cast<PinId>(getNumber(pinJson, "id"));
                    pin.name     = getString(pinJson, "name");  // 缺失时返回空字符串（默认值）
                    pin.dataType = static_cast<PinDataType>(static_cast<int>(getNumber(pinJson, "dataType")));

                    // kind: int 格式（0=Input, 1=Output）
                    if (pinJson.contains("kind") && pinJson["kind"].type() == crude_json::type_t::number)
                        pin.kind = (static_cast<int>(pinJson["kind"].get<double>()) == 1) ? PinKind::Output : PinKind::Input;

                    pin.allowMultiple = getBool(pinJson, "allowMultiple", false);
                    pin.isExec        = getBool(pinJson, "isExec", false);

                    if (pinJson.contains("defaultValue"))
                    {
                        pin.defaultValue = jsonToVariant(pinJson["defaultValue"].dump(), pin.dataType);
                    }

                    node.pins.push_back(std::move(pin));
                }
            }

            // 自定义属性
            if (nodeJson.contains("customProperties") && nodeJson["customProperties"].type() == crude_json::type_t::object)
            {
                for (auto& kv : nodeJson["customProperties"].get<crude_json::object>())
                {
                    if (kv.second.type() == crude_json::type_t::string)
                        node.customProperties[kv.first] = kv.second.get<std::string>();
                }
            }

            // 节点数据
            if (nodeJson.contains("nodeData") && nodeJson["nodeData"].type() == crude_json::type_t::object)
            {
                for (auto& kv : nodeJson["nodeData"].get<crude_json::object>())
                {
                    auto& val = kv.second;
                    Variant v;
                    if (val.type() == crude_json::type_t::boolean)
                    {
                        v = Variant(val.get<bool>());
                    }
                    else if (val.type() == crude_json::type_t::number)
                    {
                        v = Variant(val.get<double>());
                    }
                    else if (val.type() == crude_json::type_t::string)
                    {
                        v = Variant(val.get<std::string>());
                    }
                    node.nodeData[kv.first] = v;
                }
            }

            result.data.nodes.push_back(std::move(node));
        }
    }

    // ---- 解析链接 ----
    if (rootObj.contains("links") && rootObj["links"].type() == crude_json::type_t::array)
    {
        for (auto& linkJson : rootObj["links"].get<crude_json::array>())
        {
            if (linkJson.type() != crude_json::type_t::object) continue;

            LinkInstance link;
            link.id         = static_cast<LinkId>(getNumber(linkJson, "id"));
            link.startPinId = static_cast<PinId>(getNumber(linkJson, "startPinId"));
            link.endPinId   = static_cast<PinId>(getNumber(linkJson, "endPinId"));
            link.isEnabled  = getBool(linkJson, "isEnabled", true);

            result.data.links.push_back(std::move(link));
        }
    }

    // ---- 解析变量 ----
    if (rootObj.contains("variables") && rootObj["variables"].type() == crude_json::type_t::array)
    {
        for (auto& varJson : rootObj["variables"].get<crude_json::array>())
        {
            if (varJson.type() != crude_json::type_t::object) continue;

            VariableDefinition var;
            var.name      = getString(varJson, "name");
            var.isExposed = getBool(varJson, "isExposed", true);
            var.category  = getString(varJson, "category");
            var.tooltip   = getString(varJson, "tooltip");

            // 向后兼容逻辑
            // 有 containerType 字段 → 新格式，直接用
            // 无 containerType 字段 → 旧格式，按旧枚举值解释 dataType
            bool hasContainerType = varJson.contains("containerType")
                                 && varJson["containerType"].type() == crude_json::type_t::number;
            int rawDataType = static_cast<int>(getNumber(varJson, "dataType"));
            if (hasContainerType)
            {
                var.dataType      = static_cast<PinDataType>(rawDataType);
                var.containerType = static_cast<ContainerType>(static_cast<int>(getNumber(varJson, "containerType")));
                var.itemType      = static_cast<PinDataType>(static_cast<int>(getNumber(varJson, "itemType")));
                var.mapKeyType    = static_cast<PinDataType>(static_cast<int>(getNumber(varJson, "mapKeyType")));
            }
            else
            {
                // 旧枚举：Any=8, Custom=9  新枚举：Set=8, Any=9, Custom=10
                if (rawDataType == 6)       // Array
                {
                    var.dataType      = PinDataType::Array;
                    var.containerType = ContainerType::Array;
                    var.itemType      = PinDataType::Any;
                    var.mapKeyType    = PinDataType::String;
                }
                else if (rawDataType == 7)  // Map
                {
                    var.dataType      = PinDataType::Map;
                    var.containerType = ContainerType::Map;
                    var.itemType      = PinDataType::Any;
                    var.mapKeyType    = PinDataType::String;
                }
                else if (rawDataType == 8)  // 旧 Any（新 Set）
                {
                    var.dataType      = PinDataType::Any;
                    var.containerType = ContainerType::Single;
                    var.itemType      = PinDataType::Any;
                    var.mapKeyType    = PinDataType::String;
                }
                else
                {
                    var.dataType      = static_cast<PinDataType>(rawDataType);
                    var.containerType = ContainerType::Single;
                    var.itemType      = var.dataType;   // Single 时 itemType == dataType
                    var.mapKeyType    = PinDataType::String;
                }
            }

            if (varJson.contains("defaultValue"))
            {
                var.defaultValue = jsonToVariant(varJson["defaultValue"].dump(), var.dataType);
            }

            result.data.variables.push_back(std::move(var));
        }
    }

    // ---- 解析函数定义 ----
    if (rootObj.contains("functions") && rootObj["functions"].type() == crude_json::type_t::array)
    {
        for (auto& funcJson : rootObj["functions"].get<crude_json::array>())
        {
            if (funcJson.type() != crude_json::type_t::object) continue;

            FunctionDefinition func;
            func.id          = getString(funcJson, "id");
            func.name        = getString(funcJson, "name");
            func.category    = getString(funcJson, "category");
            func.description = getString(funcJson, "description");
            func.isPublic    = getBool(funcJson, "isPublic", true);

            // inputs
            if (funcJson.contains("inputs") && funcJson["inputs"].type() == crude_json::type_t::array)
            {
                for (auto& inpJson : funcJson["inputs"].get<crude_json::array>())
                {
                    if (inpJson.type() != crude_json::type_t::object) continue;
                    VariableDefinition vd;
                    vd.name = getString(inpJson, "name");

                    bool hasContainerType2 = inpJson.contains("containerType")
                                          && inpJson["containerType"].type() == crude_json::type_t::number;
                    int rawDt2 = static_cast<int>(getNumber(inpJson, "dataType"));
                    if (hasContainerType2)
                    {
                        vd.dataType      = static_cast<PinDataType>(rawDt2);
                        vd.containerType = static_cast<ContainerType>(static_cast<int>(getNumber(inpJson, "containerType")));
                        vd.itemType      = static_cast<PinDataType>(static_cast<int>(getNumber(inpJson, "itemType")));
                        vd.mapKeyType    = static_cast<PinDataType>(static_cast<int>(getNumber(inpJson, "mapKeyType")));
                    }
                    else
                    {
                        if (rawDt2 == 6)      { vd.dataType = PinDataType::Array; vd.containerType = ContainerType::Array; vd.itemType = PinDataType::Any; }
                        else if (rawDt2 == 7) { vd.dataType = PinDataType::Map;   vd.containerType = ContainerType::Map;   vd.itemType = PinDataType::Any; vd.mapKeyType = PinDataType::String; }
                        else if (rawDt2 == 8) { vd.dataType = PinDataType::Any;   vd.containerType = ContainerType::Single; vd.itemType = PinDataType::Any; }
                        else                  { vd.dataType = static_cast<PinDataType>(rawDt2); vd.containerType = ContainerType::Single; vd.itemType = vd.dataType; }
                    }
                    func.inputs.push_back(std::move(vd));
                }
            }
            // outputs
            if (funcJson.contains("outputs") && funcJson["outputs"].type() == crude_json::type_t::array)
            {
                for (auto& outJson : funcJson["outputs"].get<crude_json::array>())
                {
                    if (outJson.type() != crude_json::type_t::object) continue;
                    VariableDefinition vd;
                    vd.name = getString(outJson, "name");

                    bool hasContainerType3 = outJson.contains("containerType")
                                          && outJson["containerType"].type() == crude_json::type_t::number;
                    int rawDt3 = static_cast<int>(getNumber(outJson, "dataType"));
                    if (hasContainerType3)
                    {
                        vd.dataType      = static_cast<PinDataType>(rawDt3);
                        vd.containerType = static_cast<ContainerType>(static_cast<int>(getNumber(outJson, "containerType")));
                        vd.itemType      = static_cast<PinDataType>(static_cast<int>(getNumber(outJson, "itemType")));
                        vd.mapKeyType    = static_cast<PinDataType>(static_cast<int>(getNumber(outJson, "mapKeyType")));
                    }
                    else
                    {
                        if (rawDt3 == 6)      { vd.dataType = PinDataType::Array; vd.containerType = ContainerType::Array; vd.itemType = PinDataType::Any; }
                        else if (rawDt3 == 7) { vd.dataType = PinDataType::Map;   vd.containerType = ContainerType::Map;   vd.itemType = PinDataType::Any; vd.mapKeyType = PinDataType::String; }
                        else if (rawDt3 == 8) { vd.dataType = PinDataType::Any;   vd.containerType = ContainerType::Single; vd.itemType = PinDataType::Any; }
                        else                  { vd.dataType = static_cast<PinDataType>(rawDt3); vd.containerType = ContainerType::Single; vd.itemType = vd.dataType; }
                    }
                    func.outputs.push_back(std::move(vd));
                }
            }
            // nodes (sub-graph)
            if (funcJson.contains("nodes") && funcJson["nodes"].type() == crude_json::type_t::array)
            {
                for (auto& ndJson : funcJson["nodes"].get<crude_json::array>())
                {
                    if (ndJson.type() != crude_json::type_t::object) continue;
                    NodeInstance nd;
                    nd.id           = static_cast<NodeId>(getNumber(ndJson, "id"));
                    nd.definitionId = getString(ndJson, "definitionId");
                    nd.name         = getString(ndJson, "name");
                    // 反序列化完整 pin 数据（新格式；旧格式无 pins 字段，跳过兼容）
                    if (ndJson.contains("pins") && ndJson["pins"].type() == crude_json::type_t::array)
                    {
                        for (auto& pinJson : ndJson["pins"].get<crude_json::array>())
                        {
                            if (pinJson.type() != crude_json::type_t::object) continue;
                            PinInfo pin;
                            pin.id        = static_cast<PinId>(getNumber(pinJson, "id"));
                            pin.kind      = static_cast<PinKind>(static_cast<int>(getNumber(pinJson, "kind")));
                            pin.dataType  = static_cast<PinDataType>(static_cast<int>(getNumber(pinJson, "dataType")));
                            pin.isExec    = pinJson.contains("isExec") && pinJson["isExec"].type() == crude_json::type_t::boolean
                                            ? pinJson["isExec"].get<bool>() : false;
                            pin.name      = getString(pinJson, "name");
                            if (pinJson.contains("defaultValue"))
                                pin.defaultValue = jsonToVariant(pinJson["defaultValue"].dump(), pin.dataType);
                            nd.pins.push_back(std::move(pin));
                        }
                    }
                    func.nodes.push_back(std::move(nd));
                }
            }
            // links
            if (funcJson.contains("links") && funcJson["links"].type() == crude_json::type_t::array)
            {
                for (auto& lkJson : funcJson["links"].get<crude_json::array>())
                {
                    if (lkJson.type() != crude_json::type_t::object) continue;
                    LinkInstance lk;
                    lk.id         = static_cast<LinkId>(getNumber(lkJson, "id"));
                    lk.startPinId = static_cast<PinId>(getNumber(lkJson, "startPinId"));
                    lk.endPinId   = static_cast<PinId>(getNumber(lkJson, "endPinId"));
                    func.links.push_back(std::move(lk));
                }
            }

            result.data.functions.push_back(std::move(func));
        }
    }

    // ---- 解析注释（兼容老格式） ----
    if (rootObj.contains("comments") && rootObj["comments"].type() == crude_json::type_t::array)
    {
        for (auto& cmtJson : rootObj["comments"].get<crude_json::array>())
        {
            if (cmtJson.type() != crude_json::type_t::object) continue;

            CommentRegion cmt;
            cmt.id    = getString(cmtJson, "id");
            cmt.text  = getString(cmtJson, "text");
            cmt.color = getString(cmtJson, "color");
            cmt.alpha = static_cast<float>(getNumber(cmtJson, "alpha", 0.5));

            if (cmtJson.contains("position") && cmtJson["position"].type() == crude_json::type_t::object)
            {
                cmt.position.x = static_cast<float>(getNumber(cmtJson["position"], "x"));
                cmt.position.y = static_cast<float>(getNumber(cmtJson["position"], "y"));
            }
            if (cmtJson.contains("size") && cmtJson["size"].type() == crude_json::type_t::object)
            {
                cmt.size.width  = static_cast<float>(getNumber(cmtJson["size"], "width"));
                cmt.size.height = static_cast<float>(getNumber(cmtJson["size"], "height"));
            }

            result.data.comments.push_back(std::move(cmt));
        }
    }

    // ---- 解析视图信息（兼容老格式） ----
    if (rootObj.contains("viewInfo") && rootObj["viewInfo"].type() == crude_json::type_t::object)
    {
        auto& viewJson = rootObj["viewInfo"];
        if (viewJson.contains("viewPosition") && viewJson["viewPosition"].type() == crude_json::type_t::object)
        {
            result.data.viewInfo.viewPosition.x = static_cast<float>(getNumber(viewJson["viewPosition"], "x"));
            result.data.viewInfo.viewPosition.y = static_cast<float>(getNumber(viewJson["viewPosition"], "y"));
        }
        result.data.viewInfo.viewScale = static_cast<float>(getNumber(viewJson, "viewScale", 1.0));
    }

    // ---- 验证 ----
    if (options.validateOnLoad)
    {
        std::vector<std::string> errors;
        if (!validate(result.data, errors))
        {
            for (auto& e : errors)
                result.warnings.push_back(e);
        }
    }

    // ---- 修复断开的链接 ----
    if (options.repairBrokenLinks)
    {
        std::unordered_set<PinId> pinIds;
        for (const auto& node : result.data.nodes)
        {
            for (const auto& pin : node.pins)
            {
                pinIds.insert(pin.id);
            }
        }

        auto& links = result.data.links;
        links.erase(
            std::remove_if(links.begin(), links.end(), [&pinIds](const LinkInstance& link) {
                return pinIds.find(link.startPinId) == pinIds.end() ||
                       pinIds.find(link.endPinId) == pinIds.end();
            }),
            links.end()
        );
    }

    // ---- Schema 迁移（在所有数据解析完成后执行）----
    {
        int fileSchema = result.data.metadata.schemaVersion;
        if (fileSchema < BLUEPRINT_CURRENT_SCHEMA_VERSION)
            ApplySchemaMigrations(result.data, fileSchema);
    }

    result.success = true;
    return result;
}

ImportResult JsonBlueprintExporter::importRuntimeFromFile(const std::string& filePath, const ImportOptions& options) const
{
    ImportResult result;
    
#ifndef __EMSCRIPTEN__
    try
    {
        std::string errorMsg;
        std::string content;
        if (!m_fileSystem->ReadFile(filePath, content, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }
        
        result = importRuntimeFromString(content, options);
    }
    catch (const std::exception& e)
    {
        result.errorMessage = std::string("Exception: ") + e.what();
    }
#else
    {
        std::string errorMsg;
        std::string content;
        if (!m_fileSystem->ReadFile(filePath, content, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }
        
        result = importRuntimeFromString(content, options);
    }
#endif
    
    return result;
}

ImportMetaResult JsonBlueprintExporter::importMetadataFromFile(const std::string& filePath, const ImportOptions& options) const
{
    ImportMetaResult result;
#ifndef __EMSCRIPTEN__
    try
    {
        std::string errorMsg;
        std::string content;
        if (!m_fileSystem->ReadFile(filePath, content, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }

        result = importMetadataFromString(content, options);
    }
    catch (const std::exception& e)
    {
        result.errorMessage = std::string("Exception: ") + e.what();
    }
#else
    {
        std::string errorMsg;
        std::string content;
        if (!m_fileSystem->ReadFile(filePath, content, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }

        result = importMetadataFromString(content, options);
    }
#endif

    return result;
}

ImportMetaResult JsonBlueprintExporter::importMetadataFromString(const std::string& content, const ImportOptions& options) const
{
    ImportMetaResult result;

    // 使用 crude_json 解析
    crude_json::value root = crude_json::value::parse(content);
    if (root.is_discarded())
    {
        result.errorMessage = "JSON parse error";
        return result;
    }

    if (root.type() != crude_json::type_t::object)
    {
        result.errorMessage = "Root JSON element must be an object";
        return result;
    }

    auto& rootObj = root;

    // ---- 辅助别名（使用文件级辅助函数，通过 lambda 保留默认参数）----
    auto getNumber = [](const crude_json::value& obj, const char* key, double defaultVal = 0.0) { return getJsonNumber(obj, key, defaultVal); };
    auto getString = [](const crude_json::value& obj, const char* key) { return getJsonString(obj, key); };
    auto getBool = [](const crude_json::value& obj, const char* key, bool defaultVal = false) { return getJsonBool(obj, key, defaultVal); };

    // ---- 解析元数据 ----
    if (rootObj.contains("metadata") && rootObj["metadata"].type() == crude_json::type_t::object)
    {
        auto& meta = rootObj["metadata"];
        result.metadata.schemaVersion = static_cast<int>(getNumber(meta, "schemaVersion", 0));
        result.metadata.blueprintClass = static_cast<BlueprintClass>(
            static_cast<int>(getNumber(meta, "blueprintClass", 0)));
        result.metadata.name = getString(meta, "name");
        result.metadata.description = getString(meta, "description");
        result.metadata.version = getString(meta, "version");
        result.metadata.author = getString(meta, "author");
        result.metadata.createdAt = getString(meta, "createdAt");
        result.metadata.updatedAt = getString(meta, "updatedAt");

        if (meta.contains("tags") && meta["tags"].type() == crude_json::type_t::array)
        {
            for (auto& tag : meta["tags"].get<crude_json::array>())
            {
                if (tag.type() == crude_json::type_t::string)
                    result.metadata.tags.push_back(tag.get<std::string>());
            }
        }

        // dependencies：加载时按序读取（Runtime 用来决定 Library 加载顺序）
        if (meta.contains("dependencies") && meta["dependencies"].type() == crude_json::type_t::array)
        {
            for (auto& dep : meta["dependencies"].get<crude_json::array>())
            {
                if (dep.type() == crude_json::type_t::string)
                    result.metadata.dependencies.push_back(dep.get<std::string>());
            }
        }
    }

    // ---- Schema 版本检查 ----
    {
        int fileSchema = result.metadata.schemaVersion;
        if (fileSchema > BLUEPRINT_CURRENT_SCHEMA_VERSION)
        {
            result.errorMessage = "Blueprint file requires schema version "
                + std::to_string(fileSchema)
                + ", but this runtime only supports up to version "
                + std::to_string(BLUEPRINT_CURRENT_SCHEMA_VERSION)
                + ". Please update the application.";
            return result;
        }

        // fileSchema == 0 表示老文件没有 schemaVersion 字段，视为版本 1
        if (fileSchema == 0)
        {
            result.metadata.schemaVersion = 1;
        }
    }

    result.success = true;
    return result;
}

} // namespace Runtime
} // namespace NodeEditor