// Runtime/exporter/BlueprintExporter_Util.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the Util section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;
bool JsonBlueprintExporter::validate(const BlueprintData& data, std::vector<std::string>& errors) const
{
    errors.clear();
    
    // 验证节点 ID 唯一性 & 一次性收集所有 pinId（用于后续链接验证）
    std::unordered_map<NodeId, int> nodeIds;
    std::unordered_set<PinId> allPinIds;
    for (const auto& node : data.nodes)
    {
        if (node.id == InvalidNodeId)
        {
            errors.push_back("Node has invalid ID");
        }
        
        if (nodeIds.find(node.id) != nodeIds.end())
        {
            errors.push_back("Duplicate node ID: " + std::to_string(node.id));
        }
        nodeIds[node.id]++;
        
        for (const auto& pin : node.pins)
            allPinIds.insert(pin.id);
    }
    
    // 验证链接 — O(L) 而非 O(L*N*P)
    for (const auto& link : data.links)
    {
        if (link.id == InvalidLinkId)
        {
            errors.push_back("Link has invalid ID");
        }
        
        if (link.startPinId == InvalidPinId || link.endPinId == InvalidPinId)
        {
            errors.push_back("Link has invalid pin IDs");
        }
        
        if (allPinIds.find(link.startPinId) == allPinIds.end())
        {
            errors.push_back("Link references non-existent start pin: " + std::to_string(link.startPinId));
        }
        
        if (allPinIds.find(link.endPinId) == allPinIds.end())
        {
            errors.push_back("Link references non-existent end pin: " + std::to_string(link.endPinId));
        }
    }
    
    return errors.empty();
}

std::vector<ExportFormat> JsonBlueprintExporter::getSupportedFormats() const
{
    return { ExportFormat::JSON };
}

std::string JsonBlueprintExporter::variantToJson(const Variant& value) const
{
    switch (value.type)
    {
    case PinDataType::Boolean:
        return value.numAsBool() ? "true" : "false";
    case PinDataType::Integer:
        return std::to_string(value.numAsInt());
    case PinDataType::Float:
    {
        double d = value.numAsDouble();
        // JSON 不允许 Infinity 和 NaN，将其替换为 0 并在调试时可检测
        if (std::isinf(d) || std::isnan(d)) d = 0.0;
        // %.17g: 最短精确往返表示，去除尾零；不用 std::to_string 的 %.6f
        char buf[64];
        std::snprintf(buf, sizeof(buf), "%.17g", d);
        return std::string(buf);
    }
    case PinDataType::String:
        return "\"" + escapeJson(value.stringValue) + "\"";
    case PinDataType::Object:
        return "\"" + escapeJson(value.stringValue) + "\"";
    case PinDataType::Array:
    {
        std::string s = "[";
        for (size_t i = 0; i < value.arrayValue.size(); ++i)
        {
            if (i > 0) s += ",";
            s += variantToJson(value.arrayValue[i]);
        }
        s += "]";
        return s;
    }
    case PinDataType::Map:
    {
        // 序列化为 [[key1,val1],[key2,val2]] 以支持非 string 键
        std::string s = "[";
        for (size_t i = 0; i < value.mapValue.size(); ++i)
        {
            if (i > 0) s += ",";
            const auto& kv = value.mapValue[i];
            s += "[" + variantToJson(kv.first) + "," + variantToJson(kv.second) + "]";
        }
        s += "]";
        return s;
    }
    case PinDataType::Set:
    {
        std::string s = "[";
        for (size_t i = 0; i < value.arrayValue.size(); ++i)
        {
            if (i > 0) s += ",";
            s += variantToJson(value.arrayValue[i]);
        }
        s += "]";
        return s;
    }
    case PinDataType::Any:
        // Any 不可序列化（指向运行时跨语言对象），输出 null 占位。
        return "null";
    default:
        return "null";
    }
}

Variant JsonBlueprintExporter::jsonToVariant(const std::string& json, PinDataType type) const
{
    Variant result;
    result.type = type;

    // 关键：先按 type 初始化 numericValue 到对应零值，避免后续 JSON 解析失败或类型不匹配时
    // numericValue 保持 monostate，导致运行时 std::get 抛 bad_variant_access 崩溃。
    switch (type)
    {
    case PinDataType::Boolean: result.numericValue = false;             break;
    case PinDataType::Integer: result.numericValue = static_cast<int64_t>(0); break;
    case PinDataType::Float:   result.numericValue = 0.0;               break;
    default: break;
    }

    crude_json::value val = crude_json::value::parse(json);
    if (val.is_discarded())
        return result;

    switch (type)
    {
    case PinDataType::Boolean:
        if (val.type() == crude_json::type_t::boolean)
            result.numericValue = val.get<bool>();
        else if (val.type() == crude_json::type_t::number)
            result.numericValue = (val.get<double>() != 0.0);
        break;
    case PinDataType::Integer:
        if (val.type() == crude_json::type_t::number)
            result.numericValue = static_cast<int64_t>(val.get<double>());
        else if (val.type() == crude_json::type_t::boolean)
            result.numericValue = static_cast<int64_t>(val.get<bool>() ? 1 : 0);
        else if (val.type() == crude_json::type_t::string)
        {
            const auto& s = val.get<std::string>();
            char* end = nullptr;
            int64_t v = std::strtoll(s.c_str(), &end, 10);
            if (end != s.c_str()) result.numericValue = v;
        }
        break;
    case PinDataType::Float:
        if (val.type() == crude_json::type_t::number)
            result.numericValue = val.get<double>();
        else if (val.type() == crude_json::type_t::boolean)
            result.numericValue = val.get<bool>() ? 1.0 : 0.0;
        else if (val.type() == crude_json::type_t::string)
        {
            const auto& s = val.get<std::string>();
            char* end = nullptr;
            double v = std::strtod(s.c_str(), &end);
            if (end != s.c_str()) result.numericValue = v;
        }
        break;
    case PinDataType::String:
        if (val.type() == crude_json::type_t::string)
            result.stringValue = val.get<std::string>();
        break;
    case PinDataType::Object:
        if (val.type() == crude_json::type_t::string)
            result.stringValue = val.get<std::string>();
        break;
    case PinDataType::Array:
        if (val.type() == crude_json::type_t::array)
        {
            for (auto& elem : val.get<crude_json::array>())
            {
                // 数组元素反序列化为 Any（通过 JSON 类型推断）
                Variant elemVar;
                if (elem.type() == crude_json::type_t::boolean)
                    elemVar = Variant(elem.get<bool>());
                else if (elem.type() == crude_json::type_t::number)
                    elemVar = Variant(elem.get<double>());
                else if (elem.type() == crude_json::type_t::string)
                    elemVar = Variant(elem.get<std::string>());
                result.arrayValue.push_back(std::move(elemVar));
            }
        }
        break;
    case PinDataType::Map:
        if (val.type() == crude_json::type_t::object)
        {
            // 旧格式：JSON object (string keys)
            for (auto& kv : val.get<crude_json::object>())
            {
                Variant keyVar(kv.first);
                Variant elemVar;
                if (kv.second.type() == crude_json::type_t::boolean)
                    elemVar = Variant(kv.second.get<bool>());
                else if (kv.second.type() == crude_json::type_t::number)
                    elemVar = Variant(kv.second.get<double>());
                else if (kv.second.type() == crude_json::type_t::string)
                    elemVar = Variant(kv.second.get<std::string>());
                result.mapSet(keyVar, elemVar);
            }
        }
        else if (val.type() == crude_json::type_t::array)
        {
            // 新格式：JSON array of [key, value] pairs
            for (auto& elem : val.get<crude_json::array>())
            {
                if (elem.type() == crude_json::type_t::array)
                {
                    const auto& pairArr = elem.get<crude_json::array>();
                    if (pairArr.size() >= 2)
                    {
                        // 推断 key 类型
                        Variant keyVar;
                        if (pairArr[0].type() == crude_json::type_t::boolean)
                            keyVar = Variant(pairArr[0].get<bool>());
                        else if (pairArr[0].type() == crude_json::type_t::number)
                            keyVar = Variant(pairArr[0].get<double>());
                        else if (pairArr[0].type() == crude_json::type_t::string)
                            keyVar = Variant(pairArr[0].get<std::string>());
                        // 推断 value 类型
                        Variant valVar;
                        if (pairArr[1].type() == crude_json::type_t::boolean)
                            valVar = Variant(pairArr[1].get<bool>());
                        else if (pairArr[1].type() == crude_json::type_t::number)
                            valVar = Variant(pairArr[1].get<double>());
                        else if (pairArr[1].type() == crude_json::type_t::string)
                            valVar = Variant(pairArr[1].get<std::string>());
                        result.mapSet(keyVar, valVar);
                    }
                }
            }
        }
        break;
    case PinDataType::Set:
        if (val.type() == crude_json::type_t::array)
        {
            for (auto& elem : val.get<crude_json::array>())
            {
                Variant elemVar;
                if (elem.type() == crude_json::type_t::boolean)
                    elemVar = Variant(elem.get<bool>());
                else if (elem.type() == crude_json::type_t::number)
                    elemVar = Variant(elem.get<double>());
                else if (elem.type() == crude_json::type_t::string)
                    elemVar = Variant(elem.get<std::string>());
                result.setAdd(elemVar);
            }
        }
        break;
    default:
        break;
    }

    return result;
}



} // namespace Runtime
} // namespace NodeEditor