// Runtime/exporter/BlueprintExporter_RuntimeExport.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the RuntimeExport section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;
std::string JsonBlueprintExporter::exportRuntimeToString(const BlueprintData& data, const ExportOptions& options) const
{
    std::ostringstream oss;
    int indentLevel = 0;
    bool pretty = options.prettyPrint;
    
    auto writeIndent = [&]() {
        if (pretty) oss << indentJson(indentLevel, options.indent);
    };
    
    auto writeNewline = [&]() {
        if (pretty) oss << "\n";
    };
    
    // 开始根对象
    oss << "{";
    writeNewline();
    indentLevel++;
    
    // 文件类型标识
    writeIndent();
    oss << "\"fileType\": \"runtime\",";
    writeNewline();
    
    // ================================================================
    // 元数据（运行时只保留 name/description/version/schemaVersion）
    // ================================================================
    if (options.includeMetadata)
    {
        writeIndent();
        oss << "\"metadata\": {";
        writeNewline();
        indentLevel++;
        
        writeIndent();
        oss << "\"schemaVersion\": " << data.metadata.schemaVersion << ",";
        writeNewline();

        writeIndent();
        // blueprintClass 以整数存储（0=Actor, 1=FunctionLibrary），节省空间，枚举扩展向后兼容
        oss << "\"blueprintClass\": " << static_cast<int>(data.metadata.blueprintClass) << ",";
        writeNewline();
        
        writeIndent();
        oss << "\"name\": \"" << escapeJson(data.metadata.name) << "\",";
        writeNewline();
        
        writeIndent();
        oss << "\"description\": \"" << escapeJson(data.metadata.description) << "\",";
        writeNewline();
        
        writeIndent();
        oss << "\"version\": \"" << escapeJson(data.metadata.version) << "\"";

        // dependencies（可选，非空时写入）
        if (!data.metadata.dependencies.empty())
        {
            oss << ",";
            writeNewline();
            writeIndent();
            oss << "\"dependencies\": [";
            for (size_t di = 0; di < data.metadata.dependencies.size(); ++di)
            {
                oss << "\"" << escapeJson(data.metadata.dependencies[di]) << "\"";
                if (di + 1 < data.metadata.dependencies.size()) oss << ", ";
            }
            oss << "]";
        }
        
        writeNewline();
        indentLevel--;
        writeIndent();
        oss << "},";
        writeNewline();
    }
    
    // ================================================================
    // 节点列表（运行时数据：不含 position/size/isCollapsed）
    // ================================================================
    writeIndent();
    oss << "\"nodes\": [";
    writeNewline();
    indentLevel++;
    
    bool firstNode = true;
    for (size_t i = 0; i < data.nodes.size(); ++i)
    {
        const auto& node = data.nodes[i];
        
        // 应用节点过滤器
        if (options.nodeFilter && !options.nodeFilter(node))
            continue;
        
        if (!firstNode) { oss << ","; writeNewline(); }
        firstNode = false;
        
        writeIndent();
        oss << "{";
        writeNewline();
        indentLevel++;
        
        // 节点基础信息
        writeIndent();
        oss << "\"id\": " << node.id << ",";
        writeNewline();
        
        writeIndent();
        oss << "\"definitionId\": \"" << escapeJson(node.definitionId) << "\",";
        writeNewline();
        
        writeIndent();
        oss << "\"definitionVersion\": " << node.definitionVersion << ",";
        writeNewline();
        
        writeIndent();
        oss << "\"name\": \"" << escapeJson(node.name) << "\",";
        writeNewline();
        
        // 引脚列表
        writeIndent();
        oss << "\"pins\": [";
        writeNewline();
        indentLevel++;
        
        for (size_t j = 0; j < node.pins.size(); ++j)
        {
            const auto& pin = node.pins[j];
            
            writeIndent();
            oss << "{";
            writeNewline();
            indentLevel++;
            
            // 必选字段：id, kind(int), dataType(int)
            writeIndent(); oss << "\"id\": " << pin.id << ","; writeNewline();
            writeIndent(); oss << "\"kind\": " << static_cast<int>(pin.kind) << ","; writeNewline();
            writeIndent(); oss << "\"dataType\": " << static_cast<int>(pin.dataType);
            // 可选字段：仅在非默认值时写入（减少 JSON 体积）
            if (!pin.name.empty())
            {
                oss << ","; writeNewline();
                writeIndent(); oss << "\"name\": \"" << escapeJson(pin.name) << "\"";
            }
            if (pin.isExec)
            {
                oss << ","; writeNewline();
                writeIndent(); oss << "\"isExec\": true";
            }
            if (pin.allowMultiple)
            {
                oss << ","; writeNewline();
                writeIndent(); oss << "\"allowMultiple\": true";
            }
            if (pin.defaultValue.type != PinDataType::Unknown)
            {
                oss << ","; writeNewline();
                writeIndent(); oss << "\"defaultValue\": " << variantToJson(pin.defaultValue);
            }
            writeNewline();
            indentLevel--;
            writeIndent();
            oss << "}";
            if (j < node.pins.size() - 1) oss << ",";
            writeNewline();
        }
        
        indentLevel--;
        writeIndent();
        oss << "]";
        
        // 节点启用状态（仅在 false 时写入，默认 true）
        if (!node.isEnabled)
        {
            oss << ","; writeNewline();
            writeIndent();
            oss << "\"isEnabled\": false";
        }

        // 折叠状态（v2+，仅在 true 时写入，默认 false）
        if (node.isCollapsed)
        {
            oss << ","; writeNewline();
            writeIndent();
            oss << "\"isCollapsed\": true";
        }
        
        // 节点数据（配置参数，如常量值）
        if (!node.nodeData.empty())
        {
            oss << ","; writeNewline();
            writeIndent();
            oss << "\"nodeData\": {";
            writeNewline();
            indentLevel++;
            
            size_t idx = 0;
            for (const auto& kv : node.nodeData)
            {
                writeIndent();
                oss << "\"" << escapeJson(kv.first) << "\": " << variantToJson(kv.second);
                if (idx < node.nodeData.size() - 1) oss << ",";
                writeNewline();
                idx++;
            }
            
            indentLevel--;
            writeIndent();
            oss << "}";
        }
        
        // 自定义属性
        if (!node.customProperties.empty())
        {
            oss << ","; writeNewline();
            writeIndent();
            oss << "\"customProperties\": {";
            writeNewline();
            indentLevel++;
            
            size_t idx = 0;
            for (const auto& kv : node.customProperties)
            {
                if (options.propertyFilter && !options.propertyFilter(kv.first))
                {
                    idx++;
                    continue;
                }
                writeIndent();
                oss << "\"" << escapeJson(kv.first) << "\": \"" << escapeJson(kv.second) << "\"";
                if (idx < node.customProperties.size() - 1) oss << ",";
                writeNewline();
                idx++;
            }
            
            indentLevel--;
            writeIndent();
            oss << "}";
        }
        
        writeNewline();
        indentLevel--;
        writeIndent();
        oss << "}";
    }
    
    writeNewline();
    indentLevel--;
    writeIndent();
    oss << "],";
    writeNewline();
    
    // ================================================================
    // 链接列表
    // ================================================================
    writeIndent();
    oss << "\"links\": [";
    writeNewline();
    indentLevel++;
    
    for (size_t i = 0; i < data.links.size(); ++i)
    {
        const auto& link = data.links[i];
        
        writeIndent();
        oss << "{";
        writeNewline();
        indentLevel++;
        
        writeIndent(); oss << "\"id\": " << link.id << ","; writeNewline();
        writeIndent(); oss << "\"startPinId\": " << link.startPinId << ","; writeNewline();
        writeIndent(); oss << "\"endPinId\": " << link.endPinId << ","; writeNewline();
        writeIndent(); oss << "\"isEnabled\": " << (link.isEnabled ? "true" : "false"); writeNewline();
        
        indentLevel--;
        writeIndent();
        oss << "}";
        if (i < data.links.size() - 1) oss << ",";
        writeNewline();
    }
    
    indentLevel--;
    writeIndent();
    oss << "]";
    
    // ================================================================
    // 变量（运行时核心：name/dataType/isExposed/defaultValue）
    // ================================================================
    if (!data.variables.empty())
    {
        oss << ","; writeNewline();
        
        writeIndent();
        oss << "\"variables\": [";
        writeNewline();
        indentLevel++;
        
        for (size_t i = 0; i < data.variables.size(); ++i)
        {
            const auto& var = data.variables[i];
            
            writeIndent();
            oss << "{";
            writeNewline();
            indentLevel++;
            
            writeIndent(); oss << "\"name\": \"" << escapeJson(var.name) << "\","; writeNewline();
            writeIndent(); oss << "\"dataType\": " << static_cast<int>(var.dataType) << ","; writeNewline();
            if (var.containerType != ContainerType::Single)
            {
                writeIndent(); oss << "\"containerType\": " << static_cast<int>(var.containerType) << ","; writeNewline();
                writeIndent(); oss << "\"itemType\": " << static_cast<int>(var.itemType) << ","; writeNewline();
                writeIndent(); oss << "\"mapKeyType\": " << static_cast<int>(var.mapKeyType) << ","; writeNewline();
            }
            writeIndent(); oss << "\"isExposed\": " << (var.isExposed ? "true" : "false");
            
            if (var.defaultValue.type != PinDataType::Unknown)
            {
                oss << ","; writeNewline();
                writeIndent(); oss << "\"defaultValue\": " << variantToJson(var.defaultValue);
            }
            
            writeNewline();
            indentLevel--;
            writeIndent();
            oss << "}";
            if (i < data.variables.size() - 1) oss << ",";
            writeNewline();
        }
        
        indentLevel--;
        writeIndent();
        oss << "]";
    }
    
    // ── functions 数组 ───────────────────────────────────────────────────────
    if (!data.functions.empty())
    {
        oss << ","; writeNewline();
        writeIndent();
        oss << "\"functions\": [";
        writeNewline();
        indentLevel++;

        for (size_t fi = 0; fi < data.functions.size(); ++fi)
        {
            const auto& func = data.functions[fi];
            writeIndent(); oss << "{"; writeNewline();
            indentLevel++;

            writeIndent(); oss << "\"id\": \""          << escapeJson(func.id)          << "\","; writeNewline();
            writeIndent(); oss << "\"name\": \""         << escapeJson(func.name)         << "\","; writeNewline();
            writeIndent(); oss << "\"category\": \""     << escapeJson(func.category)     << "\","; writeNewline();
            writeIndent(); oss << "\"description\": \""  << escapeJson(func.description)  << "\","; writeNewline();
            writeIndent(); oss << "\"isPublic\": "       << (func.isPublic ? "true" : "false") << ","; writeNewline();

            // inputs
            writeIndent(); oss << "\"inputs\": [";
            for (size_t ii = 0; ii < func.inputs.size(); ++ii)
            {
                const auto& inp = func.inputs[ii];
                oss << "{\"name\":\"" << escapeJson(inp.name) << "\",\"dataType\":" << static_cast<int>(inp.dataType);
                if (inp.containerType != ContainerType::Single)
                {
                    oss << ",\"containerType\":" << static_cast<int>(inp.containerType);
                    oss << ",\"itemType\":" << static_cast<int>(inp.itemType);
                    oss << ",\"mapKeyType\":" << static_cast<int>(inp.mapKeyType);
                }
                oss << "}";
                if (ii + 1 < func.inputs.size()) oss << ",";
            }
            oss << "],"; writeNewline();

            // outputs
            writeIndent(); oss << "\"outputs\": [";
            for (size_t oi = 0; oi < func.outputs.size(); ++oi)
            {
                const auto& out = func.outputs[oi];
                oss << "{\"name\":\"" << escapeJson(out.name) << "\",\"dataType\":" << static_cast<int>(out.dataType);
                if (out.containerType != ContainerType::Single)
                {
                    oss << ",\"containerType\":" << static_cast<int>(out.containerType);
                    oss << ",\"itemType\":" << static_cast<int>(out.itemType);
                    oss << ",\"mapKeyType\":" << static_cast<int>(out.mapKeyType);
                }
                oss << "}";
                if (oi + 1 < func.outputs.size()) oss << ",";
            }
            oss << "],"; writeNewline();

            // nodes (sub-graph) — serialize with full pin data so the runtime
            // can execute func.nodes directly when top-level nodes are unavailable
            writeIndent(); oss << "\"nodes\": [";
            for (size_t ni = 0; ni < func.nodes.size(); ++ni)
            {
                const auto& nd = func.nodes[ni];
                oss << "{\"id\":" << nd.id
                    << ",\"definitionId\":\"" << escapeJson(nd.definitionId) << "\""
                    << ",\"name\":\"" << escapeJson(nd.name) << "\"";
                if (!nd.pins.empty())
                {
                    oss << ",\"pins\":[";
                    for (size_t pi = 0; pi < nd.pins.size(); ++pi)
                    {
                        const auto& p = nd.pins[pi];
                        oss << "{\"id\":" << p.id
                            << ",\"kind\":" << static_cast<int>(p.kind)
                            << ",\"dataType\":" << static_cast<int>(p.dataType)
                            << ",\"isExec\":" << (p.isExec ? "true" : "false");
                        if (!p.name.empty())
                            oss << ",\"name\":\"" << escapeJson(p.name) << "\"";
                        if (p.defaultValue.type != PinDataType::Unknown)
                            oss << ",\"defaultValue\":" << variantToJson(p.defaultValue);
                        oss << "}";
                        if (pi + 1 < nd.pins.size()) oss << ",";
                    }
                    oss << "]";
                }
                oss << "}";
                if (ni + 1 < func.nodes.size()) oss << ",";
            }
            oss << "],"; writeNewline();

            // links
            writeIndent(); oss << "\"links\": [";
            for (size_t li2 = 0; li2 < func.links.size(); ++li2)
            {
                const auto& lk = func.links[li2];
                oss << "{\"id\":" << lk.id << ",\"startPinId\":" << lk.startPinId << ",\"endPinId\":" << lk.endPinId << "}";
                if (li2 + 1 < func.links.size()) oss << ",";
            }
            oss << "]"; writeNewline();

            indentLevel--;
            writeIndent(); oss << "}";
            if (fi + 1 < data.functions.size()) oss << ",";
            writeNewline();
        }

        indentLevel--;
        writeIndent();
        oss << "]";
    }

    // 结束根对象
    writeNewline();
    indentLevel--;
    writeIndent();
    oss << "}";
    
    return oss.str();
}

ExportResult JsonBlueprintExporter::exportRuntimeToFile(const BlueprintData& data, const std::string& filePath, const ExportOptions& options) const
{
    ExportResult result;
    
#ifndef __EMSCRIPTEN__
    try
    {
        std::string jsonContent = exportRuntimeToString(data, options);
        
        std::string errorMsg;
        if (!m_fileSystem->WriteFile(filePath, jsonContent, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }
        
        result.success = true;
        result.outputPath = filePath;
        result.bytesWritten = jsonContent.size();
    }
    catch (const std::exception& e)
    {
        result.errorMessage = std::string("Exception: ") + e.what();
    }
#else
    {
        std::string jsonContent = exportRuntimeToString(data, options);
        
        std::string errorMsg;
        if (!m_fileSystem->WriteFile(filePath, jsonContent, errorMsg))
        {
            result.errorMessage = errorMsg;
            return result;
        }
        
        result.success = true;
        result.outputPath = filePath;
        result.bytesWritten = jsonContent.size();
    }
#endif
    
    return result;
}

} // namespace Runtime
} // namespace NodeEditor