// Runtime/exporter/BlueprintExporter_EditorImport.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the EditorImport section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;
ImportResult JsonBlueprintExporter::importEditorFromStrings(const std::string& runtimeContent, const std::string& editorContent, const ImportOptions& options) const
{
    // 先加载 Runtime 数据
    ImportResult result = importRuntimeFromString(runtimeContent, options);
    if (!result.success)
    {
        result.errorMessage = "Runtime import failed: " + result.errorMessage;
        return result;
    }
    
    // 解析 Editor 附加数据
    crude_json::value editorRoot = crude_json::value::parse(editorContent);
    if (editorRoot.is_discarded())
    {
        result.warnings.push_back("Editor JSON parse error, editor data ignored");
        return result;
    }
    
    if (editorRoot.type() != crude_json::type_t::object)
    {
        result.warnings.push_back("Editor JSON root must be an object, editor data ignored");
        return result;
    }
    
    // ---- 辅助别名（使用文件级辅助函数，通过 lambda 保留默认参数）----
    auto getNumber = [](const crude_json::value& obj, const char* key, double defaultVal = 0.0) { return getJsonNumber(obj, key, defaultVal); };
    auto getString = [](const crude_json::value& obj, const char* key) { return getJsonString(obj, key); };
    auto getBool   = [](const crude_json::value& obj, const char* key, bool defaultVal = false) { return getJsonBool(obj, key, defaultVal); };
    
    // ---- 合并元数据（author、时间戳）----
    if (editorRoot.contains("metadata") && editorRoot["metadata"].type() == crude_json::type_t::object)
    {
        auto& meta = editorRoot["metadata"];
        std::string author = getString(meta, "author");
        std::string createdAt = getString(meta, "createdAt");
        std::string updatedAt = getString(meta, "updatedAt");
        
        if (!author.empty())    result.data.metadata.author    = author;
        if (!createdAt.empty()) result.data.metadata.createdAt = createdAt;
        if (!updatedAt.empty()) result.data.metadata.updatedAt = updatedAt;
    }
    
    // ---- 合并节点编辑器数据（position/size/isCollapsed）----
    if (editorRoot.contains("nodes") && editorRoot["nodes"].type() == crude_json::type_t::array)
    {
        // 建立 nodeId -> node 指针映射
        std::unordered_map<NodeId, NodeInstance*> nodeMap;
        for (auto& node : result.data.nodes)
        {
            nodeMap[node.id] = &node;
        }
        
        for (auto& editorNode : editorRoot["nodes"].get<crude_json::array>())
        {
            if (editorNode.type() != crude_json::type_t::object) continue;
            
            NodeId nodeId = static_cast<NodeId>(getNumber(editorNode, "id"));
            auto it = nodeMap.find(nodeId);
            if (it == nodeMap.end()) continue;
            
            NodeInstance* node = it->second;
            
            // 位置
            if (editorNode.contains("position") && editorNode["position"].type() == crude_json::type_t::object)
            {
                auto& pos = editorNode["position"];
                node->position.x = static_cast<float>(getNumber(pos, "x"));
                node->position.y = static_cast<float>(getNumber(pos, "y"));
            }
            
            // 尺寸
            if (editorNode.contains("size") && editorNode["size"].type() == crude_json::type_t::object)
            {
                auto& sz = editorNode["size"];
                node->size.width  = static_cast<float>(getNumber(sz, "width"));
                node->size.height = static_cast<float>(getNumber(sz, "height"));
            }
            
            // 折叠状态
            if (editorNode.contains("isCollapsed"))
            {
                node->isCollapsed = getBool(editorNode, "isCollapsed", false);
            }
        }
    }
    
    // ---- 合并变量附加信息（category/tooltip）----
    if (editorRoot.contains("variables") && editorRoot["variables"].type() == crude_json::type_t::array)
    {
        // 建立 name -> variable 指针映射
        std::unordered_map<std::string, VariableDefinition*> varMap;
        for (auto& var : result.data.variables)
        {
            varMap[var.name] = &var;
        }
        
        for (auto& editorVar : editorRoot["variables"].get<crude_json::array>())
        {
            if (editorVar.type() != crude_json::type_t::object) continue;
            
            std::string name = getString(editorVar, "name");
            auto it = varMap.find(name);
            if (it == varMap.end()) continue;
            
            VariableDefinition* var = it->second;
            
            std::string category = getString(editorVar, "category");
            std::string tooltip  = getString(editorVar, "tooltip");
            
            if (!category.empty()) var->category = category;
            if (!tooltip.empty())  var->tooltip  = tooltip;
        }
    }
    
    // ---- 合并注释 ----
    if (editorRoot.contains("comments") && editorRoot["comments"].type() == crude_json::type_t::array)
    {
        for (auto& cmtJson : editorRoot["comments"].get<crude_json::array>())
        {
            if (cmtJson.type() != crude_json::type_t::object) continue;
            
            CommentRegion cmt;
            cmt.id    = getString(cmtJson, "id");
            cmt.text  = getString(cmtJson, "text");
            cmt.color = getString(cmtJson, "color");
            cmt.alpha = static_cast<float>(getNumber(cmtJson, "alpha", 0.5));
            
            if (cmtJson.contains("position") && cmtJson["position"].type() == crude_json::type_t::object)
            {
                cmt.position.x = static_cast<float>(getNumber(cmtJson["position"], "x"));
                cmt.position.y = static_cast<float>(getNumber(cmtJson["position"], "y"));
            }
            if (cmtJson.contains("size") && cmtJson["size"].type() == crude_json::type_t::object)
            {
                cmt.size.width  = static_cast<float>(getNumber(cmtJson["size"], "width"));
                cmt.size.height = static_cast<float>(getNumber(cmtJson["size"], "height"));
            }
            
            result.data.comments.push_back(std::move(cmt));
        }
    }
    
    // ---- 合并视图信息 ----
    if (editorRoot.contains("viewInfo") && editorRoot["viewInfo"].type() == crude_json::type_t::object)
    {
        auto& viewJson = editorRoot["viewInfo"];
        if (viewJson.contains("viewPosition") && viewJson["viewPosition"].type() == crude_json::type_t::object)
        {
            result.data.viewInfo.viewPosition.x = static_cast<float>(getNumber(viewJson["viewPosition"], "x"));
            result.data.viewInfo.viewPosition.y = static_cast<float>(getNumber(viewJson["viewPosition"], "y"));
        }
        result.data.viewInfo.viewScale = static_cast<float>(getNumber(viewJson, "viewScale", 1.0));
    }
    
    result.bytesRead += editorContent.size();
    return result;
}



} // namespace Runtime
} // namespace NodeEditor