# tools/split_exporter.ps1
# Split Runtime/BlueprintExporter.cpp (2064 lines) into per-section files under
# Runtime/exporter/, parallel to the handlers/ and nodedefs/ split.
#
# Sections (line numbers refer to the original BlueprintExporter.cpp):
#   106-600   RuntimeExport     -> exportRuntimeToString / exportRuntimeToFile
#   606-898   EditorExport      -> exportEditorToString / exportEditorFiles
#   904-1559  RuntimeImport     -> importRuntimeFrom* / importMetadataFrom*
#   1565-1723 EditorImport      -> importEditorFromStrings
#   1729-2000 Util              -> validate / variantToJson / jsonToVariant / getSupportedFormats
#
# Original 1-101 (JSON helpers + ApplySchemaMigrations) -> exporter/BlueprintExporter_Internal.h
# Original 2002-end (BinaryBlueprintExporter stubs)     -> kept in BlueprintExporter.cpp

$ErrorActionPreference = 'Stop'

$src    = "$PSScriptRoot/../Runtime/BlueprintExporter.cpp"
$dstDir = "$PSScriptRoot/../Runtime/exporter"

if (-not (Test-Path $dstDir)) {
    New-Item -ItemType Directory -Path $dstDir | Out-Null
}

# Read source as UTF-8 bytes -> string (preserve original encoding, do not let
# PowerShell guess GBK / ANSI)
$bytes = [System.IO.File]::ReadAllBytes($src)
$text  = [System.Text.Encoding]::UTF8.GetString($bytes)
$lines = $text -split "`r?`n"

$sections = @(
    @{Name='RuntimeExport';  Start=106;  End=600 },
    @{Name='EditorExport';   Start=606;  End=898 },
    @{Name='RuntimeImport';  Start=904;  End=1559},
    @{Name='EditorImport';   Start=1565; End=1723},
    @{Name='Util';           Start=1729; End=2000}
)

$header = @"
// Runtime/exporter/BlueprintExporter_{SEC}.cpp
// Generated by tools/split_exporter.ps1 from Runtime/BlueprintExporter.cpp
//
// Implements the {SEC} section of JsonBlueprintExporter.
// Shared helpers (escapeJson / indentJson / getJsonNumber / ...) live in
// BlueprintExporter_Internal.h.

#include "../BlueprintExporter.h"
#include "BlueprintExporter_Internal.h"
#include "../../Utils/Json/crude_json.h"
#include <sstream>
#include <iomanip>
#include <ctime>
#include <cmath>
#include <cstdio>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#  define WIN32_LEAN_AND_MEAN
#  endif
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <windows.h>
#endif

namespace NodeEditor {
namespace Runtime {

using exporter_internal::escapeJson;
using exporter_internal::indentJson;
using exporter_internal::getJsonNumber;
using exporter_internal::getJsonString;
using exporter_internal::getJsonBool;
using exporter_internal::ApplySchemaMigrations;

"@

$footer = @"

} // namespace Runtime
} // namespace NodeEditor
"@

foreach ($sec in $sections) {
    $name = $sec.Name
    $startIdx = $sec.Start - 1
    $endIdx   = $sec.End   - 1
    $body = ($lines[$startIdx..$endIdx] -join "`n")

    $h = $header -replace '\{SEC\}', $name
    $content = $h + $body + "`n" + $footer

    $outPath = Join-Path $dstDir "BlueprintExporter_$name.cpp"
    [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $outPath ($($endIdx - $startIdx + 1) lines from source)"
}

Write-Host "Done. Generated $($sections.Count) files in $dstDir"
