# tools/split_nodedefs_ai.ps1
# Split Runtime/nodedefs/BuiltinNodeDefs_AI.cpp (~700 lines, 39 nodes) into
# 4 sub-files grouped by node ID prefix, mirroring the handlers/ split.
#
# Grouping (loose semantic clustering, since node-def categories don't strictly
# match handler files):
#   _AI_JSON.cpp    — JSON.*  + Schema.*
#   _AI_LLM.cpp     — LLM.*   + String.Template + Intent.Classify + Context.Compress
#   _AI_Tool.cpp    — Tool.*  + MCP.Call + HTTP.Retry
#   _AI_Agent.cpp   — Agent.* + Memory.* + Trigger.* + UserInput.Wait
#
# Algorithm:
#   1. Scan the source for all top-level `reg("XXX.YYY", ...)` calls.
#   2. For each call, locate its start line and end line (the terminating
#      ");" at brace depth 0 inside the lambda body).
#   3. Group calls by prefix mapping table; concatenate bodies into per-file
#      payloads.
#   4. Emit one .cpp per group with the standard header + lambda definition +
#      payload + namespace footer.

$ErrorActionPreference = 'Stop'

$src    = "$PSScriptRoot/../Runtime/nodedefs/BuiltinNodeDefs_AI.cpp"
$dstDir = "$PSScriptRoot/../Runtime/nodedefs"

# Read source as raw UTF-8 to preserve any embedded Chinese comments
$bytes = [System.IO.File]::ReadAllBytes($src)
$text  = [System.Text.Encoding]::UTF8.GetString($bytes)
$lines = $text -split "`r?`n"

# Map: node ID full name -> target subgroup
$groupMap = @{
    'JSON' = 'JSON'; 'Schema' = 'JSON'
    'LLM' = 'LLM'; 'String' = 'LLM'; 'Intent' = 'LLM'; 'Context' = 'LLM'
    'Tool' = 'Tool'; 'MCP' = 'Tool'; 'HTTP' = 'Tool'
    'Agent' = 'Agent'; 'Memory' = 'Agent'; 'Trigger' = 'Agent'; 'UserInput' = 'Agent'
}

# Group target function names (so RegisterNodeDefs_AI can call them all)
$groupOrder = @('JSON','LLM','Tool','Agent')

# Scan: find each reg("...") call and its line range
$regCalls = @()
for ($i = 0; $i -lt $lines.Length; $i++) {
    if ($lines[$i] -notmatch 'reg\("([^"]+)"') { continue }
    $id     = $Matches[1]
    $prefix = ($id -split '\.')[0]
    if (-not $groupMap.ContainsKey($prefix)) {
        Write-Warning "Unknown prefix '$prefix' on line $($i+1) (id=$id) — skipped"
        continue
    }

    # Find the lambda's terminating ");" at the outermost depth.
    # Heuristic: starting from the reg(...) line, scan forward tracking
    # parentheses depth on visible characters (ignoring string literals).
    # When depth returns to 0 and we see ');' the call is complete.
    $depth = 0
    $startLine = $i
    $endLine   = $i
    $started   = $false
    for ($j = $i; $j -lt $lines.Length; $j++) {
        $line = $lines[$j]
        # Strip line comments to avoid counting parens inside `// ...`
        $codeOnly = $line -replace '//.*$',''
        # Strip simple string literals to avoid counting parens/quotes inside
        $codeOnly = [regex]::Replace($codeOnly, '"(\\.|[^"\\])*"', '""')
        foreach ($ch in $codeOnly.ToCharArray()) {
            if     ($ch -eq '(') { $depth++; $started = $true }
            elseif ($ch -eq ')') { $depth-- }
        }
        if ($started -and $depth -eq 0) {
            $endLine = $j
            break
        }
    }

    $regCalls += [PSCustomObject]@{
        ID       = $id
        Prefix   = $prefix
        Group    = $groupMap[$prefix]
        Start    = $startLine
        End      = $endLine
    }
    $i = $endLine   # skip past the call
}

Write-Host "Found $($regCalls.Count) reg(...) calls"
$regCalls | Group-Object Group | ForEach-Object { Write-Host ("  {0,-6}: {1} nodes" -f $_.Name, $_.Count) }

# Build payloads per group, preserving relative order within each group
$payloads = @{}
foreach ($g in $groupOrder) { $payloads[$g] = @() }
foreach ($call in $regCalls) {
    $callLines = $lines[$call.Start..$call.End]
    # Find any preceding comment line(s) immediately above (within 3 lines)
    $commentLines = @()
    $k = $call.Start - 1
    while ($k -ge 0 -and ($lines[$k] -match '^\s*//' -or $lines[$k] -match '^\s*$')) {
        if ($lines[$k] -match '^\s*//') { $commentLines = ,$lines[$k] + $commentLines }
        elseif ($commentLines.Count -gt 0) { break }
        $k--
        if (($call.Start - $k) -gt 4) { break }
    }
    $block = ($commentLines + $callLines) -join "`n"
    $payloads[$call.Group] += $block + "`n"
}

# Header / footer templates (English ASCII to avoid any encoding pitfalls)
$header = @"
// Runtime/nodedefs/BuiltinNodeDefs_AI_{SUB}.cpp
// Generated by tools/split_nodedefs_ai.ps1 from BuiltinNodeDefs_AI.cpp
//
// Contains the RegisterNodeDefs_AI_{SUB}() function, registering AI/{SUB}
// node definitions. Called by RegisterNodeDefs_AI().
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

void RegisterNodeDefs_AI_{SUB}(INodeRegistry& registry)
{
    auto reg = [&registry](const char* id, const char* name, const char* category,
                  std::vector<PinDefinition> inputs, std::vector<PinDefinition> outputs,
                  const char* color = "", const char* edType = "")
    { RegisterNodeDef(registry, id, name, category, std::move(inputs), std::move(outputs), color, edType); };

"@

$footer = @"

}

} // namespace Runtime
} // namespace NodeEditor
"@

foreach ($g in $groupOrder) {
    $h = $header -replace '\{SUB\}', $g
    $content = $h + ($payloads[$g] -join "`n") + $footer
    $outPath = Join-Path $dstDir "BuiltinNodeDefs_AI_$g.cpp"
    [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $outPath"
}

Write-Host "Done. Generated 4 files. Now: (1) update BuiltinNodeDefs_AI.cpp to call sub-functions, (2) add forward decls to _Internal.h, (3) update CMakeLists.txt"
