# tools/split_nodedefs.ps1
# 把 Runtime/BuiltinNodeDefs.cpp 中的各 RegisterNodeDefs_XX 函数
# 拆分到 Runtime/nodedefs/BuiltinNodeDefs_XX.cpp（每分类一个文件）。
#
# 使用 UTF-8（带 BOM 兼容）读取，确保中文注释不乱码。

$ErrorActionPreference = 'Stop'

$src = "$PSScriptRoot/../Runtime/BuiltinNodeDefs.cpp"
$dstDir = "$PSScriptRoot/../Runtime/nodedefs"

if (-not (Test-Path $dstDir)) {
    New-Item -ItemType Directory -Path $dstDir | Out-Null
}

# 读取原文件（按字节读以保留原始 UTF-8 编码）
$bytes = [System.IO.File]::ReadAllBytes($src)
$text  = [System.Text.Encoding]::UTF8.GetString($bytes)
$lines = $text -split "`r?`n"

# 各分类的起止行号（行号从 1 开始）— 与 BuiltinNodeDefs.cpp 中实际位置一致
$categories = @(
    @{Name='Flow';       Start=84;   End=225 },
    @{Name='Action';     Start=226;  End=297 },
    @{Name='Math';       Start=298;  End=646 },
    @{Name='Debug';      Start=647;  End=694 },
    @{Name='String';     Start=695;  End=872 },
    @{Name='Array';      Start=873;  End=981 },
    @{Name='Map';        Start=982;  End=1118},
    @{Name='Tree';       Start=1119; End=1139},
    @{Name='Houdini';    Start=1140; End=1157},
    @{Name='Time';       Start=1158; End=1210},
    @{Name='Data';       Start=1211; End=1248},
    @{Name='Misc';       Start=1249; End=1387},
    @{Name='Conversion'; Start=1388; End=1450},
    @{Name='Event';      Start=1451; End=1708},
    @{Name='Function';   Start=1709; End=1736},
    @{Name='EventBus';   Start=1737; End=1771},
    @{Name='Retry';      Start=1772; End=1811},
    @{Name='File';       Start=1812; End=1939},
    @{Name='Network';    Start=1940; End=2079},
    @{Name='AI';         Start=2080; End=2768},
    @{Name='Game';       Start=2769; End=2908},
    @{Name='Save';       Start=2909; End=2988},
    @{Name='GameMath';   Start=2989; End=3254},
    @{Name='Socket';     Start=3255; End=3376},
    @{Name='GameExtra';  Start=3377; End=3548}
)

$header = @"
// Runtime/nodedefs/BuiltinNodeDefs_{CAT}.cpp
// Generated by tools/split_nodedefs.ps1 from Runtime/BuiltinNodeDefs.cpp
//
// Contains only the RegisterNodeDefs_{CAT}() implementation.
// Shared helpers and forward declarations live in BuiltinNodeDefs_Internal.h
#include "BuiltinNodeDefs_Internal.h"

namespace NodeEditor {
namespace Runtime {

using nodedefs_internal::MakePin;
using nodedefs_internal::MakeFlowPin;
using nodedefs_internal::MakePinEnum;
using nodedefs_internal::RegisterNodeDef;

"@

$footer = @"

} // namespace Runtime
} // namespace NodeEditor
"@

foreach ($cat in $categories) {
    $name = $cat.Name
    $startIdx = $cat.Start - 1   # convert to 0-based
    $endIdx   = $cat.End   - 1
    $body = ($lines[$startIdx..$endIdx] -join "`n")

    # 把 "static void RegisterNodeDefs_X" 改为 "void RegisterNodeDefs_X"
    # （拆分后不再是 static，需要被同一翻译单元外的 BuiltinNodeDefs.cpp 调用）
    $body = $body -replace 'static void RegisterNodeDefs_', 'void RegisterNodeDefs_'

    $h = $header -replace '\{CAT\}', $name
    $content = $h + $body + "`n" + $footer

    $outPath = Join-Path $dstDir "BuiltinNodeDefs_$name.cpp"
    # 使用 UTF-8 (无 BOM) 写入，与 handlers/ 目录其他 .cpp 保持一致
    [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host "Wrote $outPath ($($endIdx - $startIdx + 1) lines)"
}

Write-Host "Done. Generated $($categories.Count) files in $dstDir"
